### ISSUE TITLE
Make a task a sub-task of another task (by dragging?)

### ISSUE THREAD

**Issue by Tushar-Mahapatra-Git** [johannesjo/super-productivity#1124] opened 2021-04-27 14:23 UTC
I work on a task and realize that it should have been a sub-task of another already existing task. However, I am not able to make it a sub-task. Being able to drag and drop a task inside another to make it a sub-task would be helpful.

**Comment by johannesjo** [comment] 2021-04-28 07:52
Duplicate of #709

**Closed** 2021-04-28 07:53 UTC
Labels: enhancement
