### ISSUE TITLE
Google drive sync error

### ISSUE THREAD

**Issue by mbostanara** [johannesjo/super-productivity#502] opened 2020-08-15 13:23 UTC
Hi there,

I am using the final version of Super-productivity. Since last update, an error keeps happening in my app which is a bit annoying.

![image](https://user-images.githubusercontent.com/62683393/90313213-128e9a00-df4e-11ea-8cf6-3ffe2e142665.png)

When I press 'Overwrite Remote', the error will be shown again and again until I turn off the Drive sync.

**Comment by johannesjo** [comment] 2020-08-15 21:37
Thanks for reporting. Currently I'm a bit busy with other features, but I try to have a look as soon as I can. Meanwhile if
I'd recommend using Dropbox sync instead. And of course: PRs are welcome!

**Comment by mbostanara** [comment] 2020-08-24 13:21
Version 5.5.7

**Comment by johannesjo** [comment] 2020-08-25 18:51
I am unable to reproduce the issue. Is there anything interesting in the console (Ctrl+Shift+i)?

Another way to fix this might be to use a new file for syncing.

**Comment by mareekkk** [comment] 2020-08-26 03:54
I have problem syncing with Google drive as well. I have this on my Ubuntu and thought I might try to use in in my Windows machine too but it does have a problem.

With Ubuntu, it got stuck to the window where it says logging in to Google while on Windows it keeps saying that: GoogleApi: Failed to authenticate please try logging in again!

Things to note: 
With my Google account, I am using a Yubiko key to authenticate so this might be an issue too. I really like this app, I hope it can be fix, I dont want to use Dropbox for now.

**Comment by mareekkk** [comment] 2020-08-26 03:59
<blockquote class="imgur-embed-pub" lang="en" data-id="a/QwWMrXX" data-context="false" ><a href="//imgur.com/a/QwWMrXX"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by mbostanara** [comment] 2020-08-26 12:54
Thank you, @johannesjo  for your reply. Actually, this issue has not happened to me for a while. I turned it off for a couple of days and then turned it on. Then, this issue happened again once and resolved by itself.
So, I am not really sure why this was happening and why it resolved!

**Comment by johannesjo** [comment] 2020-08-26 13:53
@mareekkk I created a new issue for your issue: https://github.com/johannesjo/super-productivity/issues/514

@mbostanara, In this case, I would close this issue. Please let me know if the issue occurs again!

**Closed** 2020-08-26 13:54 UTC
Labels: bug
