### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by sk425** [johannesjo/super-productivity#1742] opened 2021-12-07 15:11 UTC
### Steps to Reproduce

1. Came back from long break and dismissed pomodoro break timer that was currently at zero
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638889665950: [Idle] Set idle time (5) 
1638889666016: [Idle] Trigger Idle 
1638889670955: [Idle] Set idle time (5) 
1638889671016: [Idle] Trigger Idle 
1638889675961: [Idle] Set idle time (5) 
1638889676018: [Idle] Trigger Idle 
1638889680968: [Idle] Set idle time (5) 
1638889681026: [Idle] Trigger Idle 
1638889685974: [Idle] Set idle time (5) 
1638889686036: [Idle] Trigger Idle 
1638889690980: [Idle] Set idle time (5) 
1638889691041: [Idle] Trigger Idle 
1638889695986: [Idle] Set idle time (5) 
1638889696041: [Idle] Trigger Idle 
1638889700993: [Idle] Set idle time (5) 
1638889701042: [Idle] Trigger Idle 
1638889705999: [Idle] Set idle time (5) 
1638889706049: [Idle] Trigger Idle 
1638889711002: [Idle] Set idle time (5) 
1638889711052: [Idle] Trigger Idle 
1638889716009: [Idle] Set idle time (5) 
1638889716053: [Idle] Trigger Idle 
1638889721013: [Idle] Set idle time (5) 
1638889721062: [Idle] Trigger Idle 
1638889824967: [Idle] Set idle time (103) 
1638889825194: [Pomodoro] Finish Pomodoro Session 
1638889825196: [Task] Toggle start 
1638889825197: [Persistence] Save to DB 
1638889825197: [Task] SetCurrentTask 
1638889825200: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment] 2021-12-09 09:55
Thank you for opening this up! Looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-09 09:55 UTC
