### ISSUE TITLE
[SP5.5.1] Crash when starting time tracking

### ISSUE THREAD

**Issue by theCalcaholic** [johannesjo/super-productivity#456] opened 2020-07-24 16:27 UTC
As of the latest update, SP keeps crashing when I press play on a task.

**System Information:**
META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

Installed via snap, channel stable/latest, revision 716

**Stack Trace:**
```
main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'includes' of undefined
    at A (main.fd58362f53e9a5e6b70d.js:1)
    at t._handleKeyboardShortcuts (main.fd58362f53e9a5e6b70d.js:1)
    at t.onKeyDown (main.fd58362f53e9a5e6b70d.js:1)
    at main.fd58362f53e9a5e6b70d.js:1
    at _a (main.fd58362f53e9a5e6b70d.js:1)
    at i (main.fd58362f53e9a5e6b70d.js:1)
    at HTMLUnknownElement.<anonymous> (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
t.handleError @ main.fd58362f53e9a5e6b70d.js:1
main.fd58362f53e9a5e6b70d.js:1 META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER Error: TypeError: Cannot read property 'includes' of undefined
    at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
    at Yi (main.fd58362f53e9a5e6b70d.js:1)
    at _a (main.fd58362f53e9a5e6b70d.js:1)
    at i (main.fd58362f53e9a5e6b70d.js:1)
    at HTMLUnknownElement.<anonymous> (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.fd58362f53e9a5e6b70d.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at e.runTask (polyfills.aebe8ecc43d658291381.js:1)
    at e.invokeTask [as invoke] (polyfills.aebe8ecc43d658291381.js:1)
t.handleError @ main.fd58362f53e9a5e6b70d.js:1
main.fd58362f53e9a5e6b70d.js:1 META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: TypeError: Cannot read property 'includes' of undefined
    at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
    at Object.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.o [as _next] (main.fd58362f53e9a5e6b70d.js:1)
    at e.__tryOrUnsub (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e._next (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.emit (main.fd58362f53e9a5e6b70d.js:1)
    at main.fd58362f53e9a5e6b70d.js:1
```

**Comment by johannesjo** [comment] 2020-07-24 16:34
Thanks for reporting. Seems to be common issue then :/

Duplicate of https://github.com/johannesjo/super-productivity/issues/453

Should be fixed by reloading the app.

**Comment by johannesjo** [comment] 2020-07-24 16:36
Would you be willing by any chance to share a copy of your data from before the update?

**Comment by theCalcaholic** [comment] 2020-07-24 16:42
Hm, I'm afraid that's not possible, because I'm using SP for my company and I can't risk to leak internal data.
Anything I could look into for you?

Reloading doesn't solve the issue for me, unfortunately

**Comment by theCalcaholic** [comment] 2020-07-24 16:43
Btw, I believe, that the crash only occurs, when I tab out of the application - so my initial impression that it's caused by starting the task might be wrong

**Comment by Minh12349** [comment] 2020-07-24 16:44
Leave a comment

**Comment by johannesjo** [comment] 2020-07-24 16:54
Not sure, really. The data is handled much more rigorous now. My first guess would be that there is some invalid data from the past.

It's weird that the Stacktrace is not containing references to the TypeScript files. Do they appear in the dialog or if you wait a little longer? We probably could figure out the error, if we were to know which line causes it and how the data in that context looks like at this point.

**Comment by theCalcaholic** [comment] 2020-07-24 18:34
Oh, right! It shows them in the error dialog:

I can reproduce the issue at any time, by selecting a task and pressing Alt, btw. So I'm certain that's the cause.

```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:503:37)
META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
```

**Comment by johannesjo** [comment] 2020-07-24 20:07
I was able to narrow this down thanks to @danielestevez. Could you maybe post a screenshot of your keyboard shortcut settings?

**Comment by danielestevez** [comment] 2020-07-24 20:10
Glad i could help, here is my shortcuts configuration, but the crash happens with the default Ctrl+C, ctrl+V so i'm not sure it has to do with shortcuts 

![image](https://user-images.githubusercontent.com/495063/88431281-00469380-cdc8-11ea-9816-edeaaa5fc625.png)

**Comment by bjerre3000** [comment] 2020-07-24 20:10
> As of the latest update, SP keeps crashing when I press play on a task.
> 
> **System Information:**
> META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
> 
> Installed via snap, channel stable/latest, revision 716
> 
> **Stack Trace:**
> ```
> main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'includes' of undefined
>     at A (main.fd58362f53e9a5e6b70d.js:1)
>     at t._handleKeyboardShortcuts (main.fd58362f53e9a5e6b70d.js:1)
>     at t.onKeyDown (main.fd58362f53e9a5e6b70d.js:1)
>     at main.fd58362f53e9a5e6b70d.js:1
>     at _a (main.fd58362f53e9a5e6b70d.js:1)
>     at i (main.fd58362f53e9a5e6b70d.js:1)
>     at HTMLUnknownElement.<anonymous> (main.fd58362f53e9a5e6b70d.js:1)
>     at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
>     at Object.onInvokeTask (main.fd58362f53e9a5e6b70d.js:1)
>     at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
> t.handleError @ main.fd58362f53e9a5e6b70d.js:1
> main.fd58362f53e9a5e6b70d.js:1 META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
> main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER Error: TypeError: Cannot read property 'includes' of undefined
>     at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
>     at Yi (main.fd58362f53e9a5e6b70d.js:1)
>     at _a (main.fd58362f53e9a5e6b70d.js:1)
>     at i (main.fd58362f53e9a5e6b70d.js:1)
>     at HTMLUnknownElement.<anonymous> (main.fd58362f53e9a5e6b70d.js:1)
>     at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
>     at Object.onInvokeTask (main.fd58362f53e9a5e6b70d.js:1)
>     at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
>     at e.runTask (polyfills.aebe8ecc43d658291381.js:1)
>     at e.invokeTask [as invoke] (polyfills.aebe8ecc43d658291381.js:1)
> t.handleError @ main.fd58362f53e9a5e6b70d.js:1
> main.fd58362f53e9a5e6b70d.js:1 META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
> polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: TypeError: Cannot read property 'includes' of undefined
>     at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
>     at Object.next (main.fd58362f53e9a5e6b70d.js:1)
>     at e.o [as _next] (main.fd58362f53e9a5e6b70d.js:1)
>     at e.__tryOrUnsub (main.fd58362f53e9a5e6b70d.js:1)
>     at e.next (main.fd58362f53e9a5e6b70d.js:1)
>     at e._next (main.fd58362f53e9a5e6b70d.js:1)
>     at e.next (main.fd58362f53e9a5e6b70d.js:1)
>     at e.next (main.fd58362f53e9a5e6b70d.js:1)
>     at e.emit (main.fd58362f53e9a5e6b70d.js:1)
>     at main.fd58362f53e9a5e6b70d.js:1
> ```@```
- # ``
```

[]()![logo.png](https://user-images.githubusercontent.com/67606122/88431349-6c41ef80-cdfa-11ea-9c02-594b08f6242f.png)

**Comment by johannesjo** [comment] 2020-07-24 20:32
Should be fixed. Please let me know if it isn't. I provide a new release asap. Thanks again!

**Closed** 2020-07-24 20:32 UTC
Labels: bug
