### ISSUE TITLE
Error: Uncaught (in promise)...

### ISSUE THREAD

**Issue by troyane** [johannesjo/super-productivity#2929] opened 2023-12-19 11:58 UTC
### Steps to Reproduce
On MacBook with M1 and Sonoma 14.2

1. Install the app from DMG (superProductivity-7.16.0-arm64.dmg).
2. In Applications -> Open.

### Error Log (Desktop only)
```
[2023-12-19 13:27:47.383] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2023-12-19 13:27:47.471] [info]  Saving backups to /
[2023-12-19 13:27:48.096] [info]  No custom styles detected at /Users/nazargerasymchuk/Library/Application Support/superProductivity/styles.css
[2023-12-19 13:27:48.216] [error] Frontend Error: Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
[2023-12-19 13:27:48.739] [error] Frontend Error Stack: statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
[2023-12-19 13:29:48.115] [info]  Error while backing up
[2023-12-19 13:29:48.118] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:31:48.115] [info]  Error while backing up
[2023-12-19 13:31:48.116] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:33:48.103] [info]  Error while backing up
[2023-12-19 13:33:48.103] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:35:48.103] [info]  Error while backing up
[2023-12-19 13:35:48.104] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:37:48.123] [info]  Error while backing up
[2023-12-19 13:37:48.124] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:39:48.120] [info]  Error while backing up
[2023-12-19 13:39:48.120] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:41:48.120] [info]  Error while backing up
[2023-12-19 13:41:48.123] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:43:48.119] [info]  Error while backing up
[2023-12-19 13:43:48.122] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:45:48.127] [info]  Error while backing up
[2023-12-19 13:45:48.129] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:47:48.128] [info]  Error while backing up
[2023-12-19 13:47:48.130] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:49:48.125] [info]  Error while backing up
[2023-12-19 13:49:48.128] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:51:48.121] [info]  Error while backing up
[2023-12-19 13:51:48.122] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:53:48.123] [info]  Error while backing up
[2023-12-19 13:53:48.123] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:55:48.124] [info]  Error while backing up
[2023-12-19 13:55:48.125] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
[2023-12-19 13:57:48.120] [info]  Error while backing up
[2023-12-19 13:57:48.120] [error] Error: EROFS: read-only file system, open '//2023-12-19.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)
```

### Stacktrace
```
statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
```

### Meta Info
META: SP7.16.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1702985268066: [FocusMode] Set focus session elapsed time 
1702985268122: [SP_ALL] Load(import) all data 
1702985268122: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment] 2023-12-19 12:41
Duplicate of #2901

**Closed by johannesjo** 2023-12-19 12:41 UTC
