### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by nomare** [johannesjo/super-productivity#1706] opened 2021-12-01 12:25 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – ru – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638361424548: [Idle] Set idle time (5) 
1638361424810: [Idle] Trigger Idle 
1638361429593: [Idle] Set idle time (5) 
1638361429825: [Idle] Trigger Idle 
1638361434622: [Idle] Set idle time (5) 
1638361434840: [Idle] Trigger Idle 
1638361439639: [Idle] Set idle time (5) 
1638361439842: [Idle] Trigger Idle 
1638361444670: [Idle] Set idle time (5) 
1638361444843: [Idle] Trigger Idle 
1638361449688: [Idle] Set idle time (5) 
1638361449861: [Idle] Trigger Idle 
1638361454712: [Idle] Set idle time (5) 
1638361454868: [Idle] Trigger Idle 
1638361459746: [Idle] Set idle time (5) 
1638361459885: [Idle] Trigger Idle 
1638361464770: [Idle] Set idle time (5) 
1638361464894: [Idle] Trigger Idle 
1638361469816: [Idle] Set idle time (5) 
1638361469909: [Idle] Trigger Idle 
1638361474842: [Idle] Set idle time (5) 
1638361474919: [Idle] Trigger Idle 
1638361479870: [Idle] Set idle time (5) 
1638361479931: [Idle] Trigger Idle 
1638361484904: [Idle] Set idle time (5) 
1638361484935: [Idle] Trigger Idle 
1638361489922: [Idle] Set idle time (5) 
1638361489940: [Idle] Trigger Idle 
1638361500990: [Idle] Set idle time (11)
```

**Comment by johannesjo** [comment] 2021-12-01 12:35
Thanks for opening this up. This is a duplicate of #1684

**Closed by johannesjo** 2021-12-01 12:35 UTC
