### ISSUE TITLE
App crashes when minimizing - Windows 11

### ISSUE THREAD

**Issue by jakubzelonka** [johannesjo/super-productivity#3428] opened 2024-09-09 12:43 UTC
### Steps to Reproduce

1. App is open
2. I click on minimize button
3. App closes, no error message
4. Regardless if "Minimize to tray" option is enabled or not

### Error Log (Desktop only)
 Nothing in the main.log file

### Console Output

Can't be reviewed because app closes :/

### Meta Info
META: SP10.0.2 Electron – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.2 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

**Comment by johannesjo** [comment] 2024-09-09 13:03
Duplicate of #3423

**Closed by johannesjo** 2024-09-09 13:03 UTC
