### ISSUE TITLE
Tasks Bleeding between Projects

### ISSUE THREAD

**Issue by krypterro** [johannesjo/super-productivity#117] opened 2018-09-05 16:06 UTC
## Your Environment
* Version used: debx64
* Operating System and version: Mint Linux 18.
* Desktop Environment: Cinnamon

## Expected Behavior
Task should remain under the Project they were put under

## Current Behavior
When switching between one project level and another, the color will change with the project settings, as will the project name, but the tasks will carry over from whatever project's tasks I was looking at before. I can go to another project, and come back to the one that's displaying the wrong tasks, and sometimes correct the issue.

## Steps to Reproduce (for bugs)
When doing the initial setup of new projects, I can create a project, put task in it, and then create another project, and the previously created tasks for the first project will be there.

**Comment by johannesjo** [comment] 2018-09-05 18:05
Thanks for taking your time to file this issue. Unfortunately I'm unable to reproduce this behavior. Is there any output in the console before a while this issue occurs (Ctrl+Shift+J)? Also: How do your sync settings look like?

**Comment by johannesjo** [comment] 2018-09-05 18:07
Another idea: Maybe you're using an outdated version? If you use the quick access menu in the bottom right (the pink one with the triangle inside) and press on the question mark afterwards: What version is written on top of the modal appearing?

**Comment by krypterro** [comment] 2018-09-05 18:35
Okay, maybe I have a really old version, but I don't see a triangle at all, and I couldn't find the version number anywhere. If you tell me where to click I'll be happy to retrieve that, or alternatively if you can tell me this is for sure an ancient version, I assume I should just install the new one. 
![screenshot from 2018-09-05 13-33-29](https://user-images.githubusercontent.com/41011655/45113586-682a5d00-b110-11e8-9d53-5c947a494814.png)

**Comment by johannesjo** [comment] 2018-09-05 18:47
Yes this looks pretty old. I recommend downloading a newer version (have a look at the readme to see how). The issue should not occur there.

**Comment by johannesjo** [comment] 2018-09-05 22:26
I'm closing this. Please reopen if the issue persists.

**Closed by johannesjo** 2018-09-05 22:26 UTC
