### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Connection is closing.

### ISSUE THREAD

**Issue by dmp1ce** [johannesjo/super-productivity#541] opened 2020-09-28 18:43 UTC
### Steps to Reproduce
superProductivity was running in the background as I was doing a disk intensive backup. The system could have been unresponsive from time to time. I walked away from the computer for an hour or two and then this exception occured. I don't know how to reproduce.

Reloading the application didn't recover. Closing the application and then starting again worked fine to get the application running again.

### Error Log (Desktop only)

I couldn't find any log.log in my `~/snap/superproductivity/current/.config/superProductivity` directory.

### Console Output

None

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
```

### Meta Info
META: SP5.6.5 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1601314518024: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314519005: [Task] Add time spent 
1601314519006: [Tag] Update Work End for Tag 
1601314519012: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314520004: [Task] Add time spent 
1601314520005: [Tag] Update Work End for Tag 
1601314520009: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314521004: [Task] Add time spent 
1601314521005: [Tag] Update Work End for Tag 
1601314521009: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314522005: [Task] Add time spent 
1601314522007: [Tag] Update Work End for Tag 
1601314522022: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314523005: [Task] Add time spent 
1601314523007: [Tag] Update Work End for Tag 
1601314523019: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314524005: [Task] Add time spent 
1601314524006: [Tag] Update Work End for Tag 
1601314524011: [SimpleCounter] Increase SimpleCounter Counter Today 
1601314525005: [Task] Add time spent 
1601314525008: [Tag] Update Work End for Tag 
1601314525023: [SimpleCounter] Increase SimpleCounter Counter Today 
1601317858501: [Task] Add time spent 
1601317858502: [Tag] Update Work End for Tag 
1601317858507: [SimpleCounter] Increase SimpleCounter Counter Today
```

**Comment by johannesjo** [comment] 2020-09-28 19:07
Thanks for reporting. This is likely a duplicate of #398  I assume that this has to do with the database files being accessed (written?) from the outside.

**Comment by dmp1ce** [comment] 2020-09-28 21:03
I'm not sure, but I wasn't writing anything to the database, but the underlying files were being copied. I was doing a ZFS replication, so it wouldn't think it would effect superProductivity at all. When my harddrive is in heavy use, the computer will freeze for several seconds though. It is a problem with my NVMe and motherboard I think.

**Comment by johannesjo** [comment] 2020-09-29 21:43
Thanks for the insight. I am a bit unsure of how to proceed, as I can't reproduce any of these DB issues reliably but I definitely want to fix this. I'll keep you updated.

**Comment by johannesjo** [comment] 2020-10-18 20:38
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix it, but the issue doesn't appear that often and the alternatives are likely to also cause some new problems. I am closing this. Thank you!

**Closed by johannesjo** 2020-10-18 20:38 UTC
Labels: bug, db, external issue

**Comment by johannesjo** [comment] 2020-10-18 20:40
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!
