### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Internal error committing transaction.

### ISSUE THREAD

**Issue by prabhanshu11** [johannesjo/super-productivity#458] opened 2020-07-24 23:38 UTC
### Steps to Reproduce

1. 
2.
3.
4.

### Stacktrace
```
resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21
Ur (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:1716819)
t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
```

### Meta Info
META: SP5.4.2 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.2 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by johannesjo** [comment] 2020-07-25 11:22
Duplicate of #418

**Closed by johannesjo** 2020-07-25 11:22 UTC
