### ISSUE TITLE
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store

### ISSUE THREAD

**Issue by halfpintutopia** [johannesjo/super-productivity#461] opened 2020-07-26 11:07 UTC
### Steps to Reproduce

1. Running the application on Ubuntu 20.04 and it just gave me an error and then closed with this error report. 
2.
3.
4.

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.Error: UnknownError: Internal error opening backing store for indexedDB.open.    at t. (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2570586)    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2568634    at Object.throw (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2568739)    at s (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2567528)    at t.invoke (file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)    at Object.onInvoke (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:476540)    at t.invoke (file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)    at e.run (file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)    at file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325    at t.invokeTask (file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)

### Stacktrace
```
alert (webpack:///src/app/core/persistence/database.service.ts:80:12)
Ur (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2568634)
Ur (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2568739)
Ur (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2567528)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:20)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:20)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:38)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:507:24)
callback (webpack:///node_modules/zone.js/dist/zone.js:1671:17)
```

### Meta Info
META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment] 2020-07-26 21:14
Thank you very much for reporting! Possible known causes for this are:

Not enough memory
Running multiple instances of the app.
Are you able to reproduce this consistently?

Also, this is likely a duplicate of:
#375

**Closed by johannesjo** 2020-07-26 21:14 UTC
Labels: bug, db
