### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by mrdkind** [johannesjo/super-productivity#3281] opened 2024-07-22 08:01 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'then')
    at show (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:186:5567)
    at o.when.show (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:48125)
    at file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:2781
    at Array.forEach (<anonymous>)
    at iM.trigger (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:2723)
    at iM._show (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:40513)
    at iM.show (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:38567)
    at j7.show (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:45752)
    at j7.next (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:45278)
    at e.next (file:///C:/Users/Dr.laptop/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:47765)
```

### Actions Before Error
```
1721635192045: [Task] Toggle start 
1721635192045: [Persistence] Save to DB 
1721635192045: [Task] SetCurrentTask 
1721635192792: [Task] Toggle start 
1721635192793: [Persistence] Save to DB 
1721635192793: [Task] UnsetCurrentTask 
1721635196943: [Task] Update Task 
1721635196944: [Persistence] Save to DB 
1721635199207: [Task] SetSelectedTask 
1721635199208: [Layout] Hide Notes 
1721635202191: [Task] SetSelectedTask 
1721635205993: [Task] Delete Task 
1721635205994: [Persistence] Save to DB (3) 
1721635205994: [Task] UnsetCurrentTask 
1721635214595: [Layout] Show AddTaskBar 
1721635217074: [Task][Issue] Add Task 
1721635217075: [Persistence] Save to DB (2) 
1721635217075: [Task] Move tasks to other project 
1721635217076: [Persistence] Save to DB (2) 
1721635219726: [Layout] Hide AddTaskBar 
1721635225894: [Task] Update Task 
1721635225896: [Persistence] Save to DB 
1721635229033: [Task] Update Task 
1721635229270: [Persistence] Save to DB 
1721635232073: [Task] Delete Task 
1721635232076: [Persistence] Save to DB (3) 
1721635232077: [Task] UnsetCurrentTask 
1721635235875: [Layout] Toggle SideBar 
1721635241547: [Layout] Hide SideBar (2)
```

**Comment by johannesjo** [comment] 2024-07-22 14:27
Duplicate of #3270

**Closed by johannesjo** 2024-07-22 14:27 UTC
