### ISSUE TITLE
Extreme resource use

### ISSUE THREAD

**Issue by meikew** [johannesjo/super-productivity#675] opened 2020-11-18 20:17 UTC
**Your environment:**
Version 6.1.0
Operating system: Ubuntu 20.04

**Current behavior:**

Since this morning (maybe with the latest update), super-productivity seems to be using a lot of system resources, causing my whole system to slow down (when I typed in other programs, the letters showed up with a delay) and super-productivity itself to freeze multiple times, but without throwing any errors. This occurs in particular when I have the pomodoro timer running.

When I run top, I see that super-productivity is using 100% (or more) of a CPU:
![superproductivity_screenshot](https://user-images.githubusercontent.com/14234587/99582003-c8e89c00-29e1-11eb-9ca3-d3b01443479e.png)

Earlier today, also gnome-shell used a lot of resources, so I suspected the issue was about a new way that super-productivity interacts with gnome-shell. After I have disabled usage of the Ubuntu Top bar by all applications, gnome-shell is more well-behaved again, but the problems with the super-productivity resource use persist.

**Steps to reproduce**
- Start program
- Start pomodoro timer on project

Please let me know if I can provide any other information that might help clarify the issue.

Thanks a lot for your awesome work on this project! I have been using super-productivity every day for the last few months and it really helps me a lot to organize my day and keep track of my time.

**Comment by imyhxy** [comment] 2020-11-19 03:30
It makes my system slow sometimes, can I turn off the animation.

**Comment by niubit** [comment] 2020-11-19 09:25
I have the same problem with snap version. The main problem is that the mouse becomes laggy. With AppImagen also although less serious. The deb version seems to work without impacting my UX, although I do see in top that "Load average" goes up when activating a counter.

**Comment by johannesjo** [comment] 2020-11-19 09:41
Thanks for reporting this! Can you maybe check if this only happens with the snap version or also with the AppImage? There seem to be some issues with snapcraft lately unrelated to the app itself.

**Comment by johannesjo** [comment] 2020-11-19 09:49
> Edit: For some reason, after a system reboot, the deb version turns the mouse laggy also.

Hm alright then. We need to narrow this down. 
1. For none of you this happens with 6.0.1?  (would be cool, if you could check again)
2. Does this happen only for the snap version or also the AppImage version?

**Comment by ricardogsilva** [comment] 2020-11-19 12:59
I'm also being affected by this. I've found something, which seems to be related. When monitoring my system with `journalctl -f` I can see a constant flow of messages like this:

```
nov 19 12:53:09 cheetara ubuntu-appindicators@ubuntu.com[2055]: superProductivity1, Impossible to lookup icon for 'superProductivity1_14-panel'
nov 19 12:53:09 cheetara gnome-shell[2055]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                            _createIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:406:26
                                            _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:368:14
                                            _updateIconByType@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:574:18
                                            _updateIcon@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:601:14
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                            _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:220:22
                                            _onPropertiesChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:15
                                            refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:51:19

```

These messages only appear when I am tracking time for some task (i.e. I press the blue `Play` button on superproductivity) - which correlates to when my system is slooow.

As soon as I stop tracking time in superproductivity, the log messages go away, and also my system seems to become responsive again

**Comment by ricardogsilva** [comment] 2020-11-19 13:14
I've reverted to superproductivity version `6.0.1` and I'm not getting those `JS Exception...` logs anymore. My system seems to be running smooth too.

**Comment by johannesjo** [comment] 2020-11-19 13:36
@ricardogsilva thank you! This narrows it down quite a bit. I try to provide a fix asap!

**Comment by meikew** [comment] 2020-11-19 14:18
Thank you all! I get the same error messages as @ricardogsilva when I run journalctl -f. Thanks so much for looking into this @johannesjo !

**Comment by niubit** [comment] 2020-11-19 14:21
I can't make many tests with this, sorry, but using other similar app (gnome-shell-pomodoro) I have observed a similar behavior!
Correlation does not imply causality, but it seems related with changing the app icon in tray, so could be a Gnome or Ubuntu bug. In that application the problems begin when I pause the counter and the app icon begins to flash in tray.
I hope it helps.

**Comment by johannesjo** [comment] 2020-11-19 16:45
Another question: Are all of you using gnome?

**Comment by johannesjo** [comment] 2020-11-19 17:22
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1849142

**Comment by jonasallgeier** [comment] 2020-11-20 16:21
I have the same issue running GNOME Shell 3.36.4/Ubuntu 20.04.

**Comment by squarebracket** [comment] 2020-11-20 18:14
I reverted to try to fix this, but it looks like it wiped out my time tracking data post-update. Is there a way to recover it?

**Comment by johannesjo** [comment] 2020-11-20 18:20
> I reverted to try to fix this, but it looks like it wiped out my time tracking data post-update. Is there a way to recover it?

https://github.com/johannesjo/super-productivity#automatic-backups

**Comment by squarebracket** [comment] 2020-11-20 18:36
Unfortunately, I tried running `snap refresh superproductivity` to re-activate 6.1.0 (to see if the data was still there), and that seems to have copied the 6.0.1 data to 6.1.0, wiping out the data and the backups...

I will keep that in mind for the future, thank you.

**Comment by johannesjo** [comment] 2020-11-20 18:40
Sorry to hear that. Maybe there is a way to restore this data via snap somehow? Snapcraft is saving so much garbage on my harddrive (all the apps previous versions for some reason) I find it had to believe that the data is lost forever.

**Comment by johannesjo** [comment] 2020-11-20 19:37
I still assume that this is an error of gnome-shell-extension-appindicator. As this basically makes working with Super Productivity impossible for some of you I made two adjustments:
1. the updates of the tray icon are now only made with a much lesser frequency
2. If this doesn't help, you should be able to disable the tray icon completely by using the `--disable-tray` flag when starting the app.

I'll provide a patch release shortly.

**Comment by johannesjo** [comment] 2020-11-21 19:02
Can anybody confirm if this update improves the situation (ideally even without using `--disable-tray`)?

**Comment by meikew** [comment] 2020-11-21 21:55
I just tried the new version and everything appears fine again, even without using --disable-tray. Thanks so much!!!

**Comment by Stefanqn** [comment] 2021-01-19 11:36
I still have the issue (haven't tested `--disable-tray`). 
I'm running manjaro with KDE without `gnome-shell-extension-appindicator`. 
AUR `superproductivity-bin 6.3.3-1` has high load, `superproductivity 6.0.1-1` doesn't.

**Comment by johannesjo** [comment] 2021-01-19 11:41
Thanks for reporting this @Stefanqn .

Not sure what the best road to take is at the moment. Maybe I should just disable the tray indicator feature for linux until this is fixed on an OS level? Any opinions?

**Comment by Stefanqn** [comment] 2021-01-19 11:46
add it as a setting and mention that enabling it can cause high CPU load in Linux?

**Comment by ricardogsilva** [comment] 2021-01-19 11:49
> add it as a setting and mention that enabling it can cause high CPU load in Linux?

:+1:  - This seems nice, if it is not too much  work.

Otherwise, personally I don't care too much for that feature.

**Comment by johannesjo** [comment] 2021-01-22 10:59
Thanks for your input! Makes sense to me.

@Stefanqn could you maybe post some output if `journalctl -f`. Also what is your Ubuntu version?

**Comment by Stefanqn** [comment] 2021-02-09 14:00
@johannesjo sorry for my late response. For some reason, which I can not reproduce, the resource usage is for the last 2 weeks back to normal with the current version.

**Comment by johannesjo** [comment] 2021-02-10 21:16
@Stefanqn thanks for getting back to us! Let's hope it stays this way :)

**Comment by tset0401** [comment] 2021-02-25 09:16
I have the same problem on Windows, it runs smoothly at first but after running for a while, it started consuming too much CPU and tended to create more processes like these:
![image](https://user-images.githubusercontent.com/18468247/109128475-1e230f00-7782-11eb-9002-2d4db9551650.png)

I checked for running commands, they are all like the followings with different `--field-trial-handle` and `--mojo-platform-channel-handle`: 
`"C:\Program Files\WindowsApps\53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6\app\superProductivity.exe" --type=renderer --field-trial-handle=1520,9757910550222207410,1503108221746588020,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --app-path="C:\Program Files\WindowsApps\53707johannesjo.SuperProductivity_6.4.0.0_x64__ch45amy23cdv6\app\resources\app.asar" --node-integration --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --enable-spellcheck --enable-websql --disable-electron-site-instance-overrides --device-scale-factor=1.5 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2336 /prefetch:1`


Can you help me solve this problem? I've been using it for a week and it's great tool for tracking my time but I found this problem because it made my laptop much hotter. Although I can open Task Manager and kill them all but it's quite painful

**Status**
App Version: 6.4.0.0
Operating system: Windows 10 Pro Version 10.0.18363 Build 18363

**Comment by tset0401** [comment] 2021-02-26 09:04
@johannesjo I figured it out, whenever I click on a notification banner, it creates a new process like I said above, is that a feature or a bug? 🤔

**Comment by johannesjo** [comment] 2021-02-26 20:06
@tset0401 Thank you very much for digging into this. What kind of banner are we talking about? I think we should address this in a new issue, as it looks like another problem to me. I am closing this one as it doesn't seem to be a problem any more.

**Closed by johannesjo** 2021-02-26 20:06 UTC
Labels: bug, external issue
