### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by geek-andi** [johannesjo/super-productivity#1310] opened 2021-06-21 09:31 UTC
### Steps to Reproduce
1. Stop time tracking for a task 
2. IndexedDB INIT Error (Press ok)
3. This error showed for the first time, dev tools opened and a big red error message, see screenshot in comment
4. Reload application failed
5. Closing and reopening application seems to be working
6. Tasks from today are missing

```
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2337524) at Generator.throw () at a (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736) at l.invoke (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:1642047) at l.invoke (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:1641863)
! Please copy & report !

Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2337524) at Generator.throw () at a (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736) at l.invoke (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:1642047) at l.invoke (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///snap/superproductivity/1255/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:1641863)
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
META: SP7.0.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.3 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36
```

### Error Log (Desktop only)

Can't find log in  ~/.config/superProductivity/logs/main.log on ubuntu 20.04

### Stacktrace
```
zone-evergreen.js:2561 11:25:20.295 › Frontend Error Stack: await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1120:16)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:1498487)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
s.<computed> @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
invoke @ zone-evergreen.js:476
n.args.<computed> @ zone-evergreen.js:2541
zone-evergreen.js:2561 11:25:20.297 › Frontend Error Stack: await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
s.<computed> @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
invoke @ zone-evergreen.js:476
n.args.<computed> @ zone-evergreen.js:2541
zone-evergreen.js:2561 11:26:38.920 › Error while backing up
zone-evergreen.js:2561 11:26:38.923 › Error: EACCES: permission denied, open '/home/andi/snap/superproductivity/1255/.config/superProductivity/backups/2021-06-21.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at IpcMainImpl.backupData (/snap/superproductivity/1255/resources/app.asar/electron/backup.js:52:14)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)
s.<computed> @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
invoke @ zone-evergreen.js:476
n.args.<computed> @ zone-evergreen.js:2541
zone-evergreen.js:2561 11:28:38.919 › Error while backing up
zone-evergreen.js:2561 11:28:38.921 › Error: EACCES: permission denied, open '/home/andi/snap/superproductivity/1255/.config/superProductivity/backups/2021-06-21.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at IpcMainImpl.backupData (/snap/superproductivity/1255/resources/app.asar/electron/backup.js:52:14)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)
s.<computed> @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
invoke @ zone-evergreen.js:476
n.args.<computed> @ zone-evergreen.js:2541
zone-evergreen.js:2561 11:30:38.923 › Error while backing up
zone-evergreen.js:2561 11:30:38.924 › Error: EACCES: permission denied, open '/home/andi/snap/superproductivity/1255/.config/superProductivity/backups/2021-06-21.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at IpcMainImpl.backupData (/snap/superproductivity/1255/resources/app.asar/electron/backup.js:52:14)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)
```

### Meta Info
META: SP7.0.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.3 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

### Actions Before Error

**Comment by geek-andi** [comment] 2021-06-21 09:32
![Screenshot from 2021-06-21 11-28-59](https://user-images.githubusercontent.com/11439966/122740535-5cd65b00-d284-11eb-9579-120ebc666208.png)

**Comment by geek-andi** [comment] 2021-06-21 09:37
I just realized that I did an ubuntu update in the meantime.

**Comment by johannesjo** [comment] 2021-06-21 09:51
Thanks for opening this up!

Looks like a duplicate of #398 so I am closing this

**Closed by johannesjo** 2021-06-21 09:51 UTC
