### ISSUE TITLE
error "DOMException"

### ISSUE THREAD

**Issue by Al1J** [johannesjo/super-productivity#368] opened 2020-05-13 19:26 UTC
### Your Environment

* Version used:  deb
* Operating System and version:
* Desktop Environment:  Ubuntu 18.04.4 64 bits
* Browser Name and version:  Firefox 76.0 64 bits

### Expected Behavior
 I just clicked the button "break" to assign my idle time to break, as the application was asking if it was break, task or break+task. And the error occurred immediately
![Capture d’écran de 2020-05-13 21-23-37](https://user-images.githubusercontent.com/64494099/81855804-1c27f080-9560-11ea-8ac0-4d97e8f28e21.png)
.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Console Output

DOMException: UnknownError: Internal error committing transaction.
! Please copy & report !

DOMException: UnknownError: Internal error committing transaction.
META: SP5.1.1 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.1.1 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36

**Comment by johannesjo** [comment] 2020-05-13 19:29
This is probably a duplicate of #236. Probably time to finally fix this. I'll have a look as soon as I can.

**Comment by johannesjo** [comment] 2020-05-15 13:43
There is a possible fix out now. Please follow the discussion on #236.

**Closed by johannesjo** 2020-05-15 13:43 UTC
Labels: bug
