### ISSUE TITLE
Repeated task instances do not have the subtasks of the original repeated task

### ISSUE THREAD

**Issue by ghost** [johannesjo/super-productivity#3683] opened 2024-11-15 10:47 UTC
When I create a task, add subtasks to it, and then I make it a repeated task. The repeated task instances don't have the subtasks of the original tasks.

### Your Environment

- Version used:
 Super Productivity 10.1.1 (apk)
- Operating System and version: 
Android 14 (OneUI 6.1)

### Expected Behavior

The instances of the repeated tasks also have the subtasks of the original repeated task.

### Current Behavior

The repeated task instances do not have the subtasks of the original repeated task.

### Steps to Reproduce (for bugs)

1. Create a new task.
2. Add subtasks to it.
3. Make the task a repeated task.

### Can you reproduce this reliably?

Yes, I can.

**Comment by johannesjo** [comment] 2024-11-15 11:27
Duplicate of #427

**Closed as completed by johannesjo** 2024-11-15 11:27 UTC
Labels: bug
