### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by staltz** [johannesjo/super-productivity#1259] opened 2021-06-01 13:56 UTC
### Steps to Reproduce

1. I wasn't actually using the app, it was just running in the background and then suddenly...

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:2684500)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
```

### Meta Info
META: SP6.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1622555745721: [Task] Add time spent 
1622555745724: [Project] Update Work End 
1622555745727: [Tag] Update Work End for Tag 
1622555745750: [Persistence] Save to DB 
1622555745752: [Persistence] Save to DB 
1622555745754: [Persistence] Save to DB 
1622555745871: [Task] Add time spent 
1622555745872: [Project] Update Work End 
1622555745874: [Tag] Update Work End for Tag 
1622555745882: [Persistence] Save to DB 
1622555745883: [Persistence] Save to DB 
1622555745883: [Persistence] Save to DB 
1622555746871: [Task] Add time spent 
1622555746872: [Project] Update Work End 
1622555746872: [Tag] Update Work End for Tag 
1622555746878: [Persistence] Save to DB 
1622555746878: [Persistence] Save to DB 
1622555746878: [Persistence] Save to DB 
1622555749104: [Task] Add time spent 
1622555749111: [Project] Update Work End 
1622555749111: [Tag] Update Work End for Tag 
1622555749116: [Persistence] Save to DB 
1622555749116: [Persistence] Save to DB 
1622555749116: [Persistence] Save to DB 
1622555752877: [Task] Add time spent 
1622555752879: [Project] Update Work End 
1622555752881: [Tag] Update Work End for Tag 
1622555752889: [Persistence] Save to DB 
1622555752890: [Persistence] Save to DB 
1622555752891: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-01 13:59
Thank you very much for reporting this. Looks like a duplicate of #816 to me.

**Closed by johannesjo** 2021-06-01 14:00 UTC
