### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by ximemira** [johannesjo/super-productivity#1744] opened 2021-12-07 19:07 UTC
### Steps to Reproduce
*1. Idk. The error-window just popped while i was on a Pomodoro working sessions. I was doing a task with no time estimate. This error didn't happen before the last update.* 

### Error Log (Desktop only)
*I couldn't find any*

### Console Output
*Copy of the last lines :* 
[Idle] Set idle time {idleTime: 1190608, type: '[Idle] Set idle time'}
action-logger.reducer.ts:11 [Task] Add time spent {task: {…}, date: '2021-12-07', duration: 1000, type: '[Task] Add time spent'}
action-logger.reducer.ts:11 [Project] Update Work End {id: 'DEFAULT', date: '2021-12-07', newVal: 1638903665704, type: '[Project] Update Work End'}
action-logger.reducer.ts:11 [Tag] Update Work End for Tag {id: 'TODAY', date: '2021-12-07', newVal: 1638903665704, type: '[Tag] Update Work End for Tag'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'project', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'tag', data: {…}, type: '[Persistence] Save to DB'}
sync-trigger.service.ts:163 __trigger_sync__ task
sync-trigger.service.ts:163 __trigger_sync__ tag
action-logger.reducer.ts:11 [Idle] Set idle time {idleTime: 1191608, type: '[Idle] Set idle time'}
action-logger.reducer.ts:11 [Task] Add time spent {task: {…}, date: '2021-12-07', duration: 1000, type: '[Task] Add time spent'}
action-logger.reducer.ts:11 [Project] Update Work End {id: 'DEFAULT', date: '2021-12-07', newVal: 1638903666705, type: '[Project] Update Work End'}
action-logger.reducer.ts:11 [Tag] Update Work End for Tag {id: 'TODAY', date: '2021-12-07', newVal: 1638903666705, type: '[Tag] Update Work End for Tag'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'task', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'project', data: {…}, type: '[Persistence] Save to DB'}
action-logger.reducer.ts:11 [Persistence] Save to DB {dbKey: 'tag', data: {…}, type: '[Persistence] Save to DB'}

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:2107790)
    at b.__tryOrUnsub (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956876)
    at b.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956105)
    at T._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955288)
    at T.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955062)
    at v._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:975388)
    at v.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955062)
    at O.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:952809)
    at b._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:1716081)
    at b.__tryOrUnsub (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638902270613: [Task] Add time spent 
1638902270623: [Project] Update Work End 
1638902270643: [Tag] Update Work End for Tag 
1638902270648: [Persistence] Save to DB (3) 
1638902319202: [Task] Add time spent 
1638902319206: [Project] Update Work End 
1638902319215: [Tag] Update Work End for Tag 
1638902319221: [Persistence] Save to DB (3) 
1638902379837: [Task] Add time spent 
1638902379848: [Project] Update Work End 
1638902379856: [Tag] Update Work End for Tag 
1638902379866: [Persistence] Save to DB (3) 
1638902456725: [Pomodoro] Finish Pomodoro Session 
1638902456737: [Task] UnsetCurrentTask 
1638902779706: [Idle] Trigger Idle 
1638902783810: [Idle] Set idle time (3) 
1638902784695: [Idle] Trigger Idle 
1638902787654: [Idle] Set idle time (2) 
1638902794716: [Idle] Trigger Idle (2) 
1638902799497: [Pomodoro] Finish Pomodoro Session 
1638902799501: [Task] Toggle start 
1638902799503: [Persistence] Save to DB 
1638902799503: [Task] SetCurrentTask 
1638902799505: [Pomodoro] Start Pomodoro 
1638902799536: [Idle] Set idle time 
1638902799666: [Task] Add time spent 
1638902799670: [Project] Update Work End 
1638902799682: [Tag] Update Work End for Tag 
1638902799688: [Persistence] Save to DB (3) 
1638902799705: [Idle] Trigger Idle
```

**Comment by johannesjo** [comment] 2021-12-09 09:55
Thank you for opening this up! Looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-09 09:55 UTC
