### ISSUE TITLE
Play song when pomodoro timer is running

### ISSUE THREAD

**Issue by bluedevil947** [johannesjo/super-productivity#1450] opened 2021-08-13 14:01 UTC
Hey guys, is there a way to play a song when Pomodoro timer is ticking? I have a 30 minute song to always runs when I work, it would be awesome to synchronize it with this app and pomodoro timer.

**Comment by johannesjo** [comment] 2021-08-13 20:48
Duplicate of #462

**Closed by johannesjo** 2021-08-13 20:48 UTC
Labels: enhancement
