### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Connection is closing.

### ISSUE THREAD

**Issue by gibbsoft** [johannesjo/super-productivity#818] opened 2021-01-20 17:23 UTC
### Steps to Reproduce

Unknown, had the app open all day, then next time I came to use it this happened.

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:488:37)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1624:20)
```

### Meta Info
META: SP6.1.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.1 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1611135513082: [Task] Update Task Tags 
1611135513084: [WorkContextMeta] Auto Move Task from backlog to today 
1611135513085: [Persistence] Save to DB 
1611135513086: [Persistence] Save to DB 
1611135513087: [Persistence] Save to DB 
1611135735479: [Layout] Show AddTaskBar 
1611135769157: [Task][Issue] Add Task 
1611135769171: [Persistence] Save to DB 
1611135769172: [Persistence] Save to DB 
1611135772440: [Layout] Hide AddTaskBar 
1611158485632: [Task] Update Task 
1611158485681: [Persistence] Save to DB 
1611158490624: [Task] Update Task Tags 
1611158490626: [Persistence] Save to DB 
1611158490626: [Persistence] Save to DB 
1611163380153: [Project] Add Project 
1611163380157: [Persistence] Save to DB 
1611163381303: [WorkContext] Set Active Work Context 
1611163381328: [Task] SetSelectedTask 
1611163381400: [Note] Load Note State 
1611163381406: [Bookmark] Load Bookmark State 
1611163381419: [Metric] Load Metric State 
1611163381432: [Improvement] Load Improvement State 
1611163381437: [Obstruction] Load Obstruction State 
1611163381437: [Project] Load Project related Data Success 
1611163381438: [Improvement] Clear Hidden Improvements 
1611163381438: [Improvement] Delete multiple Improvements 
1611163404556: [Task][Issue] Add Task 
1611163404567: [Persistence] Save to DB 
1611163404568: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-01-22 11:42
Thanks for reporting. This looks like a duplicate of #816 to me.

**Closed by johannesjo** 2021-01-22 11:42 UTC
