### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError

### ISSUE THREAD

**Issue by sbhttchryy** [johannesjo/super-productivity#1460] opened 2021-08-17 13:11 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at sm.<anonymous> (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:1662222)
    at Generator.throw (<anonymous>)
    at a (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:1661451)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at Z (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15036
    at a (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:1939680)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
```

### Meta Info
META: SP7.5.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1629203936427: [Task] Add time spent 
1629203936428: [Tag] Update Work End for Tag 
1629203936432: [Persistence] Save to DB 
1629203936432: [Persistence] Save to DB 
1629203937427: [Task] Add time spent 
1629203937427: [Tag] Update Work End for Tag 
1629203937431: [Persistence] Save to DB 
1629203937431: [Persistence] Save to DB 
1629203938427: [Task] Add time spent 
1629203938428: [Tag] Update Work End for Tag 
1629203938432: [Persistence] Save to DB 
1629203938432: [Persistence] Save to DB 
1629203939427: [Task] Add time spent 
1629203939431: [Tag] Update Work End for Tag 
1629203939443: [Persistence] Save to DB 
1629203939443: [Persistence] Save to DB 
1629203940427: [Task] Add time spent 
1629203940431: [Tag] Update Work End for Tag 
1629203940443: [Persistence] Save to DB 
1629203940444: [Persistence] Save to DB 
1629203941427: [Task] Add time spent 
1629203941430: [Tag] Update Work End for Tag 
1629203941440: [Persistence] Save to DB 
1629203941440: [Persistence] Save to DB 
1629203942427: [Task] Add time spent 
1629203942430: [Tag] Update Work End for Tag 
1629203942440: [Persistence] Save to DB 
1629203942440: [Persistence] Save to DB 
1629205871478: [Pomodoro] Finish Pomodoro Session 
1629205871484: [Task] UnsetCurrentTask
```

**Comment by johannesjo** [comment] 2021-08-19 08:01
Thanks for reporting!

Looks like a duplicate of #398

**Closed by johannesjo** 2021-08-19 08:01 UTC
