### ISSUE TITLE
Cannot clear the task description

### ISSUE THREAD

**Issue by Looooong** [johannesjo/super-productivity#1491] opened 2021-09-03 18:15 UTC
### Your Environment

- Version used: 7.5.2
- Operating System and version: Windows 10
- Desktop Environment: 
- Browser Name and version: 

### Expected Behavior

When the task description is cleared, losing the task description textarea focus should persist the empty content to the database.

### Current Behavior

The empty task description is not persisted.

### Steps to Reproduce (for bugs)

1. Given a task with a written task description
2. Focus the task description textarea, clear all the content.
3. Lost task description textarea focus.
4. Close the task additional infos panel.
5. Re-open the task additional infos panel.
6. The task description is not cleared.

### Console Output

There is no `[Task] Update Task` or `[Persistence] Save to DB` in the console log after clearing task description.

**Comment by johannesjo** [comment] 2021-09-03 19:48
Hi there! That's a feature not a bug ;) The task description you see there is the default task description. If you don't like to see it, you can just delete all the content from Setings/Global Settings/Misc Settings/Task description template.

**Comment by Looooong** [comment] 2021-09-04 00:53
Well, I have my task description edited to something else other than the default template. However, when I don't need the description I have written, I couldn't delete it. Should it revert to the default template?

**Comment by johannesjo** [comment] 2021-09-04 09:54
Oh you're right! Good catch! Thank you.

**Comment by johannesjo** [comment] 2021-09-04 09:54
Should be fixed with the next release.

**Closed by johannesjo** 2021-09-04 09:54 UTC
Labels: bug
