### ISSUE TITLE
Error: Uncaught (in promise): Error: DataError: Failed to write blobs (IOError)Error: DataError: Failed to write blobs (IOError)

### ISSUE THREAD

**Issue by s-maibuecher** [johannesjo/super-productivity#1280] opened 2021-06-07 10:04 UTC
Hi there, first of all, thank you very much. I like to use Super Productivity for my work. It helps me a lot. Got an issue today. Here is the report:

### Steps to Reproduce

1. Started program, alert: sync failed. But worked.
2. After 40 minutes crash.
3. Finally there was a popup 'idb terminated', then program terminated.
4. What I find suspicious is that there are references to the 1237 directory in the log? Or do I misunderstand the directory structure?

```
s.m@LAP-PU75:~/snap/superproductivity|⇒  la                   
total 12K
drwxr-xr-x 13 s.m domain users 4.0K Jun  2 08:29 1237
lrwxrwxrwx  1 s.m domain users    4 Jun  7 09:34 current -> 1241
drwxr-xr-x 13 s.m domain users 4.0K Jun  7 09:34 1241
drwxr-xr-x  3 s.m domain users 4.0K Jan 15 09:27 common
```

### Error Log (Desktop only)
```
[2021-06-04 09:56:42.135] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: No token' } undefined
[2021-06-04 09:56:42.151] [error] Frontend Error Stack: 
[2021-06-04 09:56:49.248] [info]  close, isQuiting: undefined
[2021-06-04 09:56:49.252] [info]  close, isQuiting: true
[2021-06-04 09:56:49.264] [info]  Quit after all windows being closed
[2021-06-04 09:56:52.354] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-06-04 09:56:52.498] [info]  Saving backups to /home/s.m@p.local/snap/superproductivity/1237/.config/superProductivity/backups
[2021-06-04 09:56:53.159] [info]  No custom styles detected at /home/s.m@p.local/snap/superproductivity/1237/.config/superProductivity/styles.css
[2021-06-05 22:47:06.505] [warn]  getSettingsCb no callbacks left
[2021-06-06 23:22:52.372] [info]  close, isQuiting: true
[2021-06-07 08:29:37.309] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-06-07 08:29:37.458] [info]  Saving backups to /home/s.m@p.local/snap/superproductivity/1237/.config/superProductivity/backups
[2021-06-07 08:29:38.140] [info]  No custom styles detected at /home/s.m@p.local/snap/superproductivity/1237/.config/superProductivity/styles.css
[2021-06-07 09:34:21.351] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }

```

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1237/resources/app.asar/dist/main.cc3925b96cf833956e9a.js:1:2326827)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1120:16)
Ur (file:///snap/superproductivity/1237/resources/app.asar/dist/main.cc3925b96cf833956e9a.js:1:1488578)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
```

### Meta Info
META: SP7.0.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.0 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

### Actions Before Error
```
1623051172050: [Task] Add time spent 
1623051172054: [Project] Update Work End 
1623051172059: [Tag] Update Work End for Tag 
1623051172064: [Persistence] Save to DB 
1623051172065: [Persistence] Save to DB 
1623051172065: [Persistence] Save to DB 
1623051173051: [Task] Add time spent 
1623051173055: [Project] Update Work End 
1623051173061: [Tag] Update Work End for Tag 
1623051173067: [Persistence] Save to DB 
1623051173068: [Persistence] Save to DB 
1623051173069: [Persistence] Save to DB 
1623051174050: [Task] Add time spent 
1623051174054: [Project] Update Work End 
1623051174062: [Tag] Update Work End for Tag 
1623051174069: [Persistence] Save to DB 
1623051174070: [Persistence] Save to DB 
1623051174070: [Persistence] Save to DB 
1623051175051: [Task] Add time spent 
1623051175055: [Project] Update Work End 
1623051175061: [Tag] Update Work End for Tag 
1623051175067: [Persistence] Save to DB 
1623051175067: [Persistence] Save to DB 
1623051175068: [Persistence] Save to DB 
1623051176050: [Task] Add time spent 
1623051176052: [Project] Update Work End 
1623051176058: [Tag] Update Work End for Tag 
1623051176063: [Persistence] Save to DB 
1623051176063: [Persistence] Save to DB 
1623051176064: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-07 10:56
Hi there! Thanks for reporting this! This might be a chromium bug. My hope is, that it will be fixed there, as I don't really now neither how to reproduce it, nor how to fix it. :(

Seems like you're not the only one: #1220

**Comment by johannesjo** [comment] 2021-06-07 10:57
I am closing this as a duplicate of #1220.

**Closed by johannesjo** 2021-06-07 10:57 UTC
Labels: bug, external issue, help wanted
