### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Connection is closing.

### ISSUE THREAD

**Issue by palviggi-flagbit** [johannesjo/super-productivity#687] opened 2020-11-23 10:36 UTC
### Steps to Reproduce
I have no steps, I just opened the app, started on a task and got it after ~20 minutes

### Error Log (Desktop only)
It's the ubuntu 20.04 snap version, but there's no log in the folder

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:488:37)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1624:20)
```

### Meta Info
META: SP6.1.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.0 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1606126779747: [Persistence] Save to DB 
1606126779748: [Persistence] Save to DB 
1606126780727: [Task] Add time spent 
1606126780730: [Tag] Update Work End for Tag 
1606126780741: [Persistence] Save to DB 
1606126780742: [Persistence] Save to DB 
1606126781727: [Task] Add time spent 
1606126781730: [Tag] Update Work End for Tag 
1606126781743: [Persistence] Save to DB 
1606126781744: [Persistence] Save to DB 
1606126782727: [Task] Add time spent 
1606126782730: [Tag] Update Work End for Tag 
1606126782744: [Persistence] Save to DB 
1606126782745: [Persistence] Save to DB 
1606126783727: [Task] Add time spent 
1606126783730: [Tag] Update Work End for Tag 
1606126783745: [Persistence] Save to DB 
1606126783747: [Persistence] Save to DB 
1606126784727: [Task] Add time spent 
1606126784730: [Tag] Update Work End for Tag 
1606126784743: [Persistence] Save to DB 
1606126784744: [Persistence] Save to DB 
1606126785728: [Task] Add time spent 
1606126785731: [Tag] Update Work End for Tag 
1606126785743: [Persistence] Save to DB 
1606126785744: [Persistence] Save to DB 
1606126793279: [Task] Add time spent 
1606126793282: [Tag] Update Work End for Tag 
1606126793301: [Persistence] Save to DB 
1606126793304: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2020-11-23 20:23
Thank you very much for taking the time to open this up. May I ask if this just happened once or if you can somehow reproduce this consistently?

**Comment by palviggi-flagbit** [comment] 2020-11-24 10:46
This one in particular only happened once in the 2 months I've been using the app. Before the crash it also showed some alerts and opened the devtools.

I had crashes before, but then it would only close without message.

**Comment by johannesjo** [comment] 2020-11-24 21:49
Thanks. There is probably not much we can do for now. There is an [open issue for IDBWrapper for this](https://github.com/jensarps/IDBWrapper/issues/80) but I doubt that this will be fixed anytime soon if this is even possible (this might be a chromium issue).

**Comment by johannesjo** [comment] 2021-01-22 11:40
I'd assume that this is fixed now. Please let me know if it occurs again and thanks for your help once more!

**Closed by johannesjo** 2021-01-22 11:40 UTC
Labels: bug, external issue

**Comment by palviggi-flagbit** [comment] 2021-01-22 11:46
@johannesjo 2 days ago i had a similar error (the one on #816 i think)
It was after 20 minutes of usage, and before that the program was open for 3 days, so it doesn't seem to be related to usage.

However, after the restart I started getting a new message about taking a rest every 1 hour.
I suspect at this point that the snap auto-update feature broke the IDB connection while I was using the app.
Maybe you should check if all related IDB problems occur in the same week and are all from the snap version

**Comment by johannesjo** [comment] 2021-01-22 11:48
> Maybe you should check if all related IDB problems occur in the same week and are all from the snap version

This might be a good idea. Thanks for the info. My strongest suspicion is that this might be caused by the disk being full. Is that a possibility in your case?

**Comment by palviggi-flagbit** [comment] 2021-01-22 12:01
> > Maybe you should check if all related IDB problems occur in the same week and are all from the snap version
> 
> This might be a good idea. Thanks for the info. My strongest suspicion is that this might be caused by the disk being full. Is that a possibility in your case?

mmm, I don't think so directly. my main disk has 500GB free.
but I can see from `df` that snap uses a mount per app (all of the apps mounts are at 100% usage, so it's probably auto-expanding)
In the case of superproductivity I see 2 mount of 70mb each. Going with the auto-update theory, snap probably downloads the new app version and reassigns the mount to the new. In that moment the file connection from chromium breaks.

Running `snap info superproductivity` I can see that the last update was 2 days ago, at around the time I got the crash. 
That looks like it's the problem.

**Comment by johannesjo** [comment] 2021-01-22 12:09
> Running `snap info superproductivity` I can see that the last update was 2 days ago, at around the time I got the crash.
> That looks like it's the problem.

Yes, this makes a lot of sense. That would also explain, why adding some retries to the whole thing seem to have fixed this to some extend. Puh, if this is really the case, this is possibly very nasty to fix :/
