### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is undefined.

### ISSUE THREAD

**Issue by morningglory17** [johannesjo/super-productivity#1725] opened 2021-12-02 00:44 UTC
### Steps to Reproduce

I left my computer for about 15 mins with the program open and no active task. I came back, there was the usual popup for a scheduled task, I clicked start, then this error occurred. The program currently is showing a screen with one half being the normal program, albeit compressed to fit in half the screen and with a pop-up saying an error occurred, and the other half being code in a console. It also appears that the task I started is active despite the error.

### Error Log (Desktop only)

I don't seem to have a folder called superProductivity in my Roaming folder. There isn't one anywhere else on my computer either.

### Console Output

No output from the console, but the error pop-up had some type of information about the error:

task (webpack:///src/app/features/idle/idle.service.ts:137:22)__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is undefined.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638402034829: [Project] Update Work End 
1638402034836: [Tag] Update Work End for Tag 
1638402034845: [Persistence] Save to DB (3) 
1638402035670: [Task] Add time spent 
1638402035672: [Project] Update Work End 
1638402035679: [Tag] Update Work End for Tag 
1638402035687: [Persistence] Save to DB (3) 
1638402035918: [Task] UnsetCurrentTask 
1638403562980: [Idle] Trigger Idle 
1638403566408: [Idle] Set idle time (3) 
1638403567978: [Idle] Trigger Idle 
1638403569408: [Idle] Set idle time (2) 
1638403572981: [Idle] Trigger Idle 
1638403576423: [Idle] Set idle time 
1638403633091: [Idle] Trigger Idle (12) 
1638403636409: [Idle] Set idle time 
1638403693190: [Idle] Trigger Idle (12) 
1638403696409: [Idle] Set idle time 
1638403753264: [Idle] Trigger Idle (12) 
1638403756410: [Idle] Set idle time 
1638403813330: [Idle] Trigger Idle (12) 
1638403816409: [Idle] Set idle time 
1638403873416: [Idle] Trigger Idle (12) 
1638403879410: [Idle] Set idle time (4) 
1638403880291: [Project] Auto Move Task from backlog to today 
1638403880292: [Persistence] Save to DB 
1638403880292: [Task] SetCurrentTask 
1638403880294: [Task] Update Task 
1638403880296: [Persistence] Save to DB (2) 
1638403880458: [Idle] Set idle time
```

**Comment by johannesjo** [comment] 2021-12-02 09:10
Hey there! Thank you very much for reporting this. This looks like a duplicate of #1684 to me. Unfortunately I am unable to reproduce this myself. Would you maybe be willing to help me with debugging this?

**Closed** 2021-12-02 19:38 UTC
Labels: bug
