### ISSUE TITLE
Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.

### ISSUE THREAD

**Issue by devyzr** [johannesjo/super-productivity#478] opened 2020-08-05 18:32 UTC
### Steps to Reproduce

1. Be working on a react project while tracking work
2. Wait
3. PC will eventually get super slow
4. Crash

### Error Log (Desktop only)
[2020-08-04 16:31:33.550] [error] Frontend Error: RangeError: Invalid array length
    at t.setDots (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3385688)
    at t.setRotationFromValue (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386402)
    at t.onInputChange (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386250)
    at file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3387513
    at _a (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:428966)
    at i (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:429128)
    at e.o [as _next] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:465641)
    at e.__tryOrUnsub (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:575772)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:574917)
    at e._next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573993) RangeError: Invalid array length
    at t.setDots (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3385688)
    at t.setRotationFromValue (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386402)
    at t.onInputChange (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386250)
    at file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3387513
    at _a (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:428966)
    at i (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:429128)
    at e.o [as _next] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:465641)
    at e.__tryOrUnsub (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:575772)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:574917)
    at e._next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573993)
[2020-08-04 16:31:33.714] [error] Frontend Error: RangeError: Invalid array length
    at t.setDots (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3385688)
    at t.setRotationFromValue (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386402)
    at t.set [as model] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3383441)
    at Fi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:405904)
    at hi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:401284)
    at Object.ra (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:426020)
    at template (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3400952)
    at ii (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:398714)
    at ni (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:397357)
    at Si (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:404552) RangeError: Invalid array length
    at t.setDots (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3385688)
    at t.setRotationFromValue (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3386402)
    at t.set [as model] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3383441)
    at Fi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:405904)
    at hi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:401284)
    at Object.ra (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:426020)
    at template (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:3400952)
    at ii (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:398714)
    at ni (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:397357)
    at Si (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:404552)
[2020-08-04 16:31:33.955] [error] Frontend Error: Error: RangeError: Invalid array length
    at t.handleError (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:4108338)
    at Yi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:405758)
    at _a (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:428987)
    at i (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:429128)
    at e.o [as _next] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:465641)
    at e.__tryOrUnsub (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:575772)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:574917)
    at e._next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573993)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573664)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:716991) Error: RangeError: Invalid array length
    at t.handleError (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:4108338)
    at Yi (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:405758)
    at _a (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:428987)
    at i (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:429128)
    at e.o [as _next] (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:465641)
    at e.__tryOrUnsub (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:575772)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:574917)
    at e._next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573993)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:573664)
    at e.next (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:716991)
[2020-08-04 16:31:37.753] [error] Frontend Error Stack: setDots (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:169:16)
setRotationFromValue (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:232:9)
onInputChange (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:223:9)
onInputChange (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.html:16:28)
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14935:15)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/core/fesm5/core.js:25527:16)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:15)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:21)
_next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:25)
[2020-08-04 16:31:37.763] [error] Frontend Error Stack: setDots (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:169:16)
setRotationFromValue (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:232:9)
Input (webpack:///src/app/ui/duration/input-duration-slider/input-duration-slider.component.ts:54:11)
assertDataInRange (webpack:///node_modules/@angular/core/fesm5/core.js:9088:36)
getNativeByTNode (webpack:///node_modules/@angular/core/fesm5/core.js:8136:8)
bindingUpdated (webpack:///node_modules/@angular/core/fesm5/core.js:14427:8)
template (webpack:///src/app/features/tasks/dialog-time-estimate/dialog-time-estimate.component.html:17:31)
setSelectedIndex (webpack:///node_modules/@angular/core/fesm5/core.js:7747:8)
setBindingIndex (webpack:///node_modules/@angular/core/fesm5/core.js:7616:12)
viewAttachedToChangeDetector (webpack:///node_modules/@angular/core/fesm5/core.js:8762:12)
[2020-08-04 16:31:40.399] [error] Frontend Error Stack: isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/core/fesm5/core.js:25527:16)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:15)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:21)
_next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
observers.slice (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:47:24)
[2020-08-05 13:25:32.764] [error] Frontend Error: Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at S (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:15562)
    at file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:14646
    at s (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:1793636)
    at t.invoke (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:476594)
    at t.invoke (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)
    at e.run (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)
    at file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
    at t.invokeTask (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:476477) Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at S (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:15562)
    at file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:14646
    at s (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:1793636)
    at t.invoke (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:476594)
    at t.invoke (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)
    at e.run (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)
    at file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
    at t.invokeTask (file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:476477)
[2020-08-05 13:25:37.102] [error] Frontend Error Stack: scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:1793636)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js:1:1793636)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
```

### Meta Info
META: SP5.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.2 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment] 2020-08-05 21:20
Thanks for opening this up. Are you sure that this is caused by super productivity? İ personally never encountered a memory problems with the app while I often encountered memory leaks work node based build tools such as angular cli and different react build tools. İt would help a lot of you could keep open a process monitor to check where memory or CPU usage spikes out of control and under which circumstances.

**Comment by johannesjo** [comment] 2020-08-06 20:37
Ah now I get it. I think I read the error log wrong. This is most likely a duplicate of #401. Please let me know if you think it isn't.

**Closed** 2020-08-06 20:37 UTC

**Comment by devyzr** [comment] 2020-09-05 15:34
Most likely was running out of ram due to visual studio code. Haven't had any issues since changing to sublime text.
