### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AstroTemisas** [johannesjo/super-productivity#385] opened 2020-06-04 13:33 UTC
TypeError: Cannot read property 'mood' of undefined
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:55:12)
this._zone.runOutsideAngular(function (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29098:86)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
runOutsideAngular (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28074:27)
this._zone.runOutsideAngular(function (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:29098:23)
_this._zone.run(function (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28954:26)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
META: SP5.2.0 Browser – es-ES – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Reload App

### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2020-06-04 13:58
Thanks for reporting!

I just released a patched build for this:
https://github.com/johannesjo/super-productivity/releases/tag/v5.2.3

**Comment by johannesjo** [comment] 2020-06-04 13:59
Also this seems to be a duplicate of https://github.com/johannesjo/super-productivity/issues/380

**Closed by johannesjo** 2020-06-04 13:59 UTC
