### ISSUE TITLE
tasks are stopped by clicking other projects or today

### ISSUE THREAD

**Issue by aminraz** [johannesjo/super-productivity#322] opened 2020-04-02 13:13 UTC
### Your Environment

* Version used: snap
* Operating System and version: ubuntu 18.04
* Desktop Environment:  linux
* Browser Name and version: 

### Expected Behavior

Continuous time keeping while the user is surfing tasks and projects
### Steps to Reproduce (for bugs)

1. start a task in today's tab or any other project
2. click on other projects or today's tab
3. the task is stopped just by clicking another project
 I'm not sure if this behavior is intended or not. But when you want to review your tasks and projects and decide which one you want to start and then add to today, this disrupts time keeping. I tested this in the web version and this happens there too.

Very useful app,
Keep it up.

**Comment by johannesjo** [comment] 2020-04-02 16:20
That's (currently) the intended behaviour.

**Comment by MafiaInc** [comment] 2020-04-16 21:57
I think this is resolved now with the commit 63f88b3. At least I tested it today on snap 5.0.10 and my task is keep on tracking if I only browse around projects tabs.

**Comment by johannesjo** [comment] 2020-04-16 22:00
@MafiaInc yes! Your absolutely right. I just forget to close this :)

Please let me know, if you encounter any related issues.

**Closed by johannesjo** 2020-04-16 22:00 UTC
Labels: discussion, enhancement, help wanted

**Comment by aminraz** [comment] 2020-04-17 10:52
Cool! Works like a charm.
