### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by muhamadrizkiariffadillah** [johannesjo/super-productivity#3275] opened 2024-07-20 01:18 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'then')
    at show (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:186:5567)
    at o.when.show (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:48125)
    at file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:2781
    at Array.forEach (<anonymous>)
    at iM.trigger (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:2723)
    at iM._show (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:40513)
    at iM.show (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:38567)
    at j7.show (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:45752)
    at j7.next (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:45278)
    at e.next (file:///snap/superproductivity/1971/resources/app.asar/dist/browser/main-JWCHIBT3.js:198:47765)
```

### Actions Before Error
```
1721438138737: [Persistence] Save to DB (3) 
1721438138787: [Task] UnsetCurrentTask 
1721438141040: [Task] Update Task 
1721438141052: [Persistence] Save to DB 
1721438142334: [Task] SetSelectedTask 
1721438148967: [Task] Update Task 
1721438148970: [Persistence] Save to DB 
1721438152224: [Task] Update Task 
1721438152242: [Persistence] Save to DB 
1721438164418: [Task] SetSelectedTask 
1721438164419: [Layout] Hide Notes 
1721438167675: [Task] Update Task 
1721438167677: [Persistence] Save to DB 
1721438171631: [WorkContextMeta] Move Task in Today 
1721438171641: [Persistence] Save to DB 
1721438171641: [Task] Update Task 
1721438171654: [Persistence] Save to DB 
1721438178444: [Task] Update Task 
1721438178447: [Persistence] Save to DB 
1721438183513: [Task] SetSelectedTask 
1721438186313: [Task] Delete Task 
1721438186337: [Persistence] Save to DB (3) 
1721438186341: [Task] UnsetCurrentTask 
1721438208085: [Project] Add Project 
1721438208087: [Persistence] Save to DB 
1721438221974: [Global Config] Update Global Config Section 
1721438222102: [Persistence] Save to DB 
1721438241823: [Global Config] Update Global Config Section 
1721438241876: [Persistence] Save to DB 
1721438241876: [Dropbox] Trigger Auth Dialog
```

**Comment by johannesjo** [comment] 2024-07-22 06:50
Duplicate of #3270

**Closed by johannesjo** 2024-07-22 06:50 UTC
