### ISSUE TITLE
Feature Request: Cross-project daily to do list

### ISSUE THREAD

**Issue by ThatRobVK** [johannesjo/super-productivity#163] opened 2019-04-18 08:37 UTC
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior

I work on multiple projects daily and love having the separate backlogs so that I can clearly see what's required on each project and plan my day out. However, throughout the working day it's a bit of a pain to have to switch between projects to see which tasks I had planned. I do flit between projects, doing tasks for each throughout the day.
I'd love it if you can have a unified view of the planned tasks so that I have a single list to work from, and prioritise tasks against each other across the projects.

### Current Behavior

Daily tasks are separate between projects.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2019-04-18 18:14
Hey there! I like the idea and I thought about it before myself. The complexity of this task is a major problem. Atm. all the time tracking logic is project based and relies on a specific project being checked out. This is done to limit the data the app has do process at the same time.  Getting the UI right for this will be another major issue. There are lots of edge case to think about. I probably will give it a go at some point, but I will focus on other less complicated tasks first.

**Comment by ThatRobVK** [comment] 2019-04-24 20:58
No problem, that's fair. When my time frees up a bit I may be able to help out. Keep up the great work!

**Comment by KonTy** [comment] 2019-06-03 18:03
> Atm. all the time tracking logic is project based and relies on a specific project being checked out. This is done to limit the data the app has do process at the same time. 

Have you thought about ding it just a a view? Meaning I can go around each Project and add tasks from each project to "My Day". All this will do is show tasks in "My Day" in one list. but the logic of checking out the project etc what you mentioned above could stay the same with no changes. Same applies to showing tasks with hashtags. It is just a "view" all the other logic stays the same.

**Comment by johannesjo** [comment] 2019-06-04 21:20
@KonTy it is not as simple unfortunately. Data is split up into chunks into different entries of a indexeddb. The task in backlog and the daily to do list are in such a chunk. Every project has a couple of those chunks. The task data is then loaded to a redux store which is in turn used to update the data and save it back to the database (always as a complete chunk). To make it work well, I probably will have to change the underlying data structure or provide a complicated meta interface.

**Comment by KonTy** [comment] 2019-06-08 01:54
@johannesjo hmm yes sounds pretty complicated. Have you ever thought about converting it to SQLite? I mean I think with having a real DB backend perf issues will go away. Think about it Adobe Lightroom uses SQLite for storing hundreds of thousands pictures with metadata and even thumbnails. 

But you are rights in the sense that first and foremost you will need an interface something like ITaskProvider and use any technology underneath JSON/SQL/WebAPIs whatever. Shoot I wish I could get some time to help out here. I love your app but these small things are really nagging.

**Comment by johannesjo** [comment] 2019-06-10 15:29
@KonTy IndexedDB shouldn't be too much slower I assume. The problem is more on a view model level.  I think I have to do some tests. Maybe it's possible to just have single task model and not split them up.

**Comment by a4bits** [comment] 2019-10-02 22:11
I very like this idea. It would be good also to make summary of accomplished tasks. I also work on many project daily - and I need sum hours of all of those projects to see how productive I was... It will be great add-on.

**Comment by KonTy** [comment] 2019-10-03 14:41
> I very like this idea. It would be good also to make summary of accomplished tasks. I also work on many project daily - and I need sum hours of all of those projects to see how productive I was... It will be great add-on.

You do get that view already!!!! When you finish your day you get the stats, also in the left navigation pane there are a tabs called Metrics and Worklog that give you exactly that.

**Comment by a4bits** [comment] 2019-10-07 12:20
What I see its metrics per project. Every project has its own separate metrics. Or I am reading it wrong way? It would be great to have one "master" tab for all active tasks from all projects that are not in backlog. there can be colored info for which project the task is for. I usually work on many projects and I also have tab called 'learning' for things i want and need to learn.

**Comment by johannesjo** [comment] 2019-10-13 22:50
So I have given this some thought lately. I think I have a rough technical concept and even a path for migration that should work. I'm still having hard time to figure this out. One of the things I like about the app, that it gives my day some structure and that it gives it a certain endpoint with the daily summary. I'm really not sure how to put this together with a shared task list. Personally I just use a single project for work and I like having it out of the way once I get home and work on my own stuff. 

There are lots of other conceptual problems too. What should happen with the metrics and the evaluation sheet (should they be global)? What happens with the worklog for the shared list? How to treat tasks with attached issues? Should they be polled for changes all the time for changes even if the project is not active itself?

What I ideally like to achieve is the following:
1. Have a good way to put work stuff out of my sight once I am home
2. Have a way to pull together different tasks in case I am working on different projects
3. Having some place for everyday chores, where time tracking is irrelevant (Not sure if it's a good way to put all this in. Maybe Super Productivity should be for work and side projects only)
 4. Avoid making the app too complicated to use. The basic structure and what's happening should be obvious to the user without having configure too much by himself.

I really could use your input on all this questions, maybe even some advice where to ask for more feedback on this.

**Comment by a4bits** [comment] 2019-10-16 11:15
maybe something like that...
where projects have its submenu. and there is on top "TODAY", and on right side there are written for which project task is assigned.

![super-productivity-notes](https://user-images.githubusercontent.com/40560367/66914299-ccf3fe80-f016-11e9-822a-8dc3ed462302.jpg)

**Comment by KonTy** [comment] 2019-10-16 16:13
> So I have given this some thought lately. I think I have a rough technical concept and even a path for data migration that should work. I'm still having hard time to figure this out. One of the things I like about the app, that it gives my day some structure and that it gives it a certain endpoint with the daily summary. 

I agree this is a very big thing that is important to understand. Here is a scenario that I ran into and how my Microsoft Todo is unitized. 

I have big areas and I used Lists for them for example

- Work <-- this is a list
-- Big Data <-- this is a project
--- follow up with Johan <-- task
---- sub tasks for complex tasks
---- sub tasks for complex tasks
--- build a database <-- task
--- so on
-- User App <-- another project
--- Create MVP 
--- Build menu
- Home <-- this is a list
-- Chores <-- this is a project
--- wash dishes
--- take dog outside
-- Hobby <-- this is a project
--- review github messages
--- review reply to issue #163
-- House improvement <-- this is a project
--- so on


Are you following the GTG strategy by David Allen? Basically you have to review all your tasks in the beginning of the day and plan your day. MS Todo you can right click any task and add it to "My Day" which will create a view with all tasks in My Day. Todo can also recommend "My Day" tasks based on reminded and due dates. This is a very very good model. So that in the morning you can sit down plan your day, add tasks from different projects to your day and then execute on the plan. 

MS Todo also has an other views "Planned" "Assigned to me" etc. 

*All* those Views to me are no more no less then Tags. So if there was an ability to query tasks by Tags and display them and then create a custom View for those Tags that would solve the problem very quickly.

Todoist for example event allows you to create a new View (based on a filter) where you specify all your Tags (they call them labels) and it will create a new Menu Item (project in the case of Super Productivity) so when you click on it it will create a custom View with all the Tasks that have that label.

I don't know if you are following me or not. Are you using Microsoft Teams? I can call you and project my screen to demonstrate visually.



>I'm really not sure how to put this together with a shared task list. Personally I just use a single project for work and I like having it out of the way once I get home and work on my own stuff. So one of the main question is: What should happen with the daily summary?

I described it a little bit above. When you plan your day you look at all tasks in all projects including Home/Work/Chores/Hobbies whatever you add them to your "My Day". Behind the scence in the code you would just add a Tag #MyDay and in the "My Day" view you would display all tasks with that tag. 

Also if you don't like seeing both Home and Work items on a Day view you can ignore them. Or if there was an ability to define a custom view like in Todoist you could have "My Day Home" and "My Day Work" views and use different labels for those. 

Take a look at this https://get.todoist.help/hc/en-us/articles/360000029000-How-to-best-use-labels

I would really recommend to study how MS Todo and Todoist do it before designing this. (I can help, I've been using these tools for a long time) take a look at this video first https://www.youtube.com/watch?v=Xsu2ObjC12s


> There are lots of other conceptual problems too. What should happen with the metrics and the evaluation sheet (should they be global)? What happens with the worklog for the shared list (should there be one)? 

For this if "My Day" and other custom things become Tags all these things just become pivots for reports and Graphs. You should be able to display
- Summary All Tasks in a period of time
- Summary by Project for a period of time
- Summary by a chosen tag for a period of time
- Totals for the above
- Graph of All Tasks per day
- Procrastination rate (due date vs completed on that date if you push a tasks forward that's a strike against you) per day/Per week. For All tasks, for a chosen tag

So if there was an ability to pivot by tag or project (as a dropdown or free text) that should be good enough

> How to treat tasks with attached issues? Should they be polled for changes all the time for changes even if the project is not active itself?

I'm lost here a bit I'm sorry I don't understand the technical challenge here since I'm coming from the world of Big Data and relational DBs. In relational world you would just do for your "My Day" view for example SELECT * from Tasks WHERE Tag CONTAINS ("#MyDay"). Problem solve it would give you All tasks with that tag across *all* protects. I wish knew IndexDB better but from what I gather you telling us here I think the whole backend storage should be reevaluated??? You mentioned that SQLite3 can not be used to WebApps? I found this tutorial to use it for Web Apps here could you please take a look to see if this helps? https://www.youtube.com/watch?v=b5Ncv6_D0hU

If it doesn't I think one thing that should be considered is dropping web app support, I think having it as an Electron app with redesigned db backend which would allow you to sync with MS Todo/Todoist/Google Todo you name it. And perhaps having an Android app will solve all the Todo needs of everyone :)


> What I ideally like to achieve is the following:
> 
> 1. Have a good way to put work stuff out of my sight once I am home

Custom Tags View solves this problem

> 2. Have a way to pull together different tasks in case I am working on different projects

Custom Tags View solves this problem where you Add a "#MyDay" tag and display my day View

> 3. Having some place for everyday chores, where time tracking is irrelevant (Not sure if it's a good way to put all this in. Maybe Super Productivity should be for work and side projects only)

Custom Tags View solves this problem.

> 4. Avoid making the app too complicated to use. The basic structure and what's happening should be obvious to the user without having configure too much by himself.

Custom Tags View solves this problem. My Todo is very, very easy to use and that's what they have

> I really could use your input on all this questions, maybe even some advice where to ask for more feedback on this.

Please let me know I know I can't help with developement due to lack of time and steep learning curve but I can advise on design, I've been using productivity apps and designing apps for a long time. But most of all I want Super Productivity to succeed.

**Comment by johannesjo** [comment] 2019-10-16 17:17
Thank you very much for your input. It's very helpful to me! I like the idea of converting projects basically to tags. It's probably the best approach to go. 

The problem is that this would mean, that I would have to rewrite and re-conceptualize *everything*, including:

1. The task model
2. The project model
3. Persistence
4. The Jira & Git Integration
5. Daily summary
6. Metrics
7. Data export/import
8. Big changes to the user interface

This probably means at least 2 month working full time on the app, probably even more. You can probably guess that while I love working on it, it's just not a realistic, as I need to earn money too. 

I spend the last couple of days thinking about all this stuff and I am afraid this is what it boils down to. It just doesn't seam feasible to implement this feature without major changes to almost everything.

Nevertheless I will start experimenting a little bit with all this on a separate project. Given the scope of this, it's probably easier to start fresh and to migrate existing pieces bit by bit once the core of everything is working.

**Comment by a4bits** [comment] 2019-10-16 17:27
Maybe we could help in some way in coding? 

I never did app for gnome/linux desktop, etc. But it seems like HTML/CSS/JS and some other things... 

But this would require some tasks to be opened, and if someone feels enough strong, could take the task :-)

**Comment by johannesjo** [comment] 2019-10-16 17:39
@a4bits Thank you! I experiment with the basics and get back to you.

**Comment by KonTy** [comment] 2019-10-16 18:29
> Maybe we could help in some way in coding?

I wish I could I'm like Johan need to earn money and don't have a lot of time for anything extra :(

**Comment by KonTy** [comment] 2019-10-16 18:37
> I spend the last couple of days thinking about all this stuff and I am afraid this is what it boils down to. It just doesn't seam feasible to implement this feature without major changes to almost everything.

I totally get it man, I know *EXACTLY* how it is. I'm actually shocked at times how productive you are at this. Recent changes that you've implemented like the side menu etc. are game changers already.

As far as experimenting. My suggestion is that create a new branch for v2 that way development could happen in parallel. Another suggestion is to stop taking in new features into v1 work only on bugs. It is already an outstanding app as it is. Well except this crippling thing like data backend that doesn't allow syncing with other services and do cross project things.

for v2 my suggestion is to start small remove all JIRA and other syncs. Just focus on the data backend implementing it correctly. Lay down the rules basically for the MVP (minimal viable product)

Also if you fork the app and disable all the advanced features, I think I will feel more enabled to help out since I will not be breaking the main product :)

You are doing an outstanding job man I'm shocked at how productive you are. I actually wouldn't mind having you on my team :) wanna come work to US?

**Comment by KonTy** [comment] 2019-10-16 19:11
> @KonTy Thanks you for the warm words! I'll get in touch if I ever move to the us ;)

Wanna start a new project in a new repo? Like just simple pull in all of the libraries don't have any fancy UI, just a blank canvas where we could start experimenting with databases? I would do that but I've never done web development don't know where to start. 

Basically here is my suggestion:
1. Create new repo
2. Create new project with all the dependencies to be able to build an Electron app
3. Create a simple page where we could start rendering things like treeview based on a DB query
4. Look at different DB backends, I just don't know if[ IndexDB is good enough for this](https://stackoverflow.com/questions/8694941/conceptual-problems-with-indexeddb-relationships-etc). Fundamentally Todo is relational in structure and IndexedDB doesn't support it. Let's take a really close look at Sqlite3? Here is something to consider https://github.com/kripken/sql.js

**Comment by alexriabtsev** [comment] 2019-10-29 11:07
+1 vote for Today view as I have dozen of projects to balance between every day and having one viewpoint for all my tasks would be a gamechanger!

And thanks a lot for super-productivity - I really LOVE it, Johannes!

**Comment by johannesjo** [comment] 2019-11-09 00:06
I wrote down how this could work (on a conceptional level). Please let me know what you think about it:

### Shared Task List (My Day / Today)
* Is a non deletable pseudo project -> has its own theme, can have tasks of its own, has its own metrics, notes and bookmarks
* Make it a list that can be manually filled from all other projects 
* maybe add a button to import all tasks not in the backlog from other projects?
* Tasks added from another project are not removed from them
* Each task gets a colored project badge to distinguish them

### Add task bar
* Context aware auto adds to current project if one is selected
* Optional control to add a task to another project
* Provides issues only if list with issue integration is selected
* Suggest issues from all other projects when on todays list

### Finish Day/ Daily Summary
* Finishes Day for current project when on a project list
* Or finishes day for all projects with tasks being worked on today
  * But lists tasks separated by project
* Finish day Reminder is global (My Task List)
  * But can be optionally activated for single projects as well

### Evaluation
* Make feature optional on a project level (including Today list)
* Improvements and Obstructions (the suggestions) are shared between projects
* (Make habit bar a separate feature which is global (later on))

### Metrics
* Move to project context menu (three dots right of a project in the list, right click on it)
* Only display non evaluation stuff if feature is enabled for the project

### Notes
* Keep as is
* Add separate collection for My Day
* (add full size note view later on)

### Bookmarks
* My Day get's its own bookmarks
* Leave the rest as is

### Task Reminder
* Context Aware, switch to project only if not on MyDay and not on project already
* Switch to MyDay if task is in my day rather than to project

### Worklog
* Get's its own project selection button, otherwise lists all tasks for all projects
* Also accessible via project context menu

### Menu
* add worklog and metrics to project menu

**Comment by alexriabtsev** [comment] 2019-11-09 12:37
that should be great, @johannesjo!

**Comment by alexriabtsev** [comment] 2019-11-20 13:54
any updates on this feature, @johannesjo?

**Comment by johannesjo** [comment] 2019-11-20 14:00
It's a big feature and currently I have only a limited amount of time. I probably won't get this done before Christmas.

**Comment by alexriabtsev** [comment] 2019-11-20 21:31
I do hope that you'll be able to do it before NY ;)

**Comment by johannesjo** [comment] 2019-11-21 11:09
@alexriabtsev me too :D

**Comment by johannesjo** [comment] 2020-03-13 22:03
In case anyone is interested: I am working hard on this again and I am making good progress:
https://github.com/johannesjo/super-productivity/tree/feat/shared-task-list-via-tags
 
Lots of stuff is not working currently and needs to be redone, but there should be enough there to see, where its heading. Feedback would be very welcome and if someone got some time on their hands, help with coding too.

**Comment by johannesjo** [comment] 2020-03-26 18:54
The Feature has been implemented and is available in v5.0.0

**Closed by johannesjo** 2020-03-26 18:54 UTC
Labels: discussion, enhancement
