### ISSUE TITLE
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'    at statSync (node:fs:1615:3)    at t.statSync (node:electron/js2c/asar_bundle:2:4557)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40    at Array.map ()    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71    at new Promise ()

### ISSUE THREAD

**Issue by Dolfost** [johannesjo/super-productivity#2906] opened 2023-12-08 10:20 UTC
### Steps to Reproduce

1. `brew install superproductivity`
2. launch it

### Stacktrace
```
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
```

### Meta Info
META: SP7.16.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1702030687135: [FocusMode] Set focus session elapsed time 
1702030687187: [SP_ALL] Load(import) all data 
1702030687188: [SP_ALL] All Data was loaded 
1702030699665: [FocusMode] Set focus session elapsed time 
1702030699697: [SP_ALL] Load(import) all data 
1702030699698: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment] 2023-12-08 16:12
Duplicate of  #2903

**Closed by johannesjo** 2023-12-08 16:12 UTC
Labels: bug, help wanted
