### ISSUE TITLE
[Feature Request] Daily Agenda configurable break

### ISSUE THREAD

**Issue by tiagogala** [johannesjo/super-productivity#116] opened 2018-09-05 10:44 UTC
When you estimate how long your tasks will take, the Daily Agenda gives you a nice overview of your work day and automatically estimates at what time you should be starting a new task. This is great, but on a "normal" 9-to-5 work-day people take a lunch break, and this means that there will be an offset on the start time on all of the afternoon tasks.

This feature request is to ask for a way to configure at what time one usually has a lunch break and how long does it take, that way the Daily Agenda could show that and offset the afternoon tasks to the proper start time (and possibly showing a task that begins in the morning, stops for lunch and continues in the afternoon). 

BTW, thanks for the awesome app!

**Comment by johannesjo** [comment] 2018-09-05 15:13
Hey there! Thanks for opening up this issue! There is indeed a lot of room for improvement on the daily agenda. Currently I'm not using the feature myself at all, as usually the planing never works out as intended on a time scale and I find it easier to deal with the few appointments I have, in a real calendar. Thinking about it, I get the idea that it might be better to ditch the functionality altogether. 

Not sure how many people are using this feature at all and if so how they use it (I am not collecting any user metrics) or how they would like to use it. It would be interesting to hear your thoughts about it! How would a useful implementation look like for you and what would the benefits be.

**Comment by johannesjo** [comment] 2019-02-10 18:05
As the daily agenda is removed with v2, I am closing this.

**Closed by johannesjo** 2019-02-10 18:05 UTC
