### ISSUE TITLE
ERROR: Error: Project sYiCkqhSi not found

### ISSUE THREAD

**Issue by John955** [johannesjo/super-productivity#710] opened 2020-12-01 16:33 UTC
Error: Project sYiCkqhSi not found
webpack:///src/app/features/project/store/project.reducer.ts:76:12
function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1096:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1019:39)
args (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1059:38)
function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1105:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1019:39)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:868:24)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
META: SP6.1.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.0 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

__________________________________________________________________________________________________________________________________
using the windows 10 app
the project refrenced above was never created
error occurred when testing and playing around. projects were created and deleted in quick succession

Thank you for the app. It is really great. I really like the interface and it has a fantastic feature set.

### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2020-12-01 19:41
Thank you very much for reporting this. I'll look into it.

Note to self: ** error occurred when testing and playing around. projects were created and deleted in quick succession **

**Comment by johannesjo** [comment] 2020-12-03 18:34
It looks like that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export". 

If the error occurs on startup, you might still be able to go there, though it might be a bit tricky to navigate around the modal. If not you might be able to find the latest data in the [folder for automatic backups](https://github.com/johannesjo/super-productivity#automatic-backups).

**Comment by johannesjo** [comment] 2020-12-13 09:53
ping @John955

**Comment by John955** [comment] 2021-01-13 21:38
Hi,

My apologies, I was busy with school and projects and forgot. If you still
could use my data, I have attached it. I accidently cleared part of my file
system, so I don't have the original original export, but I haven't used
the app that much between then and now, so perhaps you could get something
from this export. I will also send this to the original email as you
instructed, but wanted to send one here, as it has been a while, so you
could trace it back. If there is anything else I can do don't hesitate to
contact me and I will try to be more timely in my response. I'll let you
know if I get the error again, as I will be back using the app this
semester. And again, apologies for my extremely delayed response.

Thanks,

John

**Comment by johannesjo** [comment] 2021-01-14 20:24
No worries! And thank you very much for the offer. There is probably not much we can do for now anyway, so I am going to close this issue. But please let me know if this happens again for some reason!

**Closed by johannesjo** 2021-01-14 20:24 UTC
Labels: bug, needs clarification, unable to reproduce
