### ISSUE TITLE
Cannot import Google Calendar to snap version of SP using ICS

### ISSUE THREAD

**Issue by sql-sith** [johannesjo/super-productivity#1814] opened 2022-01-07 20:26 UTC
### Your Environment

- Version used: snap, 7.9.2
- Operating System and version: Ubuntu 20.04.3 LTS
- Desktop Environment: GNOME shell 3.36.9
- Browser Name and version: although I primarily use the snap version, I could not find good logs for it, so I am attaching a console log produced with Vivaldi 5.0.2497.32 64-bit (stable) for your viewing pleasure.

### Expected Behavior

If I enter my secret Google Calendar ICS URL in the Timeline settings, my Google Calendar events should be displayed in the SP Timeline.

### Current Behavior

Errors occur, as seen in the attached console log.

#### To Reproduce a Successful ICS Import

1. Open Timeline settings in the Web app.
2. I have emailed you the full URL for a file named `simple-example-success.ics`. Add an ICS source using this URL.
3. Save the settings and open the Timeline view. The events will have been imported successfully.

#### To Reproduce a Failed ICS Import

1. Open Timeline settings in the Web app.
2. Delete the ICS source created during the repro of the Successful use case.
3. Save the settings.
4. I have emailed you the full URL for a file named `simple-example-error.ics`. Create a new ICS source using this URL.
5. Save the settings. Errors will occur.

### Console / Error Log Output

I could not find anything in the `snap` directory that contained the error messages I observed in the UI, so I recreated the error in the Web app and grabbed them from the developer tools console. It's a little long, so I will attach it. The attached console log is from a repro when I used a larger ICS file, so it has more than the single error that is caused by the `simple-example-error.ics` file. If you need a larger ICS file to work with, just let me know.

[app.super-productivity.com-1641582634002.log](https://github.com/johannesjo/super-productivity/files/7831152/app.super-productivity.com-1641582634002.log)

**Comment by johannesjo** [comment] 2022-01-08 16:14
Thanks for opening this up! Seems that there for some reason is an event that has a start time (`dtstart`), but no end time (`dend`). Not sure if this is supposed to be possible, but I will add a workaround for it.

**Comment by johannesjo** [comment] 2022-01-08 16:26
This should be fixed with the next release. Events without and end time now just simply get a default value of 15 minutes. Thanks again!

**Closed by johannesjo** 2022-01-08 16:26 UTC
Labels: bug

**Comment by sql-sith** [comment] 2022-01-08 19:11
That was amazingly fast. Thanks, @johannesjo !

**Comment by sql-sith** [comment] 2022-01-08 20:13
Hey @johannesjo , your observation about DTSTART without DTEND made me remember something unique about the event in the test files that caused the error. It is a zero-time event. In other words, it starts and ends at the same time. I do this on my calendar for reminders because I like having everything time-based on a calendar, and because I don't like day-long events for things I want to do at a particular time. 

The comment that this should not be possible got me thinking. I have tons of curiosity, Johannes, so I research anything I can. :)

Microsoft handles this in the way you'd expect: DTSTART and DTEND are set to the same time. However, it appears that Microsoft's behavior is actually incorrect, and Google's is actually correct.

The [ICS stardard](https://datatracker.ietf.org/doc/html/rfc2445) states the following:

---

**Page 53, in the section defining VEVENT:**
 
_For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE-TIME data type but no "DTEND" property, the event ends on the same calendar date and time of day specified by the "DTSTART" property._
 
In other words, what Google is doing is OK.
 
**Page 91, in the section defining DTEND:** 
_Conformance: This property can be specified in "VEVENT" or "VFREEBUSY" calendar components._
 
In other words, as was implied on page 53, DTEND is not mandatory, since the word SHOULD is not used.
 
**Page 91, in the section defining DTEND:** 
_Within the "VEVENT" calendar component, this property defines the date and time by which the event ends. The value MUST be later in time than the value of the "DTSTART" property._
 
In other words, Microsoft should not include a DTEND that is the same value as DTSTART.

---

I have a feeling that what Microsoft is doing is common because it makes so much sense and is such a subtle violation of the RFC ("MUST be later in time" vs "MUST NOT be earlier in time"). But if it wouldn't mess up the internals of the app too much, could you change the 15-minute duration to 0 minutes? That would make the patch RFC compliant.

I am going to submit a modification to your [ae193b](https://github.com/johannesjo/super-productivity/commit/ae7193b7d58ee7611207d07be3b9d0fefc792852) defaulting the DTEND to DTSTART. Please accept it if it won't cause problems elsewhere in the program. I'm hoping it won't since it appears that iCAL events are only displayed and not otherwise acted upon. 

Thanks again. I am bus today but am sold on this project. I will contribute when I can (but again, not a javascript guy) and hope to sponsor soon after plowing through my last "end of year" goals today (better late than never, right?). Great stuff, Johannes.

**Comment by johannesjo** [comment] 2022-01-08 21:06
Thank you very much for digging into this! That's interesting indeed! 

The question I ask myself is "How would one want those zero time events to show up in the timeline?" My first intuition was that a zero time event makes no sense, at it at least should take some time. If understand you correctly you'd prefer them to show up on the timeline as zero duration events as well, right? And does this work as you'd expect with the changes you made? 

I also think we might want to add an additional unit test to check if this works as intended with the timeline and with future changes to it. This looks definitely like an edge case that might get broken unintentionally :)

**Comment by sql-sith** [comment] 2022-01-09 02:12
It's actually a feature of the RFC, right? So it's not surprising that it's
supported by both MS and Google, even if they do it differently. Check out
these screenshots, which actually show zero minutes as an option in the
dropdown menu. So although I understand your surprise, I don't think this
is an edge case. I think it's just a case you didn't expect. I'm obviously
biased, but to me, it's perfectly natural to want to put time-based
reminders onto a calendar. These are things that I want to be reminded of
at a particular point in time but for which, for whatever reason, I don't
want to assign a specific time until later, like "find out when Darrin can
have breakfast tomorrow." That's not a great example, but that's the idea.
And as I've pointed out, it's part of the RFC, and as you can see below,
it's not just *supported* by Microsoft and Google, but actually *suggested *by
both of them in their interfaces.

And if you scroll all the way down to the third screenshot, you'll see that
zero-minute events already work in Super Productive. The appointment on
Monday called *Respond to calendar app'ts* is a recurring daily reminder
for me to look at my appointments every day and make sure I've responded to
all of them. And SP handles it beautifully. :)  Look where the duration
should be. It's empty. How much nicer could that be? It's perfect.

Oh, and don't worry about the repeated entries on that screenshot. I'm
looking into that, but it could be a problem with how Microsoft publishes
recurring events that have individual exceptions. At any rate, it's not
important for this discussion.

[image: image.png]
[image: image.png]
[image: image.png]

Thanks for everything,
Chris

**Comment by johannesjo** [comment] 2022-01-09 09:29
Thanks for your reply. The screenshots don't show up here unfortunately.

**Comment by sql-sith** [comment] 2022-01-10 00:19
Well, that's no good! Can you see the files here?
https://www.dropbox.com/sh/d1d07h44bb30z4c/AAA1tzWOIyMAUBRtlxxwu_Iga?dl=0

**Comment by johannesjo** [comment] 2022-01-11 16:31
> Well, that's no good! Can you see the files here?

Yes! Thank you!
