### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of nullTypeError: Cannot read property 'summary' of null    at t.displayIssueWith [as displayWith]

### ISSUE THREAD

**Issue by yanjost** [johannesjo/super-productivity#1458] opened 2021-08-16 10:05 UTC
Title too long, original title would have been: 

```
Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of nullTypeError: Cannot read property 'summary' of null    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
```

### Steps to Reproduce

1. Don't use SP since 7.3
2. Upgrade the snap to 7.5.5
3. Try to switch to a JIRA-synchronized project
4. BOOM

### Error Log (Desktop only)
I can't find the log file as it is installed via snap

### Console Output

```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
task.reducer.ts:91 @ngrx/store/update-reducers Objectfeatures: Array(14)0: "globalConfig"1: "projects"2: "context"3: "layout"4: "bookmark"5: "pomodoro"6: "tag"7: "simpleCounter"8: "taskRepeatCfg"9: "tasks"10: "obstruction"11: "improvement"12: "metric"13: "note"length: 14__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Objecttype: "@ngrx/store/update-reducers"__proto__: Object
task.reducer.ts:91 @ngrx/effects/init Objecttype: "@ngrx/effects/init"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
task.reducer.ts:91 @ngrx/store/update-reducers Object
app.component.ts:287 Persistence already allowed
app.component.ts:316 3 out of 175869 MiB used (0%)
zone.js:2561 12:01:42.257 › No custom styles detected at /home/yannick/snap/superproductivity/1332/.config/superProductivity/styles.css
model-version.ts:34 Migrating model "GlobalConfig" to version from 2.2003 to 2.2005 Object
migrate-global-config.util.ts:112 EXTEND globalConfig sync localFileSync Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:34 Migrating model "GlobalConfig" to version from 2.2003 to 2.2005 Object
migrate-global-config.util.ts:112 EXTEND globalConfig sync localFileSync Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:34 Migrating model "SimpleCounter" to version from undefined to 2 Object
task.reducer.ts:91 [SP_ALL] Load(import) all data Object
task.reducer.ts:91 [SP_ALL] All Data was loaded Object
migrate-metric.service.ts:37 Migrating Legacy Metric State to new model
migrate-metric.service.ts:38 metricMigration: 1 Object
task.reducer.ts:91 [WorkContext] Set Active Work Context Object
task.reducer.ts:91 [Task] SetSelectedTask Object
task.reducer.ts:91 [Bookmark] Load Bookmark State Object
task.reducer.ts:91 [Note] Load Note State Object
task.reducer.ts:91 [Project] Load Project related Data Success Object
task.reducer.ts:91 [Improvement] Clear Hidden Improvements sw
task.reducer.ts:91 [Improvement] Delete multiple Improvements Object
jira-issue.effects.ts:296 JIRA_POLL_BACKLOG_CHANGES
global-error-handler.class.ts:36 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (main.29fbb60c3500c86c2112.js:1)
    at t._setTriggerValue (main.29fbb60c3500c86c2112.js:1)
    at main.29fbb60c3500c86c2112.js:1
    at l.invoke (polyfills.3f21005097f2d4ba8d4e.js:1)
    at Object.onInvoke (main.29fbb60c3500c86c2112.js:1)
    at l.invoke (polyfills.3f21005097f2d4ba8d4e.js:1)
    at t.run (polyfills.3f21005097f2d4ba8d4e.js:1)
    at polyfills.3f21005097f2d4ba8d4e.js:1
    at l.invokeTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at Object.onInvokeTask (main.29fbb60c3500c86c2112.js:1)
    at Z (polyfills.3f21005097f2d4ba8d4e.js:1)
    at polyfills.3f21005097f2d4ba8d4e.js:1
    at l.invokeTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at Object.onInvokeTask (main.29fbb60c3500c86c2112.js:1)
    at l.invokeTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at t.runTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at m (polyfills.3f21005097f2d4ba8d4e.js:1)
    at u.invokeTask [as invoke] (polyfills.3f21005097f2d4ba8d4e.js:1)
    at _ (polyfills.3f21005097f2d4ba8d4e.js:1)
    at HTMLButtonElement.k (polyfills.3f21005097f2d4ba8d4e.js:1)
(anonymous) @ global-error-handler.class.ts:36
action-logger.ts:30 Last actions before error: Array(30)0: "1629107761555: [Persistence] Save to DB"1: "1629107761556: [Persistence] Save to DB"2: "1629107761556: [Task][Issue] Add Task"3: "1629107761561: [Persistence] Save to DB"4: "1629107761562: [Persistence] Save to DB"5: "1629107761562: [Task][Issue] Add Task"6: "1629107761569: [Persistence] Save to DB"7: "1629107761569: [Persistence] Save to DB"8: "1629107761570: [Task][Issue] Add Task"9: "1629107761576: [Persistence] Save to DB"10: "1629107761576: [Persistence] Save to DB"11: "1629107761577: [Task][Issue] Add Task"12: "1629107761582: [Persistence] Save to DB"13: "1629107761582: [Persistence] Save to DB"14: "1629107761642: [Task] Update Task"15: "1629107761644: [Persistence] Save to DB"16: "1629107761646: [Tag] Add Tag"17: "1629107761654: [Persistence] Save to DB"18: "1629107761656: [Task] Update Task Tags"19: "1629107761665: [Persistence] Save to DB"20: "1629107761666: [Persistence] Save to DB"21: "1629108102695: [SP_ALL] Load(import) all data"22: "1629108102698: [SP_ALL] All Data was loaded"23: "1629108106495: [WorkContext] Set Active Work Context"24: "1629108106543: [Task] SetSelectedTask"25: "1629108106697: [Bookmark] Load Bookmark State"26: "1629108106723: [Note] Load Note State"27: "1629108106724: [Project] Load Project related Data Success"28: "1629108106725: [Improvement] Clear Hidden Improvements"29: "1629108106726: [Improvement] Delete multiple Improvements"length: 30__proto__: Array(0)
global-error-handler.class.ts:80 t
global-error-handler.util.ts:115 Object
zone.js:1063 Unhandled Promise rejection: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)
    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (main.29fbb60c3500c86c2112.js:1)
    at t._setTriggerValue (main.29fbb60c3500c86c2112.js:1)
    at main.29fbb60c3500c86c2112.js:1
    at l.invoke (polyfills.3f21005097f2d4ba8d4e.js:1)
    at Object.onInvoke (main.29fbb60c3500c86c2112.js:1)
    at l.invoke (polyfills.3f21005097f2d4ba8d4e.js:1)
    at t.run (polyfills.3f21005097f2d4ba8d4e.js:1)
    at polyfills.3f21005097f2d4ba8d4e.js:1
    at l.invokeTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at Object.onInvokeTask (main.29fbb60c3500c86c2112.js:1)
    at t.<anonymous> (main.29fbb60c3500c86c2112.js:1)
    at Generator.next (<anonymous>)
    at o (main.29fbb60c3500c86c2112.js:1)
    at l.invoke (polyfills.3f21005097f2d4ba8d4e.js:1)
    at t.run (polyfills.3f21005097f2d4ba8d4e.js:1)
    at polyfills.3f21005097f2d4ba8d4e.js:1
    at l.invokeTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at t.runTask (polyfills.3f21005097f2d4ba8d4e.js:1)
    at m (polyfills.3f21005097f2d4ba8d4e.js:1)
    at u.invokeTask [as invoke] (polyfills.3f21005097f2d4ba8d4e.js:1) Error: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)
    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at t.<anonymous> (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3525717)
    at Generator.next (<anonymous>)
    at o (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3523071)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at t.runTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at m (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:9146)
    at u.invokeTask [as invoke] (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:8231)
n.onUnhandledError @ zone.js:1063
zone.js:2561 12:06:01.062 › Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)
    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at Z (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16798
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7073)
    at t.runTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at m (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:9146)
    at u.invokeTask [as invoke] (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:8231)
    at _ (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:20135)
    at HTMLButtonElement.k (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:20380) Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)
    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at Z (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16798
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7073)
    at t.runTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at m (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:9146)
    at u.invokeTask [as invoke] (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:8231)
    at _ (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:20135)
    at HTMLButtonElement.k (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:20380)
s.<computed> @ zone.js:2561
zone.js:2561 12:06:02.442 › Frontend Error Stack: submit (webpack:///src/app/features/issue/providers/jira/jira-view-components/jira-cfg/jira-cfg.component.ts:190:17)
_setTriggerValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:708:30)
writeValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:566:46)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
resolvePromise (webpack:///node_modules/zone.js/fesm2015/zone.js:1283:16)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:582:34)
task.zone.runTask (webpack:///node_modules/zone.js/fesm2015/zone.js:491:20)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1600:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1626:16)
s.<computed> @ zone.js:2561
invokeTask @ zone.js:406
runTask @ zone.js:178
invokeTask @ zone.js:487
invoke @ zone.js:476
n.args.<computed> @ zone.js:2541
setTimeout (async)
i @ zone.js:2543
scheduleTask @ zone.js:393
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
f @ zone.js:679
(anonymous) @ zone.js:2585
s.<computed> @ zone.js:975
consoleLog @ /snap/superproductivity/1332/resources/app.asar/node_modules/electron-log/src/transports/console.js:93
transport @ /snap/superproductivity/1332/resources/app.asar/node_modules/electron-log/src/transports/console.js:46
runTransport @ /snap/superproductivity/1332/resources/app.asar/node_modules/electron-log/src/log.js:44
(anonymous) @ /snap/superproductivity/1332/resources/app.asar/node_modules/electron-log/src/transports/ipc.js:21
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
jira-issue.effects.ts:296 JIRA_POLL_BACKLOG_CHANGES
﻿```


### Stacktrace
```
submit (webpack:///src/app/features/issue/providers/jira/jira-view-components/jira-cfg/jira-cfg.component.ts:190:17)
_setTriggerValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:708:30)
writeValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:566:46)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
resolvePromise (webpack:///node_modules/zone.js/fesm2015/zone.js:1283:16)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:582:34)
```

### Meta Info
META: SP7.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1629107381273: [Project] Load Project related Data Success 
1629107381274: [Improvement] Clear Hidden Improvements 
1629107381275: [Improvement] Delete multiple Improvements 
1629107390533: [WorkContext] Set Active Work Context 
1629107390585: [Task] SetSelectedTask 
1629107390653: [Note] Load Note State 
1629107390655: [Bookmark] Load Bookmark State 
1629107390656: [Project] Load Project related Data Success 
1629107390656: [Improvement] Clear Hidden Improvements 
1629107390657: [Improvement] Delete multiple Improvements 
1629107411643: [WorkContextMeta] Move Task from backlog to today 
1629107411661: [Persistence] Save to DB 
1629107411664: [Task] Update Task 
1629107411669: [Persistence] Save to DB 
1629107416705: [Task] Update Task Tags 
1629107416723: [WorkContextMeta] Auto Move Task from backlog to today 
1629107416726: [Persistence] Save to DB 
1629107416727: [Persistence] Save to DB 
1629107416729: [Persistence] Save to DB 
1629107714952: [WorkContext] Set Active Work Context 
1629107715005: [Task] SetSelectedTask 
1629107715091: [Bookmark] Load Bookmark State 
1629107715111: [Note] Load Note State 
1629107715112: [Project] Load Project related Data Success 
1629107715113: [Improvement] Clear Hidden Improvements 
1629107715113: [Improvement] Delete multiple Improvements 
1629107738205: [SP_ALL] Load(import) all data 
1629107738208: [SP_ALL] All Data was loaded 
1629107738231: [WorkContext] Set Active Work Context 
1629107738253: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment] 2021-08-16 18:02
Thanks for reporting! I am closing this as a duplicate of #1441

**Closed by johannesjo** 2021-08-16 18:03 UTC
