### ISSUE TITLE
My English is bad ,can you add Chinese support ?

### ISSUE THREAD

**Issue by Suremotoo** [johannesjo/super-productivity#52] opened 2018-02-07 03:57 UTC
**My English is bad ,but Do not support Chinese！**

**Comment by hansgoed** [comment] 2018-02-13 18:57
duplicate of #33

**Comment by Suremotoo** [comment] 2018-02-16 13:43
thanks

At 2018-02-14 02:57:29, "hansgoed" <notifications@github.com> wrote:


duplicate of #33

**Closed** 2018-03-02 19:22 UTC
