### ISSUE TITLE
Replacement characters showing instead of proper font in notification

### ISSUE THREAD

**Issue by sbomsdorf** [johannesjo/super-productivity#3149] opened 2024-04-15 16:13 UTC
Hi all,

I am not sure whether this is an issue with the Desktop app or a problem with my setup (leaning towards the latter...): In the Finish-day-notification, when trying to close the app without doing so before, the font is not rendered and the windows is showing black rectangles/replacement characters instead (see [screenshot](https://github.com/johannesjo/super-productivity/assets/83335795/b1b1df0d-6b9b-48f8-8567-affe4e4ff00a)). I'd be truly thankful for any hint to either figuring out the real problem or even a solution to it.

### Steps to Reproduce
1. Try to close the app before finishing the day.
2. Getting a pop-up notification that should have the text to remind you to finish the day

### Error Log (Desktop only)
```
[2024-04-15` 17:55:29.304] [info]  close, isQuiting: undefined
[2024-04-15 17:55:29.314] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2024-04-15 17:55:41.551] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-04-15 17:55:43.269] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2024-04-15 17:55:43.270] [info]  close, isQuiting: undefined
[2024-04-15 17:55:43.273] [info]  close, isQuiting: true
[2024-04-15 17:55:43.307] [info]  Quit after all windows being closed
```

### Console Output
```
ipcEvent$ trigger NOTIFY_ON_CLOSE          ipc-event.ts:21
```

### Meta Info
META: SP8.0.5 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.5 Chrome/122.0.6261.156 Electron/29.2.0 Safari/537.36

**Comment by johannesjo** [comment] 2024-04-19 11:23
Hi there! Thanks for opening this up! This seems to occur on some linux machines. Haven't been able to reproduce it myself. Could you maybe provide a bit more infos about your system, e.g. which distro and display manager you are using?

**Comment by sbomsdorf** [comment] 2024-04-19 15:14
Hi Johannes,
Sure! The distro is Fedora 38 with GNOME 44.10 and display manager X11. 
The problem is not only with the notification I mentioned in the initial post. Meanwhile, I had an issue with the system time, which I suspect to have caused a notification in the app similar to "there is already an entry for that time stamp" or similar - I cannot tell because it was all replacement chars again. So, I assume that the problem is there for any notification that opens in another window.
Please let me know if there is anything else I can provide to help to resolve the issue.

**Comment by Jagdfalke** [comment] 2024-04-23 05:30
Duplicate of this one: #2619

**Closed** 2024-04-23 05:30 UTC
Labels: bug, unable to reproduce
