### ISSUE TITLE
Error: Uncaught (in promise): Error: No correct localLastSync given nullError: No correct localLastSync given null    

### ISSUE THREAD

**Issue by AndreiMihaiRad** [johannesjo/super-productivity#807] opened 2021-01-18 07:49 UTC
### Stacktrace
```
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:289:12)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3523065)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3522810)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3529625)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3522867)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3522810)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3529625)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dd7851f8c399c3d3ce7e.js:1:3522867)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28281:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

### Meta Info
META: SP6.3.3 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

**Comment by johannesjo** [comment] 2021-01-18 21:19
Thanks for opening this up. Looks like a duplicate of #720  (please upvote!)

**Comment by johannesjo** [comment] 2021-01-18 21:19
jk

**Closed by johannesjo** 2021-01-18 21:19 UTC
