### ISSUE TITLE
TypeError: Cannot read property 'subTasks' of null

### ISSUE THREAD

**Issue by kleinpetr** [johannesjo/super-productivity#1461] opened 2021-08-17 13:14 UTC
### Steps to Reproduce
1) create 2 projects (project1, project2)
2) schedule task in project1 to some time
3) switch to the project2 and wait until the time you've set
4) when the popup with scheduled task appears, click to the START
5) the task from project1 is now also added in the porject2
6) try to remove this task from the project2
7) you can see this error :)

### Stacktrace
```
TypeError: Cannot read property 'subTasks' of null
    at file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1492120
    at Array.forEach (<anonymous>)
    at su (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1492096)
    at o.project (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1518085)
    at o._next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1087433)
    at o.next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1075582)
    at c.next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1073331)
    at c.nextInfiniteTimeWindow (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1071903)
    at Object.next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1333147)
    at u.__tryOrUnsub (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1077400)
```

### Meta Info
META: SP7.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.1 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1629205565928: [Task] SetSelectedTask 
1629205588955: [Task] ReSchedule 
1629205588957: [Persistence] Save to DB 
1629205588957: [Persistence] Save to DB 
1629205592314: [WorkContext] Set Active Work Context 
1629205592321: [Task] SetSelectedTask 
1629205604568: [Layout] Show SearchBar 
1629205610504: [Layout] Hide SearchBar 
1629205775363: [WorkContext] Set Active Work Context 
1629205775399: [Task] SetSelectedTask 
1629205775527: [Note] Load Note State 
1629205775537: [Bookmark] Load Bookmark State 
1629205775538: [Project] Load Project related Data Success 
1629205775539: [Improvement] Clear Hidden Improvements 
1629205775539: [Improvement] Delete multiple Improvements 
1629205782535: [WorkContext] Set Active Work Context 
1629205782571: [Task] SetSelectedTask 
1629205782614: [Note] Load Note State 
1629205782619: [Bookmark] Load Bookmark State 
1629205782620: [Project] Load Project related Data Success 
1629205782620: [Improvement] Clear Hidden Improvements 
1629205782620: [Improvement] Delete multiple Improvements 
1629205785455: [WorkContext] Set Active Work Context 
1629205785502: [Task] SetSelectedTask 
1629205785545: [Note] Load Note State 
1629205785546: [Bookmark] Load Bookmark State 
1629205785546: [Project] Load Project related Data Success 
1629205785547: [Improvement] Clear Hidden Improvements 
1629205785547: [Improvement] Delete multiple Improvements 
1629205790619: [Task] Delete Task
```

**Comment by johannesjo** [comment] 2021-08-19 18:18
Thank you very much for reporting this! I think I found the cause of it and I look into to it tomorrow.

**Comment by johannesjo** [comment] 2021-08-20 10:47
Should be fixed with the next release. Thanks again!

**Closed** 2021-09-24 07:33 UTC
