### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by atilathehun** [johannesjo/super-productivity#1309] opened 2021-06-19 20:51 UTC
### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
```

### Meta Info
META: SP7.0.3 Electron – es-419 – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.3 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

### Actions Before Error
```
1624135863544: [Persistence] Save to DB 
1624135863544: [Persistence] Save to DB 
1624135864540: [Task] Add time spent 
1624135864541: [Tag] Update Work End for Tag 
1624135864548: [Persistence] Save to DB 
1624135864548: [Persistence] Save to DB 
1624135865540: [Task] Add time spent 
1624135865541: [Tag] Update Work End for Tag 
1624135865547: [Persistence] Save to DB 
1624135865547: [Persistence] Save to DB 
1624135866540: [Task] Add time spent 
1624135866541: [Tag] Update Work End for Tag 
1624135866547: [Persistence] Save to DB 
1624135866548: [Persistence] Save to DB 
1624135867540: [Task] Add time spent 
1624135867541: [Tag] Update Work End for Tag 
1624135867548: [Persistence] Save to DB 
1624135867548: [Persistence] Save to DB 
1624135868540: [Task] Add time spent 
1624135868541: [Tag] Update Work End for Tag 
1624135868549: [Persistence] Save to DB 
1624135868549: [Persistence] Save to DB 
1624135869540: [Task] Add time spent 
1624135869541: [Tag] Update Work End for Tag 
1624135869549: [Persistence] Save to DB 
1624135869550: [Persistence] Save to DB 
1624135871828: [Task] Add time spent 
1624135871829: [Tag] Update Work End for Tag 
1624135871834: [Persistence] Save to DB 
1624135871834: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-20 15:07
Duplicate of #398

**Closed by johannesjo** 2021-06-20 15:07 UTC
