### ISSUE TITLE
Not able to edit title of a task

### ISSUE THREAD

**Issue by kavyadav** [johannesjo/super-productivity#704] opened 2020-12-01 05:04 UTC
### Your Environment

* Version used: 6.1.0
* Operating System and version: Windows 10 S
* Desktop Environment: 
* Browser Name and version: 

### Expected Behavior
On clicking the title of a task, the box highlights, allowing one to rename or edit the title. 

### Current Behavior
When I click on a task, it doesn't highlight, and I am not able to edit the title. Same behaviour is observed with subtasks as well.

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2020-12-01 19:38
Thank you very much for taking the time to open this up. Unfortunately, I am unable to reproduce this.

**Comment by Chsbrgr** [comment] 2021-01-20 13:42
Hi,
I am experiencing the same issue as above on the Windows Desktop version and the Web app. I am unable to edit the title of a task or subtask after adding it to my list.

- Version used: 6.3.3 Windows desktop installer and Web app
- Operating System and version: Windows 10 Enterprise 1809
- Desktop Environment:
- Browser Name and version: Chrome 87

Steps to Reproduce (for bugs)

- Create a new task on desktop/web app, give it a title, and press enter to save it.
- Select the task from the task list by clicking on it
- try to change the title of the task or subtask.
- try to assign and use keyboard shortcut for "edit title"

Other things I've tried:

- Going into Keyboard shortcuts and assigning a shortcut to "edit title" - Accepted the keyboard shortcut assignment, but did not allow editing of the title.
- sync list to mobile client through Google Drive, then edit titles on the mobile app, and let them sync back - Works, but time consuming.

**Comment by johannesjo** [comment] 2021-01-20 19:57
Thanks @Chsbrgr ! I can use all the info I can get, because this is very weird. Especially that it happens for the web app as well. Does this happen consistently in your case?

**Comment by devismi** [comment] 2021-12-16 00:44
Uh oh, having the same issue with version 7.8.1 on desktop, as well as in the web app on Chrome. It's consistent, and I only noticed it happening in the past month or so, perhaps associated with an update.

Desktop app:

> App version 7.8.1

> Operating System: Windows 10 Enterprise 20H2

Web app: 

> Using Chrome Version 96.0.4664.110 (Official Build) (64-bit)

I can enter a task name when first creating it, but am unable to edit the task title after it is entered. Simply does not highlight the task name for editing when clicked the way it used to - just brings up and hides the task info sidebar repeatedly. Using the assigned shortcut key for task title edits yields no reaction. Same apparent behavior on both desktop and web app.

Additionally, I am having an issue where sub-tasks are automatically created without any name (no option to provide one when creating), and titles for sub-tasks are also uneditable once created. This means that the sub-tasks feature is unusable entirely, since I can only create blank sub-tasks.

Just FYI, I guess - let me know if additional info would be helpful. I love Super Productivity but unfortunately this issue is destroying much of the functionality I use.

**Comment by devismi** [comment] 2021-12-16 04:58
I installed same version of Windows desktop app on my home computer as well, which is running Windows 10 Pro 20H2. everything works as intended there: single click on the title of a task and it highlights the task name for editing, instead of just popping up the task info side bar. 

This is so bizarre! Apologies, I want to figure this out because this has become such a crucial tool for me at work.

**Comment by johannesjo** [comment] 2021-12-16 11:18
@devismi hi there! Does your computer have a touch screen? Might be that the touch screen and non touch screen programming is conflicted.

**Comment by devismi** [comment] 2021-12-16 17:30
@johannesjo  it does! Good point. I forget because I have it docked and typically use the connected monitors primarily. It's a Surface Pro 4... and it's had a history of messing really weirdly with the behavior or some applications, like AutoCAD. Hmm.

**Comment by devismi** [comment] 2021-12-16 19:28
@johannesjo I disabled the HID touch screen entries and the  Surface Pro Digitizer Integration in the Windows Device Manager, closed and restarted the SP app, and the app is back to working as normal! Hurray - an okay solution for now since I essentially never use the touch screen functionailty of the machine, but it would be nice to be able to use both touch-screen and SP at some point in the future. 

Thank you for pointing that out!

**Comment by johannesjo** [comment] 2021-12-16 21:19
I am glad that it works for now! :)

The subject is a bit tricky. If anybody has suggestions on how to make both approaches work at the same time, I am all ears!

**Comment by johannesjo** [comment] 2021-12-19 16:19
@everbody experiencing this. Could you do me a favor? I am interested in getting the output of this if you run it in your main browsers and the app console (Ctrl+Shift+i):
```
[
  'any-hover: hover',
  'any-hover: none',
  'pointer: fine',
  'pointer: coarse',
  'hover: hover',
  'hover: none',
].forEach((v) => {
  console.log(v, window.matchMedia('(' + v + ')').matches);
});
``` 
Along with the information what kind of device you are using and if you are using a mouse, a touchpad or the touchscreen of your device, this would be very helpful for finding a good solution for this.

**Comment by rreo** [comment] 2021-12-26 11:42
I'm having this problem using a mouse. For your debugging purposes, I've tried the touchscreen as well to no avail. Clicking/tapping the task brings up the task additional info sidebar. Applies to both tasks and subtasks. 

Device: Microsoft Surface pro-1796.
Version used: Desktop app version 7.8.1 / Web app version 7.8.1
Operating System and version: Windows 10 Pro 21H2
Browser version: Microsoft Edge Version 96.0.1054.57 (Official build) (64-bit)

Steps to Reproduce (for bugs)
1. Create a new task on desktop/web app, give it a title, and press enter to save it.
2. Select the task from the task list by clicking on it
3. try to change the title of the task or subtask.
4. try to assign and use keyboard shortcut for "edit title"

```
any-hover: hover false
any-hover: none true
pointer: fine false
pointer: coarse true
hover: hover false
hover: none true
```

**Comment by rreo** [comment] 2021-12-26 14:23
Also, not sure if related; the 'tasks' category shortcuts are not exactly working. I am a new user and do not know if this is normal behavior or is related to this bug.

I pressed 'w' to go to work view, then pressed 'tab' to focus on the first task in list. 

Firstly, it is almost impossible to notice the tasks are tab-focused, the only indication was the slightly rounded corners. 

Anyway, once a task is tab-focused, 
- 'j' does not go to the next task, 'k' does not go to the previous task.
- 'q' opens the task context menu but once dismissed, the task is unfocused. Pressing tab here will cycle the sidenav, there seems to be no obvious way to refocus to the task list. 
- 'i' shows the sidebar, but pressing i again does not hide it.  The task is unfocused again. clicking on the task to hide it interestingly focuses on the first task in list again.
- 'edit title' and 'add subtask' shortcuts are probably affected by this bug.
- the other shortcuts mostly work like 'd', 's', but the UX problem of focusing to a task persists.

**Comment by WveedeeTee** [comment] 2022-01-11 13:36
I have the same issue in version 7.9.2 It seems to have something to do with the size of the window, I can edit te title if I keep the window tiny.

**Comment by johannesjo** [comment] 2022-01-14 18:46
This seems to be caused by a chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1088262
https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/results/

**Comment by johannesjo** [comment] 2022-01-14 20:36
This should be fixed with the next release thanks to @marilouneko and everybody else sharing their console output. Thank you!

Please let me know if this issue persists regardless once the new version is released!

**Closed by johannesjo** 2022-01-14 20:36 UTC
Labels: bug, help wanted, external issue
