### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by Peter-Valachovic** [johannesjo/super-productivity#2849] opened 2023-11-13 09:02 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:1401304
    at m.project (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:1401326)
    at m._next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3736241)
    at m.next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3724370)
    at m._next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3724596)
    at m.next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3724370)
    at m._next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3736339)
    at m.next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3724370)
    at m._next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3735752)
    at m.next (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:3724370)
```

### Meta Info
META: SP7.13.2 Browser – sk-SK – Linux armv81 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Actions Before Error
```
1699865704044: [Task][Issue] Add Task 
1699865704055: [Persistence] Save to DB (2) 
1699865706356: [Layout] Hide AddTaskBar 
1699865707170: [Task] SetSelectedTask 
1699865707175: [Layout] Hide Notes 
1699865783643: [Task] Schedule 
1699865783654: [Persistence] Save to DB (2) 
1699865783655: [Task] Update Task 
1699865783660: [Persistence] Save to DB 
1699865798823: [Task] ReSchedule 
1699865798831: [Persistence] Save to DB (2) 
1699865808182: [Task] SetSelectedTask 
1699865808189: [Layout] Hide Notes 
1699866046041: [Layout] Toggle SideBar 
1699866055248: [Layout] Hide SideBar 
1699866055283: [WorkContext] Set Active Work Context 
1699866055519: [Task] SetSelectedTask 
1699866056347: [Layout] Hide SideBar 
1699866056457: [Bookmark] Load Bookmark State 
1699866056459: [Project] Load Project related Data Success 
1699866056460: [Improvement] Clear Hidden Improvements 
1699866056462: [Improvement] Delete multiple Improvements 
1699866068045: [SP_ALL] Load(import) all data 
1699866068051: [SP_ALL] All Data was loaded 
1699866068097: [WorkContext] Set Active Work Context 
1699866068127: [Task] SetSelectedTask 
1699866069238: [Bookmark] Load Bookmark State 
1699866069239: [Project] Load Project related Data Success 
1699866069241: [Improvement] Clear Hidden Improvements 
1699866069242: [Improvement] Delete multiple Improvements
```

**Comment by codeling** [comment] 2023-12-15 12:03
Duplicate of https://github.com/johannesjo/super-productivity/issues/2793 .

**Closed** 2024-03-29 09:45 UTC
