### ISSUE TITLE
Error: Uncaught (in promise): Error: No correct localLastSync given null

### ISSUE THREAD

**Issue by mohamedhagag** [johannesjo/super-productivity#878] opened 2021-02-07 23:05 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:292:12)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581546)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///tmp/.mount_superPEzG21T/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

### Meta Info
META: SP6.4.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1612738684326: [Layout] Hide SideBar 
1612738692770: [Project] Update Project Order 
1612738692771: [Persistence] Save to DB 
1612738694619: [Layout] Toggle SideBar 
1612738698269: [Project] Update Project Order 
1612738698270: [Persistence] Save to DB 
1612738699695: [Project] Update Project Order 
1612738699696: [Persistence] Save to DB 
1612738701852: [Project] Update Project Order 
1612738701853: [Persistence] Save to DB 
1612738708517: [Project] Update Project Order 
1612738708536: [Persistence] Save to DB 
1612738711337: [Layout] Hide SideBar 
1612738722580: [Layout] Toggle SideBar 
1612738725605: [Layout] Hide SideBar 
1612738726321: [Layout] Hide SideBar 
1612738782510: [Global Config] Update Global Config Section 
1612738782520: [Persistence] Save to DB 
1612738907161: [Global Config] Update Global Config Section 
1612738907177: [Persistence] Save to DB 
1612738947555: [Global Config] Update Global Config Section 
1612738947564: [Persistence] Save to DB 
1612738962381: [Global Config] Update Global Config Section 
1612738962384: [Persistence] Save to DB 
1612738986127: [Global Config] Update Global Config Section 
1612738986140: [Persistence] Save to DB 
1612739057495: [Global Config] Update Global Config Section 
1612739057506: [Persistence] Save to DB 
1612739061959: [Global Config] Update Global Config Section 
1612739061965: [Persistence] Save to DB
```

**Comment by RodSanches** [comment] 2021-02-08 08:41
This error occurred while trying to sync the app with Google Drive. I hope this helps.

Error: Uncaught (in promise): Error: No correct localLastSync given null Error: No correct localLastSync given null at e. (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588239) at Generator.next () at file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581546 at new C (file:///opt/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831) at ED (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291) at e._setLocalRevAndLastSync (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121) at e. (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3587258) at Generator.next () at a (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348) at l.invoke (file:///opt/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)


! Please copy & report !

Error: Uncaught (in promise): Error: No correct localLastSync given null Error: No correct localLastSync given null at e. (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588239) at Generator.next () at file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581546 at new C (file:///opt/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831) at ED (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291) at e._setLocalRevAndLastSync (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121) at e. (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3587258) at Generator.next () at a (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348) at l.invoke (file:///opt/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:292:12)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581546)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)


META: SP6.4.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36


Reload App

**Comment by johannesjo** [comment] 2021-02-08 08:49
Thanks for reporting this! Looks like quite a lot of people are affected. I am closing this as duplicate of #720

**Closed by johannesjo** 2021-02-08 08:49 UTC

**Comment by RodSanches** [comment] 2021-02-08 08:52
Hi Johannes,
The issue seems to resolve itself once the app is reloaded.
I hope this helps.
Kind regards,
Rodrigo Sanches
