### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by smendozabarrera** [johannesjo/super-productivity#397] opened 2020-06-11 15:28 UTC
META: SP5.3.4 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.4 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Steps to Reproduce

1. Update to 5.3.4 version
2. Recovered from Google Drive backup
3. Attempt to sort the projects from Manage projects
4. Error jump

### Stacktrace
```
t.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:459:23)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1540329)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1540434)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1539370)
new t (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:913:33)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1539115)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1551191)
t.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:449:37)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1540329)
Ur (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.996e14580f3159e7b2c4.js:1:1540434)
```

**Comment by johannesjo** [comment] 2020-06-11 16:16
Thanks for reporting. This is a duplicate of #391. A fix should be out very soon.

**Closed by johannesjo** 2020-06-11 16:16 UTC
