### ISSUE TITLE
[Feature] Add a "due date" option

### ISSUE THREAD

**Issue by budinero** [johannesjo/super-productivity#726] opened 2020-12-07 16:06 UTC
It would be interesting to have the possibility to select select the due date in some task. It is different to "Schedule task": "Due date" is the date when the task must be finished, while "Schedule task" seems more appropriate to define the beginning of a task. 

A calendar to show tasks with scheduled and due dates will be interesting to.

**Comment by johannesjo** [comment] 2020-12-07 16:10
Thanks for opening this up. Looks like a duplicate of #405 to me.

**Closed by johannesjo** 2020-12-07 16:10 UTC

**Comment by budinero** [comment] 2020-12-07 18:19
Thanks, did not find it in a quick search. Upvoted.
