### ISSUE TITLE
Error: Project Z5HHhcbpp not found

### ISSUE THREAD

**Issue by SloppyJalopy95** [johannesjo/super-productivity#526] opened 2020-09-10 21:10 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
webpack:///src/app/features/project/store/project.reducer.ts:76:12
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)
```

### Meta Info
META: SP5.6.5 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1599772189957: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772190955: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772191956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772192956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772193956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772194956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772195956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772196956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772197956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772198956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772199956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772200956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772201956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772202957: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772203955: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772204956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772205956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772206957: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772207955: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772208955: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772209956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772210956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772211956: [SimpleCounter] Increase SimpleCounter Counter Today 
1599772212182: [Layout] Toggle AddTaskBar 
1599772212955: [SimpleCounter] Increase SimpleCounter Counter Today
```

**Comment by johannesjo** [comment] 2020-09-11 14:20
Duplicate of #525

**Closed by johannesjo** 2020-09-11 14:20 UTC
