### ISSUE TITLE
Crash: Error: Uncaught (in promise): UnknownError: Internal error opening backing store for indexedDB.open.

### ISSUE THREAD

**Issue by cristianharangus** [johannesjo/super-productivity#375] opened 2020-05-20 12:48 UTC
### Your Environment

* Version used:  snap 5.1.4 rev. number 624 latest/edge 
* Operating System and version: kubuntu 20.04
* Desktop Environment: kde plasma 5.18.4 
* Browser Name and version: snap version 

### Current Behavior

Permanent crash. Well, didn't try to reboot my computer yet.  "Fixed" after reboot.

### Steps to Reproduce (for bugs)

1. I tried to set away time to a task. 

### Error Log (Desktop only)

Error: Uncaught (in promise): UnknownError: Internal error opening backing store for indexedDB.open.
resolvePromise (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
resolvePromise (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:784:21)
apply (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:894:21)
t.invokeTask (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28273:33)
t.invokeTask (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
drainMicroTaskQueue (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:601:39)
e.invoke (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:507:25)
p (file:///snap/superproductivity/623/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
META: SP5.1.4 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.1.4 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36

**Comment by johannesjo** [comment] 2020-05-20 13:26
Thank you very much for reporting! This crashed your computer completely?

**Comment by cristianharangus** [comment] 2020-05-21 06:40
Hello. It didn't crash my computer, only the app itself. I couldn't use it until the computer restart.

**Comment by johannesjo** [comment] 2020-05-21 10:46
I was unable to reproduce the issue and also didn't find an obvious fix for this after an extended research. I updated electron however as there are several issues fixed with 8.3.0 which might be related. I also improved error handling in case this occurs again.

I leave this open for now. Please let me know if the error occurs again.

**Comment by johannesjo** [comment] 2020-05-28 11:38
I just came across this myself. My problem was running two instances of the app, which caused the database access to fail. This should not be possible any more following the next release.

**Comment by cristianharangus** [comment] 2020-06-05 12:24
It may be that the app crashed for a different reason, and I was trying to just reopen it when this error occurred. So yeah, basically two instances of the app causing db access to fail. Most likely this was my problem too.

**Comment by johannesjo** [comment] 2020-09-26 21:10
May I ask if you encountered this or a similar issue again? I am asking because I had the feeling that this might have gotten better with the most recent electron version (introduced with Super Productivity 5.6.5) as nobody has reported a similar issue after that.

**Comment by johannesjo** [comment] 2020-10-18 20:41
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!

**Closed by johannesjo** 2020-10-18 20:41 UTC
Labels: bug, db, help wanted
