### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by SamTheDude** [johannesjo/super-productivity#1473] opened 2021-08-28 20:55 UTC
### Steps to Reproduce
1. App running in the background on Ubuntu 21.04 tracking time on a task.
2. Switched to it using the GNOME task view.
3. Had to kill the whole thing using xkill as the error repeated after reloading the app. Performing a reboot after I send this, will update with an edit if that fixes it.

Was playing with docker and rvm at the same time? No idea if that helps? 
Honestly I don't quite know what caused this, possibly something else I did in the background messing with PATH variables but I wouldn't have guessed so. 
Also had Joplin, VSCode, Discord, Steam, Firefox and Thunderbird open. 

Gimme a ping if you want any more information about the desktop setup

### Stacktrace
```
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at sm.<anonymous> (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1541340)
    at Generator.throw (<anonymous>)
    at a (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1540569)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:139916)
    at Z (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15036
    at a (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1818798)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:139916)
```

### Meta Info
META: SP7.5.1 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.1 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1630183367253: [Task] Add time spent 
1630183367254: [Project] Update Work End 
1630183367257: [Tag] Update Work End for Tag 
1630183367259: [Persistence] Save to DB 
1630183367259: [Persistence] Save to DB 
1630183367259: [Persistence] Save to DB 
1630183368253: [Task] Add time spent 
1630183368254: [Project] Update Work End 
1630183368256: [Tag] Update Work End for Tag 
1630183368259: [Persistence] Save to DB 
1630183368259: [Persistence] Save to DB 
1630183368259: [Persistence] Save to DB 
1630183369253: [Task] Add time spent 
1630183369254: [Project] Update Work End 
1630183369256: [Tag] Update Work End for Tag 
1630183369258: [Persistence] Save to DB 
1630183369258: [Persistence] Save to DB 
1630183369258: [Persistence] Save to DB 
1630183370253: [Task] Add time spent 
1630183370254: [Project] Update Work End 
1630183370257: [Tag] Update Work End for Tag 
1630183370259: [Persistence] Save to DB 
1630183370259: [Persistence] Save to DB 
1630183370259: [Persistence] Save to DB 
1630183378375: [Task] Add time spent 
1630183378376: [Project] Update Work End 
1630183378378: [Tag] Update Work End for Tag 
1630183378381: [Persistence] Save to DB 
1630183378381: [Persistence] Save to DB 
1630183378381: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-08-29 10:09
Hi there! Thanks for reporting this. Looks like a duplicate of #398 to me.

**Closed** 2021-08-29 10:10 UTC
