### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by fillswim** [johannesjo/super-productivity#1790] opened 2022-01-02 12:41 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Nd._tapNext (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:3703488)
    at Nd._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1321919)
    at Nd.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1082266)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1102584)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1082266)
    at m._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1093643)
    at m.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1082266)
    at se.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1080013)
    at _._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:3855105)
    at __tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.9.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.e1d7389cff44d05b.js:1:1084080)
```

### Meta Info
META: SP7.9.1 Electron – ru – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.9.1 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1641122302678: [Tag] Update Work End for Tag 
1641122302830: [Persistence] Save to DB (2) 
1641122352342: [Task] Add time spent 
1641122352347: [Tag] Update Work End for Tag 
1641122352358: [Persistence] Save to DB (2) 
1641122412326: [Task] Add time spent 
1641122412329: [Tag] Update Work End for Tag 
1641122412354: [Persistence] Save to DB (2) 
1641122472351: [Task] Add time spent 
1641122472353: [Tag] Update Work End for Tag 
1641122472372: [Persistence] Save to DB (2) 
1641122532317: [Task] Add time spent 
1641122532319: [Tag] Update Work End for Tag 
1641122532328: [Persistence] Save to DB (2) 
1641122592317: [Task] Add time spent 
1641122592319: [Tag] Update Work End for Tag 
1641122592333: [Persistence] Save to DB (2) 
1641122592338: [Pomodoro] Finish Pomodoro Session 
1641122592365: [Task] UnsetCurrentTask 
1641122892355: [Pomodoro] Pause Pomodoro 
1641122951621: [Idle] Trigger Idle 
1641122951624: [Idle] Set idle time 
1641122951624: [Idle] Open dialog 
1641127265620: [Idle] Set idle time (860) 
1641127265639: [Pomodoro] Finish Pomodoro Session 
1641127265640: [Task] Toggle start 
1641127265642: [Persistence] Save to DB 
1641127265643: [Task] SetCurrentTask 
1641127265648: [Pomodoro] Start Pomodoro 
1641127265791: [Idle] Dialog result
```

**Comment by johannesjo** [comment] 2022-01-02 15:57
Thanks for opening this up. Looks like a duplicate of  #1779

**Closed by johannesjo** 2022-01-02 15:57 UTC
