### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by julandrod** [johannesjo/super-productivity#1386] opened 2021-07-13 19:29 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1275/resources/app.asar/dist/main.82bd44998b7599df3d30.js:1:2346469)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28591:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28578:32)
```

### Meta Info
META: SP7.2.1 Electron – es-419 – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.2.1 Chrome/91.0.4472.106 Electron/13.1.4 Safari/537.36

### Actions Before Error
```
1626204459621: [Task] Add time spent 
1626204459626: [Project] Update Work End 
1626204459638: [Tag] Update Work End for Tag 
1626204459646: [Persistence] Save to DB 
1626204459648: [Persistence] Save to DB 
1626204459649: [Persistence] Save to DB 
1626204460621: [Task] Add time spent 
1626204460626: [Project] Update Work End 
1626204460637: [Tag] Update Work End for Tag 
1626204460647: [Persistence] Save to DB 
1626204460649: [Persistence] Save to DB 
1626204460652: [Persistence] Save to DB 
1626204461621: [Task] Add time spent 
1626204461626: [Project] Update Work End 
1626204461636: [Tag] Update Work End for Tag 
1626204461645: [Persistence] Save to DB 
1626204461646: [Persistence] Save to DB 
1626204461648: [Persistence] Save to DB 
1626204462622: [Task] Add time spent 
1626204462625: [Project] Update Work End 
1626204462636: [Tag] Update Work End for Tag 
1626204462644: [Persistence] Save to DB 
1626204462646: [Persistence] Save to DB 
1626204462647: [Persistence] Save to DB 
1626204465638: [Task] Add time spent 
1626204465646: [Project] Update Work End 
1626204465657: [Tag] Update Work End for Tag 
1626204465684: [Persistence] Save to DB 
1626204465686: [Persistence] Save to DB 
1626204465688: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-07-14 18:24
Looks like a duplicate of #398. Hopefully the next electron version fixes this.

**Closed by johannesjo** 2021-07-14 18:24 UTC
