### ISSUE TITLE
[Feature request] GitLab Integration 

### ISSUE THREAD

**Issue by tobiasgraeber** [johannesjo/super-productivity#178] opened 2019-06-08 22:52 UTC
Any plans to add a GitLab Integration to import of Tickets (?) and maybe also sync of ticket Time/Estimates - primary for the self hosted GitLab instances (not just gitlab.com)

Nice work! Keep going :)!

**Comment by endorama** [comment] 2019-06-10 08:27
Feels a duplicate of #156 :)

**Comment by johannesjo** [comment] 2019-06-10 15:24
Closing this in favor of #156 thanks @endorama and thanks for the suggestion @tobiasgraeber . The feature will probably come sooner or later, but it's not on top of my to do list to be honest.

**Closed by johannesjo** 2019-06-10 15:24 UTC
