### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by Melaineg** [johannesjo/super-productivity#3271] opened 2024-07-19 12:34 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Electron – fr – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'then')
    at show (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:186:5567)
    at o.when.show (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:48125)
    at file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:2781
    at Array.forEach (<anonymous>)
    at iM.trigger (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:2723)
    at iM._show (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:40513)
    at iM.show (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:38567)
    at j7.show (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:45752)
    at j7.next (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:45278)
    at e.next (file:///C:/Users/melai/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-AKZA6QGV.js:198:47765)
```

### Actions Before Error
```
1721392251165: [Task] Move tasks to other project 
1721392251166: [Persistence] Save to DB (2) 
1721392253053: [Layout] Hide AddTaskBar 
1721392255509: [Task] SetCurrentTask 
1721392255828: [Task] Add time spent 
1721392255830: [Project] Update Work End 
1721392255830: [Tag] Update Work End for Tag 
1721392255835: [Persistence] Save to DB (3) 
1721392256828: [Task] Add time spent 
1721392256830: [Project] Update Work End 
1721392256831: [Tag] Update Work End for Tag 
1721392256832: [Persistence] Save to DB (3) 
1721392257827: [Task] Add time spent 
1721392257828: [Project] Update Work End 
1721392257828: [Tag] Update Work End for Tag 
1721392257828: [Persistence] Save to DB (3) 
1721392258828: [Task] Add time spent 
1721392258829: [Project] Update Work End 
1721392258829: [Tag] Update Work End for Tag 
1721392258830: [Persistence] Save to DB (3) 
1721392259828: [Task] Add time spent 
1721392259829: [Project] Update Work End 
1721392259832: [Tag] Update Work End for Tag 
1721392259834: [Persistence] Save to DB (3) 
1721392260361: [Task] UnsetCurrentTask 
1721392267329: [Layout] Toggle SideBar 
1721392301509: [Layout] Hide SideBar (2) 
1721392324418: [Layout] Toggle SideBar 
1721392327173: [Layout] Hide SideBar (2)
```

**Comment by johannesjo** [comment] 2024-07-19 21:19
Duplicate of #3270

**Closed by johannesjo** 2024-07-19 21:19 UTC
