### ISSUE TITLE
"You do not have permission to access this document", cannot use Android app

### ISSUE THREAD

**Issue by pigeonwithalilhat** [johannesjo/super-productivity#3265] opened 2024-07-18 09:46 UTC
I was using the app on android when this screen appeared: 

![Screenshot_2024-07-18-11-32-22-681_com superproductivity superproductivity](https://github.com/user-attachments/assets/517c6f86-daa7-4e1e-9f36-2c266050ee06)

I cant click anything and cant use the app at all. This keeps happening after uninstalling and installing again.

- Version used: newest one thats on google play
- Operating System and version: Android 10 QP1A.190711.020

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by MayhemKarma** [comment] 2024-07-18 11:12
I believe it is the same issue not only for android, coz I have the same error in the web-app:
![image](https://github.com/user-attachments/assets/46ca954c-5c54-4938-8a6c-bdf5a5349bfa)

**Comment by johannesjo** [comment] 2024-07-19 21:26
This should hopefully be fixed now? Please try restarting the app.

**Comment by pigeonwithalilhat** [comment] 2024-07-20 09:06
It works again!

**Comment by MayhemKarma** [comment] 2024-07-20 11:14
I can confirm - the issue is solved, thanks!

**Closed** 2024-07-22 06:46 UTC
Labels: bug
