### ISSUE TITLE
TypeError: Cannot set property 'boundary' of undefined

### ISSUE THREAD

**Issue by venkat-iyer13** [johannesjo/super-productivity#486] opened 2020-08-07 17:03 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
MultiPartBuilder (webpack:///src/app/features/google/util/multi-part-builder.ts:7:18)
MultiPartBuilder (webpack:///src/app/features/google/google-api.service.ts:249:32)
saveFile$ (webpack:///src/app/features/google/store/google-drive-sync.effects.ts:180:29)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/mergeMap.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/mergeMap.js:51:17)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
this.project.call (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:41:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
this.destination.error (webpack:///node_modules/rxjs/_esm5/internal/operators/filter.js:38:29)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
```

### Meta Info
META: SP5.5.2 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.2 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment] 2020-08-07 17:21
Duplicate of #474

**Closed by johannesjo** 2020-08-07 17:21 UTC
