### ISSUE TITLE
Add Flatpak Support

### ISSUE THREAD

**Issue by wada3n** [johannesjo/super-productivity#634] opened 2020-10-30 11:53 UTC
Hello.
Firstly, this app is pretty amazing.
Everything in it is impressive, very practical, useful and perfect.
I would like to thank you for this distinguished work.
I just have a request if you can add flatpak support.

**Comment by johannesjo** [comment] 2020-10-30 14:46
Thanks for opening this up! However, I am closing this as duplicate of #25 . Please upvote that one!

**Closed by johannesjo** 2020-10-30 14:46 UTC
Labels: enhancement
