### ISSUE TITLE
Crash on changing project

### ISSUE THREAD

**Issue by jeensg** [johannesjo/super-productivity#238] opened 2019-10-11 16:00 UTC
### Your Environment
* Version used: deb 2.13.0
* Operating System and version: Ubuntu 19.04
* Desktop Environment: xfce

### Expected Behavior
When I change a project, it should appear, although it is empty.

### Current Behavior
When I change to an empty project, App crashes with TypeError.

### Steps to Reproduce (for bugs)
1. Start App
2. Change into empty project.

### Console Output
`TypeError: Cannot read property 'isEnabled' of null at file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1287197 at file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1442190 at memoized (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1441573) at oe (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1442575) at file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1442244 at memoized (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1441573) at t.project (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:1441195) at t._next (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:58263) at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:439647) at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.a94ca2a992e56e28f4a7.js:1:512371)`

### Error Log (Desktop only)
Included.
[log.log](https://github.com/johannesjo/super-productivity/files/3718539/log.log)

**Comment by johannesjo** [comment] 2019-10-11 16:25
Hey thanks for reporting. I am unable to reproduce the issue. Could you maybe reload the page page with an open console (Ctrl+Shift+i) and provide me with the log there? Also please check if you if you really have installed 2.13.0. You can look it up by switching to the global settings (settings button in the bottom left of the menu and scrolling down  to Super Productivity <some version nr>.

**Comment by jeensg** [comment] 2019-10-11 17:19
Sure :-) Version is correct, even made a screenshot now.
If I'm creating a new project, it works, which is empty too.
About the emptiness I'm only ure about 1 project. It happens to exactly 2 of all of my list and I can't state if the second one was empty or not. At least all the others still work.
I added another screenshot of the error and here is the log of open console:
`Persistent store granted
global-error-handler.class.ts:11 TypeError: Cannot read property 'isEnabled' of null
    at project.reducer.ts:55
    at store.js.pre-build-optimizer.js:581
    at memoized (store.js.pre-build-optimizer.js:531)
    at oe (store.js.pre-build-optimizer.js:550)
    at store.js.pre-build-optimizer.js:584
    at memoized (store.js.pre-build-optimizer.js:531)
    at t.project (store.js.pre-build-optimizer.js:478)
    at t._next (map.js.pre-build-optimizer.js:35)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t.next (Subject.js.pre-build-optimizer.js:47)
global-error-handler.class.ts:77 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'isEnabled' of null
    at project.reducer.ts:55
    at store.js.pre-build-optimizer.js:581
    at memoized (store.js.pre-build-optimizer.js:531)
    at oe (store.js.pre-build-optimizer.js:550)
    at store.js.pre-build-optimizer.js:584
    at memoized (store.js.pre-build-optimizer.js:531)
    at t.project (store.js.pre-build-optimizer.js:478)
    at t._next (map.js.pre-build-optimizer.js:35)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t.next (Subject.js.pre-build-optimizer.js:47)
e.handleError @ global-error-handler.class.ts:77
(anonymous) @ effects.js.pre-build-optimizer.js:142
t.error @ catchError.js.pre-build-optimizer.js:34
t._error @ Subscriber.js.pre-build-optimizer.js:79
t.error @ Subscriber.js.pre-build-optimizer.js:59
t.notifyError @ OuterSubscriber.js.pre-build-optimizer.js:13
t._error @ InnerSubscriber.js.pre-build-optimizer.js:18
t.error @ Subscriber.js.pre-build-optimizer.js:59
t._error @ Subscriber.js.pre-build-optimizer.js:79
t.error @ Subscriber.js.pre-build-optimizer.js:59
t._next @ map.js.pre-build-optimizer.js:38
t.next @ Subscriber.js.pre-build-optimizer.js:53
t.next @ Subject.js.pre-build-optimizer.js:47
t.next @ BehaviorSubject.js.pre-build-optimizer.js:38
(anonymous) @ store.js.pre-build-optimizer.js:386
t.__tryOrUnsub @ Subscriber.js.pre-build-optimizer.js:192
t.next @ Subscriber.js.pre-build-optimizer.js:130
t._next @ Subscriber.js.pre-build-optimizer.js:76
t.next @ Subscriber.js.pre-build-optimizer.js:53
t._tryNext @ scan.js.pre-build-optimizer.js:67
t._next @ scan.js.pre-build-optimizer.js:54
t.next @ Subscriber.js.pre-build-optimizer.js:53
t._next @ withLatestFrom.js.pre-build-optimizer.js:66
t.next @ Subscriber.js.pre-build-optimizer.js:53
e.observe @ Notification.js.pre-build-optimizer.js:21
t.dispatch @ observeOn.js.pre-build-optimizer.js:40
t._execute @ AsyncAction.js.pre-build-optimizer.js:64
t.execute @ QueueAction.js.pre-build-optimizer.js:27
t.flush @ AsyncScheduler.js.pre-build-optimizer.js:43
t.schedule @ QueueAction.js.pre-build-optimizer.js:21
e.schedule @ Scheduler.js.pre-build-optimizer.js:13
t.schedule @ AsyncScheduler.js.pre-build-optimizer.js:31
t.scheduleMessage @ observeOn.js.pre-build-optimizer.js:45
t._next @ observeOn.js.pre-build-optimizer.js:48
t.next @ Subscriber.js.pre-build-optimizer.js:53
t.next @ Subject.js.pre-build-optimizer.js:47
t.next @ BehaviorSubject.js.pre-build-optimizer.js:38
t.next @ store.js.pre-build-optimizer.js:134
t.dispatch @ store.js.pre-build-optimizer.js:439
e.setCurrentId @ project.service.ts:323
e.switchProject @ side-nav.component.ts:50
(anonymous) @ side-nav.component.ngfactory.js.pre-build-optimizer.js:34
handleEvent @ core.js.pre-build-optimizer.js:29238
handleEvent @ core.js.pre-build-optimizer.js:29783
Kf @ core.js.pre-build-optimizer.js:19858
(anonymous) @ core.js.pre-build-optimizer.js:28447
(anonymous) @ platform-browser.js.pre-build-optimizer.js:1032
t.invokeTask @ zone.js.pre-build-optimizer.js:423
onInvokeTask @ core.js.pre-build-optimizer.js:26246
t.invokeTask @ zone.js.pre-build-optimizer.js:422
e.runTask @ zone.js.pre-build-optimizer.js:195
e.invokeTask @ zone.js.pre-build-optimizer.js:498
b @ zone.js.pre-build-optimizer.js:1693
m @ zone.js.pre-build-optimizer.js:1719
Show 24 more frames
global-error-handler.class.ts:11 TypeError: Cannot read property 'isEnabled' of null
    at project.reducer.ts:55
    at store.js.pre-build-optimizer.js:581
    at memoized (store.js.pre-build-optimizer.js:531)
    at oe (store.js.pre-build-optimizer.js:550)
    at store.js.pre-build-optimizer.js:584
    at memoized (store.js.pre-build-optimizer.js:531)
    at t.project (store.js.pre-build-optimizer.js:478)
    at t._next (map.js.pre-build-optimizer.js:35)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t.next (Subject.js.pre-build-optimizer.js:47)
global-error-handler.class.ts:77 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'isEnabled' of null
    at project.reducer.ts:55
    at store.js.pre-build-optimizer.js:581
    at memoized (store.js.pre-build-optimizer.js:531)
    at oe (store.js.pre-build-optimizer.js:550)
    at store.js.pre-build-optimizer.js:584
    at memoized (store.js.pre-build-optimizer.js:531)
    at t.project (store.js.pre-build-optimizer.js:478)
    at t._next (map.js.pre-build-optimizer.js:35)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t.next (Subject.js.pre-build-optimizer.js:47)
e.handleError @ global-error-handler.class.ts:77
next @ core.js.pre-build-optimizer.js:26758
o @ core.js.pre-build-optimizer.js:23734
t.__tryOrUnsub @ Subscriber.js.pre-build-optimizer.js:192
t.next @ Subscriber.js.pre-build-optimizer.js:130
t._next @ Subscriber.js.pre-build-optimizer.js:76
t.next @ Subscriber.js.pre-build-optimizer.js:53
t.next @ Subject.js.pre-build-optimizer.js:47
t.emit @ core.js.pre-build-optimizer.js:23718
(anonymous) @ core.js.pre-build-optimizer.js:26277
t.invoke @ zone.js.pre-build-optimizer.js:391
e.run @ zone.js.pre-build-optimizer.js:150
e.runOutsideAngular @ core.js.pre-build-optimizer.js:26214
onHandleError @ core.js.pre-build-optimizer.js:26277
t.handleError @ zone.js.pre-build-optimizer.js:395
e.runTask @ zone.js.pre-build-optimizer.js:198
e.invokeTask @ zone.js.pre-build-optimizer.js:498
invoke @ zone.js.pre-build-optimizer.js:487
n.args.<computed> @ zone.js.pre-build-optimizer.js:3070
setTimeout (async)
c @ zone.js.pre-build-optimizer.js:3091
t.scheduleTask @ zone.js.pre-build-optimizer.js:410
onScheduleTask @ zone.js.pre-build-optimizer.js:301
t.scheduleTask @ zone.js.pre-build-optimizer.js:404
e.scheduleTask @ zone.js.pre-build-optimizer.js:238
e.scheduleMacroTask @ zone.js.pre-build-optimizer.js:261
v @ zone.js.pre-build-optimizer.js:1194
(anonymous) @ zone.js.pre-build-optimizer.js:3106
A.i.<computed> @ zone.js.pre-build-optimizer.js:1518
i @ hostReportError.js.pre-build-optimizer.js:3
t.error @ Subscriber.js.pre-build-optimizer.js:164
t._error @ Subscriber.js.pre-build-optimizer.js:79
t.error @ Subscriber.js.pre-build-optimizer.js:59
t._error @ Subscriber.js.pre-build-optimizer.js:79
t.error @ Subscriber.js.pre-build-optimizer.js:59
t._error @ Subscriber.js.pre-build-optimizer.js:79
t.error @ Subscriber.js.pre-build-optimizer.js:59
e.observe @ Notification.js.pre-build-optimizer.js:23
t.dispatch @ observeOn.js.pre-build-optimizer.js:40
t._execute @ AsyncAction.js.pre-build-optimizer.js:64
t.execute @ QueueAction.js.pre-build-optimizer.js:27
t.flush @ AsyncScheduler.js.pre-build-optimizer.js:43
t.schedule @ QueueAction.js.pre-build-optimizer.js:21
e.schedule @ Scheduler.js.pre-build-optimizer.js:13
t.schedule @ AsyncScheduler.js.pre-build-optimizer.js:31
t.scheduleMessage @ observeOn.js.pre-build-optimizer.js:45
t._next @ observeOn.js.pre-build-optimizer.js:48
t.next @ Subscriber.js.pre-build-optimizer.js:53
t.next @ Subject.js.pre-build-optimizer.js:47
t.next @ BehaviorSubject.js.pre-build-optimizer.js:38
t.next @ store.js.pre-build-optimizer.js:134
t.dispatch @ store.js.pre-build-optimizer.js:439
e.setCurrentId @ project.service.ts:323
e.switchProject @ side-nav.component.ts:50
(anonymous) @ side-nav.component.ngfactory.js.pre-build-optimizer.js:34
handleEvent @ core.js.pre-build-optimizer.js:29238
handleEvent @ core.js.pre-build-optimizer.js:29783
Kf @ core.js.pre-build-optimizer.js:19858
(anonymous) @ core.js.pre-build-optimizer.js:28447
(anonymous) @ platform-browser.js.pre-build-optimizer.js:1032
t.invokeTask @ zone.js.pre-build-optimizer.js:423
onInvokeTask @ core.js.pre-build-optimizer.js:26246
t.invokeTask @ zone.js.pre-build-optimizer.js:422
e.runTask @ zone.js.pre-build-optimizer.js:195
e.invokeTask @ zone.js.pre-build-optimizer.js:498
b @ zone.js.pre-build-optimizer.js:1693
m @ zone.js.pre-build-optimizer.js:1719
Show 36 more frames
zone.js.pre-build-optimizer.js:199 Uncaught TypeError: Cannot read property 'isEnabled' of null
    at project.reducer.ts:55
    at store.js.pre-build-optimizer.js:581
    at memoized (store.js.pre-build-optimizer.js:531)
    at oe (store.js.pre-build-optimizer.js:550)
    at store.js.pre-build-optimizer.js:584
    at memoized (store.js.pre-build-optimizer.js:531)
    at t.project (store.js.pre-build-optimizer.js:478)
    at t._next (map.js.pre-build-optimizer.js:35)
    at t.next (Subscriber.js.pre-build-optimizer.js:53)
    at t.next (Subject.js.pre-build-optimizer.js:47)`

**Comment by jeensg** [comment] 2019-10-11 17:21
Sorry, missed to attach the files.
![Error](https://user-images.githubusercontent.com/24763877/66671441-a58ee180-ec64-11e9-9583-e688f5d697e3.png)
![2 13 0](https://user-images.githubusercontent.com/24763877/66671443-a6277800-ec64-11e9-8795-3976e6ffb19c.png)

**Comment by johannesjo** [comment] 2019-10-11 17:36
I think I found a fix. Thank you very much for your help!

**Comment by jeensg** [comment] 2019-10-11 17:39
Thank you even more :p

**Comment by johannesjo** [comment] 2019-10-11 17:41
I am closing this. Will make a new release shortly. Please let me know if the issue persists for you.

**Closed by johannesjo** 2019-10-11 17:41 UTC
Labels: bug

**Comment by jeensg** [comment] 2019-10-14 21:08
Hey, with 2.13.2 it's gone. Since the projects weren't empty at the end, you seem to have fixed another issue than I was thinking of :-D thanks anyway!
