### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by timdhoffmann** [johannesjo/super-productivity#1739] opened 2021-12-06 09:26 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638782687290: [Idle] Set idle time (5) 
1638782687469: [Idle] Trigger Idle 
1638782692294: [Idle] Set idle time (5) 
1638782692469: [Idle] Trigger Idle 
1638782697298: [Idle] Set idle time (5) 
1638782697470: [Idle] Trigger Idle 
1638782702304: [Idle] Set idle time (5) 
1638782702469: [Idle] Trigger Idle 
1638782707309: [Idle] Set idle time (5) 
1638782707470: [Idle] Trigger Idle 
1638782712313: [Idle] Set idle time (5) 
1638782712471: [Idle] Trigger Idle 
1638782717316: [Idle] Set idle time (5) 
1638782717471: [Idle] Trigger Idle 
1638782722321: [Idle] Set idle time (5) 
1638782722472: [Idle] Trigger Idle 
1638782727325: [Idle] Set idle time (5) 
1638782727472: [Idle] Trigger Idle 
1638782732331: [Idle] Set idle time (5) 
1638782732472: [Idle] Trigger Idle 
1638782737336: [Idle] Set idle time (5) 
1638782737472: [Idle] Trigger Idle 
1638782742341: [Idle] Set idle time (5) 
1638782742472: [Idle] Trigger Idle 
1638782743343: [Idle] Set idle time 
1638782744142: [Pomodoro] Finish Pomodoro Session 
1638782744143: [Task] Toggle start 
1638782744144: [Persistence] Save to DB 
1638782744144: [Task] SetCurrentTask 
1638782744146: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment] 2021-12-06 20:17
Thank you very much for reporting! Looks like a duplicate of #1684 

Would you maybe be willing to help debugging this?

**Closed by johannesjo** 2021-12-06 20:17 UTC
