### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by Kostasn2** [johannesjo/super-productivity#3290] opened 2024-07-24 08:41 UTC
### Steps to Reproduce

1. Increase or decrease the volume in settings

### Meta Info
META: SP9.0.5 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.5 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
isHandledError (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/src/app/core/error-handler/global-error-handler.class.ts:45:12)
RA (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-X2V3OSX7.js:1:1522)
invoke (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:157)
onInvoke (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15681:24)
invoke (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:45)
run (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:111:36)
zone.scheduleMicroTask(source, (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:2366:29)
invokeTask (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)
shouldBeIgnoredByZone (file:///C:/Users/KostasNtouros/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15670:24)
```

### Actions Before Error
```
1721810461835: [Global Config] Update Global Config Section 
1721810461849: [Persistence] Save to DB 
1721810462860: [Global Config] Update Global Config Section 
1721810462875: [Persistence] Save to DB 
1721810463478: [Global Config] Update Global Config Section 
1721810463493: [Persistence] Save to DB 
1721810466520: [Global Config] Update Global Config Section 
1721810466535: [Persistence] Save to DB 
1721810468477: [Global Config] Update Global Config Section 
1721810468493: [Persistence] Save to DB 
1721810473223: [Global Config] Update Global Config Section 
1721810473238: [Persistence] Save to DB 
1721810474394: [Global Config] Update Global Config Section 
1721810474408: [Persistence] Save to DB 
1721810475904: [Global Config] Update Global Config Section 
1721810475920: [Persistence] Save to DB 
1721810477113: [Global Config] Update Global Config Section 
1721810477127: [Persistence] Save to DB 
1721810478140: [Global Config] Update Global Config Section 
1721810478157: [Persistence] Save to DB 
1721810479847: [Global Config] Update Global Config Section 
1721810479862: [Persistence] Save to DB 
1721810481716: [Global Config] Update Global Config Section 
1721810481731: [Persistence] Save to DB 
1721810483400: [Global Config] Update Global Config Section 
1721810483401: [Persistence] Save to DB 
1721810483473: [Global Config] Update Global Config Section 
1721810483487: [Persistence] Save to DB 
1721810492356: [Global Config] Update Global Config Section 
1721810492376: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2024-07-26 05:50
Duplicate of #3290

**Closed by johannesjo** 2024-07-26 05:50 UTC
