### ISSUE TITLE
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.

### ISSUE THREAD

**Issue by TimoStolz** [johannesjo/super-productivity#1289] opened 2021-06-10 10:54 UTC
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.Error: UnknownError: Internal error opening backing store for indexedDB.open.    at t. (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:2686573)    at Generator.throw ()    at o (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:2684500)    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)    at i.run (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)    at file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758    at l.invokeTask (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190)    at Object.onInvokeTask (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1902903)

### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
alert (webpack:///src/app/core/persistence/database.service.ts:109:12)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:2684500)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:487:20)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
```

### Meta Info
META: SP6.5.2 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1623317667878: [Task] Add time spent 
1623317667897: [Project] Update Work End 
1623317667902: [Tag] Update Work End for Tag 
1623317667931: [Persistence] Save to DB 
1623317667938: [Persistence] Save to DB 
1623317667943: [Persistence] Save to DB 
1623317669412: [Task] Add time spent 
1623317669425: [Project] Update Work End 
1623317669444: [Tag] Update Work End for Tag 
1623317669479: [Persistence] Save to DB 
1623317669486: [Persistence] Save to DB 
1623317669491: [Persistence] Save to DB 
1623317669881: [Task] Add time spent 
1623317669912: [Project] Update Work End 
1623317669923: [Tag] Update Work End for Tag 
1623317669949: [Persistence] Save to DB 
1623317669954: [Persistence] Save to DB 
1623317669960: [Persistence] Save to DB 
1623317672816: [Task] Add time spent 
1623317672826: [Project] Update Work End 
1623317672832: [Tag] Update Work End for Tag 
1623317672862: [Persistence] Save to DB 
1623317672867: [Persistence] Save to DB 
1623317672877: [Persistence] Save to DB 
1623317673057: [Task] Add time spent 
1623317673078: [Project] Update Work End 
1623317673092: [Tag] Update Work End for Tag 
1623317673132: [Persistence] Save to DB 
1623317673139: [Persistence] Save to DB 
1623317673149: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-10 17:11
Duplicate of #419

**Closed by johannesjo** 2021-06-10 17:11 UTC
