### ISSUE TITLE
"TypeError: Cannot read property 'tagIds' of undefined" when clicking Finish Day button

### ISSUE THREAD

**Issue by mjgwood** [johannesjo/super-productivity#481] opened 2020-08-06 11:56 UTC
This happens whenever I click the Finish Day button. I also noticed that there is nothing under the Tags section in the sidebar. I've never used tags before so I don't know how long that has been the case, but it is completely empty when I click the arrow to expand it.

### Your Environment
- Version used: 5.5.2 (snap)
- Operating System and version: Ubuntu 18.04.4
- Desktop Environment: GNOME

### Steps to Reproduce
1. Click 'Finish Day'
2. Presented with error message 'TypeError: Cannot read property 'tagIds' of undefined'
3. Click 'Reload App' button
4. Presented with same error again

### Error Log (Desktop only)
```
[2020-08-06 19:38:29.159] [error] Frontend Error Stack: tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
[2020-08-06 19:38:34.873] [error] Frontend Error: TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668) TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668)
[2020-08-06 19:38:35.878] [error] Frontend Error Stack: tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
[2020-08-06 19:40:02.760] [error] Frontend Error: TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668) TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668)
[2020-08-06 19:40:03.749] [error] Frontend Error Stack: tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
[2020-08-06 19:42:44.859] [error] Frontend Error: TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668) TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668)
[2020-08-06 19:42:45.824] [error] Frontend Error Stack: tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
[2020-08-06 19:44:48.187] [error] Frontend Error: TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668) TypeError: Cannot read property 'tagIds' of undefined
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745124
    at Array.filter (<anonymous>)
    at SS (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3745043)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749170
    at t.<anonymous> (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3749296)
    at file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716
    at Object.next (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
    at o (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
    at t.invoke (file:///snap/superproductivity/734/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:476668)
[2020-08-06 19:44:49.113] [error] Frontend Error Stack: tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
```

### Console Output
```
main.8e59c22….js:1 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'tagIds' of undefined
    at main.8e59c22….js:1
    at Array.filter (<anonymous>)
    at SS (main.8e59c22….js:1)
    at main.8e59c22….js:1
    at t.<anonymous> (main.8e59c22….js:1)
    at main.8e59c22….js:1
    at Object.next (main.8e59c22….js:1)
    at o (main.8e59c22….js:1)
    at t.invoke (polyfills.aebe8ec….js:1)
    at Object.onInvoke (main.8e59c22….js:1)
main.8e59c22….js:1 Last actions before error: 
(25) ["1596714073396: [WorkContext] Set Active Work Context", "1596714073413: [Task] SetSelectedTask", "1596714073500: [Note] Load Note State", "1596714073529: [Bookmark] Load Bookmark State", "1596714073538: [Metric] Load Metric State", "1596714073546: [Improvement] Load Improvement State", "1596714073549: [Obstruction] Load Obstruction State", "1596714073550: [Project] Load Project related Data Success", "1596714073550: [Improvement] Clear Hidden Improvements", "1596714073551: [Improvement] Delete multiple Improvements", "1596714076256: [Task] SetSelectedTask", "1596714084777: [Task] UnsetCurrentTask", "1596714084778: [SimpleCounter] Turn off all simple counters", "1596714086990: [SP_ALL] Load(import) all data", "1596714086992: [SP_ALL] All Data was loaded", "1596714086995: [WorkContext] Set Active Work Context", "1596714087005: [Task] SetSelectedTask", "1596714090195: [Task] SetSelectedTask", "1596714093682: [Task] SetSelectedTask", "1596714164718: [Task] SetSelectedTask", "1596714287638: [SP_ALL] Load(import) all data", "1596714287640: [SP_ALL] All Data was loaded", "1596714287646: [WorkContext] Set Active Work Context", "1596714287656: [Task] SetSelectedTask", "1596714287967: [Task] SetSelectedTask"]
polyfills.aebe8ec….js:1 Uncaught Error: TypeError: Cannot read property 'tagIds' of undefined
    at t.handleError (main.8e59c22….js:1)
    at Object.next (main.8e59c22….js:1)
    at e.o [as _next] (main.8e59c22….js:1)
    at e.__tryOrUnsub (main.8e59c22….js:1)
    at e.next (main.8e59c22….js:1)
    at e._next (main.8e59c22….js:1)
    at e.next (main.8e59c22….js:1)
    at e.next (main.8e59c22….js:1)
    at e.emit (main.8e59c22….js:1)
    at main.8e59c22….js:1
```

### Stacktrace
```
tagIds (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:47:45)
filter (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:43:112)
_filterIdsForTag (webpack:///src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:16:6)
workContext (webpack:///src/app/features/worklog/worklog.service.ts:150:88)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748716)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3748821)
Ur (file:///snap/superproductivity/734/resources/app.asar/dist/main.8e59c225469dff8e7366.js:1:3751723)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
```

### Meta Info
META: SP5.5.4 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.4 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1596714070853: [Improvement] Load Improvement State 
1596714070855: [Obstruction] Load Obstruction State 
1596714070855: [Project] Load Project related Data Success 
1596714070856: [Improvement] Clear Hidden Improvements 
1596714070856: [Improvement] Delete multiple Improvements 
1596714073396: [WorkContext] Set Active Work Context 
1596714073413: [Task] SetSelectedTask 
1596714073500: [Note] Load Note State 
1596714073529: [Bookmark] Load Bookmark State 
1596714073538: [Metric] Load Metric State 
1596714073546: [Improvement] Load Improvement State 
1596714073549: [Obstruction] Load Obstruction State 
1596714073550: [Project] Load Project related Data Success 
1596714073550: [Improvement] Clear Hidden Improvements 
1596714073551: [Improvement] Delete multiple Improvements 
1596714076256: [Task] SetSelectedTask 
1596714084777: [Task] UnsetCurrentTask 
1596714084778: [SimpleCounter] Turn off all simple counters 
1596714086990: [SP_ALL] Load(import) all data 
1596714086992: [SP_ALL] All Data was loaded 
1596714086995: [WorkContext] Set Active Work Context 
1596714087005: [Task] SetSelectedTask 
1596714090195: [Task] SetSelectedTask 
1596714093682: [Task] SetSelectedTask 
1596714164718: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment] 2020-08-06 21:15
Thank you very much for reporting! I look into it!

**Comment by johannesjo** [comment] 2020-08-07 14:44
I don't know if it is possible for us to reconstruct what happened to cause this (though it would be super cool if we could) but the error you are encountered is triggered because there is subtask whose parent seems to be missing. Do you by any chance have a suspicion of what might have caused this?

**Comment by johannesjo** [comment] 2020-08-07 14:46
If you send me a copy of your data (to contact@super-productivity.com) I can have a deeper look and also try to fix your data.

**Comment by mjgwood** [comment] 2020-08-08 07:43
Unfortunately I have no idea what task could be responsible for the error. I had a comb through my data to see if I could find anything that looked abnormal but nothing stood out to me. I'm sure you have a better idea of what to look for though!

Today when I clicked the Finish Day button I actually got a different error message: `TypeError: Cannot read property 'projectId' of undefined`

I've emailed my exported data to you now. Thanks very much for your time.

**Comment by johannesjo** [comment] 2020-08-08 21:26
Maybe it's better to keep the discussion here. Just wanted to reference your data in private :)

>  I'm not really sure what 'archived' means in this app. Since I don't think I have the ability to archive tasks I assume it means deleted? 

An archived task is a (parent - subtasks are archived together with their parent) task that was marked as done and was then archived when you click "finish day" and then "save and go home". You can identify an archived (parent) task by the little restore icon next to it on the "worklog" page. You can access the worklog by opening the menu, then hovering the project, whose backlog you want to access, clicking the three little dots, and then selecting "worklog".

Tasks that are archived are saved differently and separately, so your daily list can remain lean and fast, while also having access to the full history. Something went wrong with your data as some sub-tasks remained in the main task list, while their parent and some others went into the archive. Normally a parent task should always move together with its subtasks, but for some reason, that is not the case with your data.

**Comment by mjgwood** [comment] 2020-08-09 05:46
Ah okay I think I understand now. The error initially showed up some time ago so I haven't actually been making use of the 'Finish Day' and 'Save and Go Home' features.

> some sub-tasks remained in the main task list, while their parent and some others went into the archive.

I can currently still see the parent task `id: -5NSAVqsr` and the one subtask `id: r0E6Y5US1` in my project view as 'completed', which I don't think should be the case if the parent was archived? Neither of these appear under `taskArchive` in my data file. The other 2 subtasks are archived and I cannot see them, but I can't currently view any of the 'Worklog' screens because I get this error `TypeError: Cannot read property 'projectId' of undefined`.

Is the Worklog screen supposed to just show the archived tasks for that particular project? If that's the case I find it strange that I get the error no matter which projects Worklog screen I try to access.

What happens to subtasks that are completed when you click Finish Day? Would they not be archived if the parent task is not also completed? If not, then maybe I did restore the parent task at some point.. I don't currently have any active tasks for that project so I could just remove all the project and task data if that will fix the issue.

**Comment by johannesjo** [comment] 2020-08-09 14:13
> Is the Worklog screen supposed to just show the archived tasks for that particular project? If that's the case I find it strange that I get the error no matter which projects Worklog screen I try to access.

This is because the algorithm is checking all the archived tasks for their projectId or their parents projected.

 > What happens to subtasks that are completed when you click Finish Day? Would they not be archived if the parent task is not also completed? If not, then maybe I did restore the parent task at some point.. I don't currently have any active tasks for that project so I could just remove all the project and task data if that will fix the issue.

Normally subtasks are archived and also unarchived together with their parent task. I really don't know why that didn't work in your case.

I send you a fixed copy of your data, which should resolve the issue for now.

Please let me know if this or something similar pops up again. I'd really like to get to the bottom of this, but it also just might be some rare hiccup, caused by circumstances, that are not even possible anymore with the newest version of the app.

**Comment by mjgwood** [comment] 2020-08-10 01:05
That makes sense, I thought it must be something like that.

The new data that you sent is working perfectly, thank you so much! I didn't realise how many features I was actually missing out on!

> it also just might be some rare hiccup, caused by circumstances, that are not even possible anymore with the newest version of the app

I think this may be the case since the version I would have been using at the time was probably 5.3.5 or 5.4.0 now that I look back at the dates. I will definitely create an issue if it happens again, but let's hope it's something that can't happen anymore. Thanks again for all your hard work and your fast action on this issue!

**Comment by johannesjo** [comment] 2020-08-10 11:36
I am closing this. Please let me know if you encounter this or any other issue?

**Closed by johannesjo** 2020-08-10 11:36 UTC
Labels: bug
