### ISSUE TITLE
new version crashes on mac arm64

### ISSUE THREAD

**Issue by devashishRaj** [johannesjo/super-productivity#2923] opened 2023-12-17 13:30 UTC
### Steps to Reproduce

1. Install on mac via homebrew or dmg file
2. Open

macOS: 14.2-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false

```
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'    at statSync (node:fs:1615:3)    at t.statSync (node:electron/js2c/asar_bundle:2:4557)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40    at Array.map ()    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71    at new Promise ()
[ANONYMIZED-super-productivity-crash-user-data-export.json](https://github.com/johannesjo/super-productivity/files/13696254/ANONYMIZED-super-productivity-crash-user-data-export.json)

```

### Stacktrace
```
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
```

### Meta Info
META: SP7.16.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1702819152264: [FocusMode] Set focus session elapsed time 
1702819152312: [SP_ALL] Load(import) all data 
1702819152313: [SP_ALL] All Data was loaded 
1702819161495: [FocusMode] Set focus session elapsed time 
1702819161538: [SP_ALL] Load(import) all data 
1702819161539: [SP_ALL] All Data was loaded 
1702819341488: [FocusMode] Set focus session elapsed time 
1702819341535: [SP_ALL] Load(import) all data 
1702819341536: [SP_ALL] All Data was loaded 
1702819354848: [FocusMode] Set focus session elapsed time 
1702819354886: [SP_ALL] Load(import) all data 
1702819354887: [SP_ALL] All Data was loaded 
1702819367656: [FocusMode] Set focus session elapsed time 
1702819367722: [SP_ALL] Load(import) all data 
1702819367723: [SP_ALL] All Data was loaded
```

**Comment by devashishRaj** [comment] 2023-12-17 13:30
[ANONYMIZED-super-productivity-crash-user-data-export.json](https://github.com/johannesjo/super-productivity/files/13696256/ANONYMIZED-super-productivity-crash-user-data-export.json)

**Comment by johannesjo** [comment] 2023-12-18 15:01
Duplicate of #2901

**Closed by johannesjo** 2023-12-18 15:01 UTC
