### ISSUE TITLE
Encountered problem while syncing with googleDrive

### ISSUE THREAD

**Issue by BongweKE** [johannesjo/super-productivity#718] opened 2020-12-04 06:40 UTC
###The program flares up errors and brings up a developer tools menu like the one in browsers used to inspect HTML elements. The error message asks me to report this error and has a huge red background

### Your Environment
I use the latest version of the snap as per this time
* Kali Linux latest version as per this time
* Desktop Environment: Xfce? if that's the actual name. It's not gnome though
* Browser Name and version: An old version of firefox. But does it actually use my browser?

### Expected Behavior
I just expected to actually sync my data to googleDrive

### Current Behavior
Flares up errors

### Steps to Reproduce (for bugs)
1. Make sure you have installed it the first time in a machine
2.Then do some tasks
3.Try to save some data to googleDrive
4.Use an email that's being used by this snap for the first time

### Error Log (Desktop only)\

this is what running the snap has brought to my terminal since I ran the snap for the first time

black@kaliSana:~$  superproductivity  
{ enabled: null, showDevTools: false, mode: 'bottom' }
Saving backups to /home/black/snap/superproductivity/969/.config/superProductivity/backups
No custom styles detected at /home/black/snap/superproductivity/969/.config/superProductivity/styles.css
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
getSettingsCb no callbacks left
refreshToken null
Success code=4/1AY0e-g5Vrwj9_E5x5y2Y6Pz4JlHHshWPHNS8rQmRIxi_jO3BxZS_Y7_5Vtg&scope=https://www.googleapis.com/auth/drive%20https://www.googleapis.com/auth/drive.install
Gtk-Message: 08:18:31.988: GtkDialog mapped without a transient parent. This is discouraged.
08:18:37.435 › Frontend Error: Error: Uncaught (in promise): Error: No correct localLastSync given
Error: No correct localLastSync given
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579919)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573258
    at new C (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:17843)
    at Ex (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
    at t._setLocalRevAndLastSync (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3578985)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Z (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at new C (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:17869)
    at Ex (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
    at t._setLocalRevAndLastSync (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3578985)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:1543328)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579) Error: Uncaught (in promise): Error: No correct localLastSync given
Error: No correct localLastSync given
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579919)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573258
    at new C (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:17843)
    at Ex (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
    at t._setLocalRevAndLastSync (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3578985)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Z (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at new C (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:17869)
    at Ex (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
    at t._setLocalRevAndLastSync (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
    at t.<anonymous> (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3578985)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:1543328)
    at l.invoke (file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
08:18:46.741 › Frontend Error Stack: typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:288:12)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573258)
constructor (webpack:///node_modules/zone.js/fesm2015/zone.js:1385:32)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
executor(makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1388:20)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573003)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3579818)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js:1:3573060)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
Gtk-Message: 08:22:15.028: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 08:23:54.561: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 08:25:17.366: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by johannesjo** [comment] 2020-12-04 18:06
Thanks for reporting! I am closing this as a duplicate of #720.

**Closed by johannesjo** 2020-12-04 18:06 UTC
Labels: bug
