### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by Henry-Keys** [johannesjo/super-productivity#392] opened 2020-06-11 08:19 UTC
META: SP5.3.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.3 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Steps to Reproduce
No ideia

### Error Log (Desktop only)
```
Error: Uncaught (in promise): TypeError: Cannot read property 'reduce' of undefined TypeError: Cannot read property 'reduce' of undefined at t. (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:459:23) at file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540329 at Object.next (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540434) at executor (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1539370) at new t (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:913:33) at D (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1539115) at t._loadForProjectIds (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1551191) at t. (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:449:37) at file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540329 at Object.next (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540434)
```

### Stacktrace
```
t.<anonymous> (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:459:23)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540329)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540434)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1539370)
new t (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:913:33)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1539115)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1551191)
t.<anonymous> (file:///snap/superproductivity/648/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:449:37)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540329)
Ur (file:///snap/superproductivity/648/resources/app.asar/dist/main.598cad98aaf68f146685.js:1:1540434)
```

**Comment by johannesjo** [comment] 2020-06-11 10:41
Thanks for reporting. I am closing this as a duplicate of #391

**Closed by johannesjo** 2020-06-11 10:41 UTC

**Comment by johannesjo** [comment] 2020-06-11 10:54
I am wondering how your setup is as I am unable to reproduce this. Have you been using the app before or did you start with a fresh set of data? And do you have any projects created at all?

**Comment by Henry-Keys** [comment] 2020-06-11 11:57
It happened a second time and then i remember how the bug came to appear.
I created a new project "Books" and then the bug happened.

I can send you my **SUPER_PRODUCTIVITY_SYNC.json** so you can try to replicate.
I just need to hide sensitive information in this file.

**Comment by johannesjo** [comment] 2020-06-11 12:41
A copy of the data would be super helpful! You can send it to contact@super-productivity.com. I promise to handle it carefully and delete it after I am done.

**Comment by johannesjo** [comment] 2020-06-11 12:50
Nevertheless making sure no sensitive data is included is probably a good idea.

**Comment by johannesjo** [comment] 2020-06-11 16:56
A new patch release is out. Thank you very much!
