### ISSUE TITLE
Due date and multilevel subtasks

### ISSUE THREAD

**Issue by korzol** [johannesjo/super-productivity#265] opened 2019-12-17 15:56 UTC
Hello
Is it possible to implement an option to set due date-time per task. 
Also multilevel sub tasks I believe would be great feature
Thank you for this great app

**Comment by johannesjo** [comment] 2019-12-17 18:08
Glad that you like the app! 
There already is the function to add reminders to task, you can use them like a due date, if you like. Multilevel subtasks are not on the list. Personally I believe that they defeats the purpose of splitting your work into smaller chunks possibly leaving you instead working on some huge mega tasks. Also there are several problems when it comes to the UI, but there are also many possible issues and edge cases to consider when it comes to the model.

**Comment by Mindstormer619** [comment] 2019-12-18 11:15
Adding on to the suggestion, I like creating a new project to track those megatasks that have lots of tasks under them. Haven't needed more than one level of nesting when that's in place.

**Comment by johannesjo** [comment] 2020-02-14 16:37
Closing this as duplicate of #181

**Closed by johannesjo** 2020-02-14 16:38 UTC
