### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by davsta01** [johannesjo/super-productivity#394] opened 2020-06-11 12:21 UTC
META: SP5.3.4 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.4 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
t.<anonymous> (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:459:23)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1540329)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1540434)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1539370)
new t (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:913:33)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1539115)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1551191)
t.<anonymous> (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/src/app/core/persistence/persistence.service.ts:449:37)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1540329)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:1540434)
```

**Comment by johannesjo** [comment] 2020-06-11 12:37
Thanks for reporting! I am wondering how your setup is as I am unable to reproduce this. Have you been using the app before or did you start with a fresh set of data? And do you have any projects created at all?
 
Also: This is a duplicate of #391

**Closed** 2020-06-11 12:50 UTC
Labels: bug

**Comment by johannesjo** [comment] 2020-06-11 16:56
A new patch release is out. Thank you very much!

**Comment by davsta01** [comment] 2020-06-11 17:36
Hey Johannes, 
wow, that was quick - seems to be working now, thank YOU! :-)
cheers
