### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by diegoehg** [johannesjo/super-productivity#1735] opened 2021-12-06 01:07 UTC
### Steps to Reproduce

1. A task is started in Pomodoro mode.
2. After 25 minutes, it appears break dialog and 5 minute pause counter.
3. After 5 minutes break, press continue button
4. The following error appears in the whole window:

```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
task (webpack:///src/app/features/idle/idle.service.ts:137:22)__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
META: SP7.8.0 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36
```

### Stacktrace
```
task (webpack:///src/app/features/idle/idle.service.ts:137:22)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
```

### Meta Info
META: SP7.8.0 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638752042027: [Tag] Update Work End for Tag 
1638752042030: [Persistence] Save to DB (2) 
1638752102009: [Task] Add time spent 
1638752102010: [Tag] Update Work End for Tag 
1638752102015: [Persistence] Save to DB (2) 
1638752161964: [Task] Add time spent 
1638752161965: [Tag] Update Work End for Tag 
1638752161968: [Persistence] Save to DB (2) 
1638752161970: [Pomodoro] Finish Pomodoro Session 
1638752161991: [Task] UnsetCurrentTask 
1638752487983: [Idle] Trigger Idle 
1638752492156: [Idle] Set idle time (3) 
1638752492972: [Idle] Trigger Idle 
1638752495989: [Idle] Set idle time (2) 
1638752517998: [Idle] Trigger Idle (5) 
1638752520988: [Pomodoro] Pause Pomodoro 
1638752521997: [Idle] Set idle time (2) 
1638752523004: [Idle] Trigger Idle 
1638752527244: [Idle] Set idle time (5) 
1638752528004: [Idle] Trigger Idle 
1638752534560: [Idle] Set idle time (7) 
1638752534974: [Pomodoro] Finish Pomodoro Session 
1638752534975: [Task] Toggle start 
1638752534976: [Persistence] Save to DB 
1638752534976: [Task] SetCurrentTask 
1638752534977: [Pomodoro] Start Pomodoro 
1638752535011: [Task] Add time spent 
1638752535012: [Tag] Update Work End for Tag 
1638752535018: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment] 2021-12-06 20:17
Thank you very much for reporting this. Looks like a duplicate of #1684 

Would you maybe be willing to help me debugging this?

**Closed by johannesjo** 2021-12-06 20:17 UTC
