### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by EvVlF** [johannesjo/super-productivity#1732] opened 2021-12-03 22:20 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
task (webpack:///src/app/features/idle/idle.service.ts:137:22)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
```

### Meta Info
META: SP7.8.0 Electron – ru – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638569932627: [Idle] Set idle time (5) 
1638569933614: [Idle] Trigger Idle 
1638569937628: [Idle] Set idle time (5) 
1638569938620: [Idle] Trigger Idle 
1638569942629: [Idle] Set idle time (5) 
1638569943626: [Idle] Trigger Idle 
1638569948630: [Idle] Set idle time (6) 
1638569948631: [Idle] Trigger Idle 
1638569953631: [Idle] Set idle time (5) 
1638569953637: [Idle] Trigger Idle 
1638569958632: [Idle] Set idle time (5) 
1638569958641: [Idle] Trigger Idle 
1638569963633: [Idle] Set idle time (5) 
1638569963647: [Idle] Trigger Idle 
1638569968634: [Idle] Set idle time (5) 
1638569968652: [Idle] Trigger Idle 
1638569973635: [Idle] Set idle time (5) 
1638569973658: [Idle] Trigger Idle 
1638569978637: [Idle] Set idle time (5) 
1638569978664: [Idle] Trigger Idle 
1638569983639: [Idle] Set idle time (5) 
1638569983665: [Idle] Trigger Idle 
1638569988639: [Idle] Set idle time (5) 
1638569988666: [Idle] Trigger Idle 
1638569993641: [Idle] Set idle time (5) 
1638569993672: [Idle] Trigger Idle 
1638569998642: [Idle] Set idle time (5) 
1638569998672: [Idle] Trigger Idle 
1638570001643: [Idle] Set idle time (3)
```

**Comment by johannesjo** [comment] 2021-12-05 09:08
Duplicate of #1684 

Help debugging this would be very welcome!

**Closed by johannesjo** 2021-12-05 09:08 UTC
