### ISSUE TITLE
convert to sub tasks with drag and drop

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#709] opened 2020-12-01 11:35 UTC
Would be nice to be able to convert tasks to sub task via drag and drop (and viceversa convert sub tasks to tasks)

**Comment by santiyounger** [comment] 2020-12-01 12:41
that's a great idea, I second this

**Comment by johannesjo** [comment] 2020-12-01 19:29
Thank you very much for taking the time to open this up. Sounds like a duplicate of #235. Please upvote the original issue if you like to see this.

**Closed by johannesjo** 2020-12-01 19:29 UTC
Labels: enhancement
