### ISSUE TITLE
[Bug Report] -Confirm before exiting the app- is not working

### ISSUE THREAD

**Issue by richardnassour** [johannesjo/super-productivity#579] opened 2020-10-13 19:47 UTC
### Your Environment
* Version used: 5.9.9 UWP
* Operating System and version: Windows 10 2004

### Expected Behavior
I expect a confirmation dialog when I click the close (X) button because I have the option ticked in the settings

### Current Behavior
When I click the close (X) button the app closes without asking for confirmation even though I have the option ticked
![superProductivity_OK9rCqH1xL](https://user-images.githubusercontent.com/33163707/95908493-d2109880-0da5-11eb-85aa-e5dbaf86caf1.png)

**Comment by johannesjo** [comment] 2020-10-13 19:52
Hm. I just checked with the latest UWP and it works. I assume you didn't just forget to hit save?

**Comment by richardnassour** [comment] 2020-10-13 20:30
> Hm.you I just checked with the latest UWP and it works. I assume you didn't just forget to hit save?

I hit save. also unticked, saved, restarted the app and re-ticked it again. still.

**Comment by johannesjo** [comment] 2020-10-13 21:01
Ok, thank you. Probably nothing I can do for now, as I am unable to reproduce this.

**Comment by dmzh22** [comment] 2020-10-29 11:36
Same issue here with SuperProductivity 6.0.1 on MacOs 10.15.7.
No confirmation dialog shown before exiting. Confirmed on two different machines.

Great tool :-) Thank you so much

**Comment by johannesjo** [comment] 2020-10-29 15:20
I was able to reproduce the issue, after checking again. I'll have a look.

**Comment by johannesjo** [comment] 2020-10-29 18:10
Thanks again for reporting. Should be fixed with the next release.

**Closed by johannesjo** 2020-10-29 18:10 UTC
Labels: bug
