### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 't' as it is undefined.

### ISSUE THREAD

**Issue by d-r-q** [johannesjo/super-productivity#699] opened 2020-11-28 07:13 UTC
### Steps to Reproduce
Unfortunately, I don't know. The error occurred when my wife was cleaning the keyboard in my absence

### Error Log (Desktop only)
[main.log](https://github.com/johannesjo/super-productivity/files/5610185/main.log)

### Console Output
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/lz.442fc0eea6997c158216.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/reminder.18476f14a3e060101479.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/styles.e0393ca42eb49cc180b2.css.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/runtime.076604685350bc36956d.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/969/resources/app.asar/dist/main.315386ddce759b904228.js.map: 

### Stacktrace
```
task (webpack:///src/app/features/time-tracking/idle.service.ts:115:19)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/__ivy_ngcc__/fesm2015/dialog.js:408:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
```

### Meta Info
META: SP6.1.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.1.1 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1606538116197: [Tag] Update Work End for Tag 
1606538116198: [Persistence] Save to DB 
1606538116199: [Persistence] Save to DB 
1606538116200: [Persistence] Save to DB 
1606538117180: [Task] Add time spent 
1606538117182: [Project] Update Work End 
1606538117195: [Tag] Update Work End for Tag 
1606538117196: [Persistence] Save to DB 
1606538117196: [Persistence] Save to DB 
1606538117197: [Persistence] Save to DB 
1606538118180: [Task] Add time spent 
1606538118181: [Project] Update Work End 
1606538118184: [Tag] Update Work End for Tag 
1606538118184: [Persistence] Save to DB 
1606538118184: [Persistence] Save to DB 
1606538118185: [Persistence] Save to DB 
1606538118625: [Project] Add to Break Time 
1606538118639: [Persistence] Save to DB 
1606538119179: [Task] Add time spent 
1606538119180: [Project] Update Work End 
1606538119184: [Tag] Update Work End for Tag 
1606538119184: [Persistence] Save to DB 
1606538119184: [Persistence] Save to DB 
1606538119184: [Persistence] Save to DB 
1606538120042: [Task] Toggle start 
1606538120043: [Persistence] Save to DB 
1606538120043: [Task] UnsetCurrentTask 
1606541472685: [Task] SetSelectedTask 
1606541472691: [WorkContext] Set Active Work Context 
1606541472730: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment] 2020-11-28 12:31
Thank you very much for taking the time to open this up. I'll look into it!

**Comment by johannesjo** [comment] 2020-11-28 19:51
I am unable to reproduce this, but I might have found a possible fix. I am closing this, but please let me know if the issue occurs again!

**Closed** 2020-11-28 19:52 UTC
