### ISSUE TITLE
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB

### ISSUE THREAD

**Issue by halfpintutopia** [johannesjo/super-productivity#455] opened 2020-07-24 15:37 UTC
### Steps to Reproduce

1. The application was running the background
2. It seemed to do an automatic update and then sent me an error
3. Application was closed and it had updated and and is now running fine.
4.

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.Error: UnknownError: Internal error opening backing store for indexedDB.open.    at t. (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:83:13)    at file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2417084    at Object.throw (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2417189)    at apply (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2415978)    at t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)    at Object.onInvoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)    at t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)    at e.run (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)    at apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)    at t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)

### Stacktrace
```
t.<anonymous> (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:83:13)
Ur (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2417084)
Ur (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2417189)
Ur (file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js:1:2415978)
t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:784:21)
apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:894:21)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
drainMicroTaskQueue (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:601:39)
e.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:507:25)
p (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
```

### Meta Info
META: SP5.4.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.2 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by johannesjo** [comment] 2020-07-24 15:59
Thank you very much for reporting. This probably a duplicate of #419. Please have a look at that one for updates.

**Closed by johannesjo** 2020-07-24 15:59 UTC
Labels: bug, db

**Comment by johannesjo** [comment] 2020-07-26 21:15
#375
