### ISSUE TITLE
Drag task to another task to create subtasks

### ISSUE THREAD

**Issue by nicola-lunghi** [johannesjo/super-productivity#1222] opened 2021-05-20 11:18 UTC
Would be nice in  the task list to be able to drag a task ino another to transform it in a sub task

e.g. I have

- create new project
- create basic project structure
- create first test

And would be nice to drag the 2nd an t3rd task to the first to create sub-task

Thanks
Nick

**Comment by johannesjo** [comment] 2021-05-21 10:13
Thanks for opening this up. Looks like a duplicate of #905.

**Closed by johannesjo** 2021-05-21 10:13 UTC
Labels: enhancement
