### ISSUE TITLE
TypeError: Cannot read property 'keyboard' of undefined

### ISSUE THREAD

**Issue by edisangon** [johannesjo/super-productivity#352] opened 2020-04-29 10:03 UTC
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2020-04-29 10:05
Thanks for reporting. Duplicate of #349.

**Closed by johannesjo** 2020-04-29 10:05 UTC
