### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations._init/

### ISSUE THREAD

**Issue by napalu** [johannesjo/super-productivity#793] opened 2021-01-13 18:31 UTC
### Steps to Reproduce

1. Navigate to https://app.super-productivity.com/ with Firefox 84.0.2 on 64-bit  Archlinux

### Stacktrace
```
Error: Uncaught (in promise): Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. _init/<@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:2356950 o@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:2355251 invoke@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572 onInvoke@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:1555412 invoke@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6512 run@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:1984 P/<@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:16758 invokeTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:7190 onInvokeTask@https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:1555301 invokeTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:7111 runTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:2599 m@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:9184 invokeTask@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:8269 _@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:20167 k@https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:20413

scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:31)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28269:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:487:20)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:27)

META: SP6.3.3 Browser – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0```

### Meta Info
META: SP6.3.3 Browser – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

### Actions Before Error
```
None - just navigated. The problem is that indexed Db cannot be initialized
```

**Comment by johannesjo** [comment] 2021-01-13 21:29
Thanks for reporting this. Looks like a duplicate of #737 to me

**Closed by johannesjo** 2021-01-13 21:29 UTC
