### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by ejalili** [johannesjo/super-productivity#1707] opened 2021-12-01 14:20 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638357932146: [Idle] Set idle time 
1638357987606: [Idle] Trigger Idle (12) 
1638357992134: [Idle] Set idle time 
1638358047698: [Idle] Trigger Idle (12) 
1638358052144: [Idle] Set idle time 
1638358107800: [Idle] Trigger Idle (12) 
1638358112132: [Idle] Set idle time 
1638358167910: [Idle] Trigger Idle (12) 
1638358172133: [Idle] Set idle time 
1638358227994: [Idle] Trigger Idle (12) 
1638358232136: [Idle] Set idle time 
1638358288132: [Idle] Trigger Idle (12) 
1638358292134: [Idle] Set idle time 
1638358348237: [Idle] Trigger Idle (12) 
1638358352133: [Idle] Set idle time 
1638358408332: [Idle] Trigger Idle (12) 
1638358412133: [Idle] Set idle time 
1638358468438: [Idle] Trigger Idle (12) 
1638358472130: [Idle] Set idle time 
1638358528540: [Idle] Trigger Idle (12) 
1638358532126: [Idle] Set idle time 
1638358588652: [Idle] Trigger Idle (12) 
1638358592131: [Idle] Set idle time 
1638358628723: [Idle] Trigger Idle (8) 
1638367744101: [Idle] Set idle time (2) 
1638367749102: [Idle] Trigger Idle (3) 
1638368012102: [Idle] Set idle time (5) 
1638368040471: [Idle] Trigger Idle 
1638368414103: [Idle] Set idle time (138)
```

**Comment by johannesjo** [comment] 2021-12-01 17:58
Duplicate of #1683

**Closed by johannesjo** 2021-12-01 17:59 UTC
