### ISSUE TITLE
Cannot mark tasks as "done" in windows

### ISSUE THREAD

**Issue by WveedeeTee** [johannesjo/super-productivity#1829] opened 2022-01-11 13:54 UTC
### Windows 10 Enterprise 21H1

- Version used: Microsoft Store Version 7.9.2
- Operating System and version: Windows 10 Enterprise 21H1
- Browser Name and version: Chrome Versie 96.0.4664.45 (Officiële build) (64-bits)

### Expected Behavior

When I hover over a task there is are buttons to expand the task, start the timer, and mark it as done.

### Current Behavior

The buttons in the taks titlebar dissapeared (And keyboard shortcuts do not work)

### Steps to Reproduce (for bugs)

I have never tried to use the keyboard shortcuts so I do not know how long that has been an issue, I only tried it because I could not find the button.

It started when I updated the app, so I suspect it is an issue with the current build.
(This is on my work computer so I have very little control and cannot roll back te update to check)

**Comment by johannesjo** [comment] 2022-01-11 16:09
Hi there! Thanks for opening this up! Are you by any chance using a device with a touchscreen monitor?

**Comment by WveedeeTee** [comment] 2022-01-11 20:56
Yes

Op di 11 jan. 2022 17:09 schreef Johannes Millan ***@***.***>:

**Comment by johannesjo** [comment] 2022-01-12 09:17
Could maybe also open up the console of the app (Ctrl+Shift+i) and run the following there.
```
[
  'any-hover: hover',
  'any-hover: none',
  'pointer: fine',
  'pointer: coarse',
  'hover: hover',
  'hover: none',
].forEach((v) => {
  console.log(v, window.matchMedia('(' + v + ')').matches);
});
```

**Comment by marilouneko** [comment] 2022-01-12 15:21
I have the same issue with a touch screen 2-in-1 laptop. It's weird because it worked fine before christmas and now it doesn't work anymore :(. i disabled my touch screen like they said in the other thread and everything works fine now.

**Comment by johannesjo** [comment] 2022-01-12 15:25
@marilouneko could you maybe do the same as above (execute the command from the console of the app)? This would help me find out out what is actually causing this behavior.

**Comment by marilouneko** [comment] 2022-01-12 15:33
![image](https://user-images.githubusercontent.com/97615129/149170721-9d326319-8f51-4878-9107-095edf419e4d.png)

Sorry, i'm not familiar with coding. i added a screenshot so you could make sure i put the command in the right place and everything. Here's what it said:

[
  'any-hover: hover',
  'any-hover: none',
  'pointer: fine',
  'pointer: coarse',
  'hover: hover',
  'hover: none',
].forEach((v) => {
  console.log(v, window.matchMedia('(' + v + ')').matches);
});
VM235:9 any-hover: hover false
VM235:9 any-hover: none true
VM235:9 pointer: fine false
VM235:9 pointer: coarse true
VM235:9 hover: hover false
VM235:9 hover: none true
undefined
persistence.service.ts:338 LOAD COMPLETE false

**Comment by johannesjo** [comment] 2022-01-13 10:52
Thank you very much! This doesn't look good unfortunately, since the output indicates that the app doesn't get the correct information about a mouse being available :( Not sure how to deal with this tbh. :/

Could you maybe also execute this (The same but with to additional entries): 
```
[
  'any-hover: hover',
  'any-hover: none',
  'any-pointer: fine',
  'any-pointer: coarse',
  'pointer: fine',
  'pointer: coarse',
  'hover: hover',
  'hover: none',
].forEach((v) => {
  console.log(v, window.matchMedia('(' + v + ')').matches);
});
```

**Comment by marilouneko** [comment] 2022-01-13 13:44
Voilà!

![image](https://user-images.githubusercontent.com/97615129/149341294-fc15cea2-cdbb-4d11-9ce2-84081552361c.png)

**Comment by johannesjo** [comment] 2022-01-14 16:08
@marilouneko Thank you again! 

I am very sorry to bother you so much (unfortunately I have no such device available to make these tests. But to verify if a chromium update might fix the issue, could you do one more of these, but this time in the latest version of chrome? It's weird that the output is incorrect and I am hoping that this behavior doesn't occur with the latest version.

**Comment by marilouneko** [comment] 2022-01-14 18:33
it's my pleasure to help, i really appreciate you trying to fix the issue :) as far as i'm concerned my chrome is up to date. i noticed windows needed an updated and did it but the issue is still there. seems like the command gave the same results as last time.

![image](https://user-images.githubusercontent.com/97615129/149566807-e322844d-30da-4ae5-90fe-3d6fec42dcdc.png)

**Comment by johannesjo** [comment] 2022-01-14 18:45
Thanks again! This seems indeed to be a chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1088262
https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/results/

**Comment by marilouneko** [comment] 2022-01-14 18:56
thank you for finding the problem! So just to be sure that i understand correctly, the issue needs to be fixed by chromium? aka i just wait and hope it's corrected in the next updates?

**Comment by johannesjo** [comment] 2022-01-14 19:06
> thank you for finding the problem! So just to be sure that i understand correctly, the issue needs to be fixed by chromium? aka i just wait and hope it's corrected in the next updates?

That's the "correct" long term solution at least :)

Meanwhile one thing you could do is to deactivate touch.

Could I pester you with another test? What is the output on this page, ideally once with mouse connected and once without:
https://detect-it.rafgraph.dev/

**Comment by marilouneko** [comment] 2022-01-14 19:15
yes, perfect thank you. it does work when i disable the touchscreen.

here are the results with USB mouse connected (usual setup)
![image](https://user-images.githubusercontent.com/97615129/149571965-d6df757a-fd0c-4608-86ff-3edd765175f9.png)

and USB mouse disconnected
![image](https://user-images.githubusercontent.com/97615129/149572180-b1f71561-e715-45ef-a879-7bede550a6b1.png)

**Comment by johannesjo** [comment] 2022-01-14 20:34
Thank you once more! This is a good solution then until Chromium comes along.

**Comment by johannesjo** [comment] 2022-01-14 20:35
Please let me know if this issue persists regardless once the new version is released!

**Closed** 2022-01-14 20:35 UTC
Labels: bug, external issue
