### ISSUE TITLE
Date dropdown looks corrupt (6.1.2)

### ISSUE THREAD

**Issue by Heart1010** [johannesjo/super-productivity#736] opened 2020-12-19 12:58 UTC
using v6.1.2 on Win10 - the date popup looks corrupt

![image](https://user-images.githubusercontent.com/1481680/102689925-2ef35980-4202-11eb-9a2b-db4d45ffaee3.png)

**Comment by johannesjo** [comment] 2020-12-20 21:58
Thank you very much for bringing this to my attention. I thought that I fixed this, but apparently not.

**Comment by johannesjo** [comment] 2020-12-21 12:05
This should hopefully be fixed with the upcoming release. Thanks again!

**Comment by johannesjo** [comment] 2020-12-21 12:05
ff

**Comment by Heart1010** [comment] 2020-12-28 13:42
> This should hopefully be fixed with the upcoming release. Thanks again!

Using v6.3.1 and still having that problem

**Comment by johannesjo** [comment] 2020-12-28 14:32
Puh this is driving me nuts :D

**Comment by johannesjo** [comment] 2020-12-28 14:40
Well thanks for staying with me on this!

**Comment by johannesjo** [comment] 2020-12-28 19:43
https://github.com/johannesjo/super-productivity/issues/576

**Comment by johannesjo** [comment] 2020-12-29 20:27
I finally was able to find the cause of this. I will provide a fix for the next release. Meanwhile you might be able to correct this by selecting a default starting day for the week under "Misc Settings" on the config page. Thanks again for bringing this to my attention!

**Closed** 2020-12-29 20:28 UTC
Labels: bug

**Comment by Heart1010** [comment] 2021-01-04 21:00
> I finally was able to find the cause of this. I will provide a fix for the next release. Meanwhile you might be able to correct this by selecting a default starting day for the week under "Misc Settings" on the config page. Thanks again for bringing this to my attention!

worked 👍  thank you
