### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at sm. (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1541340)    at Generator.throw ()    at a (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1540569)    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)    at Object.onInvoke (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:140100)    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)    at t.run (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)  

### ISSUE THREAD

**Issue by rawda-developer** [johannesjo/super-productivity#1472] opened 2021-08-28 12:58 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at sm.<anonymous> (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1541340)
    at Generator.throw (<anonymous>)
    at a (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1540569)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:139916)
    at Z (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15036
    at a (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1818798)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:139916)
```

### Meta Info
META: SP7.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.1 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1630155351225: [Persistence] Save to DB 
1630155351225: [Persistence] Save to DB 
1630155352203: [Task] Add time spent 
1630155352206: [Tag] Update Work End for Tag 
1630155352223: [Persistence] Save to DB 
1630155352224: [Persistence] Save to DB 
1630155353203: [Task] Add time spent 
1630155353206: [Tag] Update Work End for Tag 
1630155353224: [Persistence] Save to DB 
1630155353224: [Persistence] Save to DB 
1630155354203: [Task] Add time spent 
1630155354205: [Tag] Update Work End for Tag 
1630155354215: [Persistence] Save to DB 
1630155354216: [Persistence] Save to DB 
1630155355203: [Task] Add time spent 
1630155355205: [Tag] Update Work End for Tag 
1630155355223: [Persistence] Save to DB 
1630155355223: [Persistence] Save to DB 
1630155356203: [Task] Add time spent 
1630155356209: [Tag] Update Work End for Tag 
1630155356227: [Persistence] Save to DB 
1630155356228: [Persistence] Save to DB 
1630155357203: [Task] Add time spent 
1630155357206: [Tag] Update Work End for Tag 
1630155357220: [Persistence] Save to DB 
1630155357221: [Persistence] Save to DB 
1630155391652: [Task] Add time spent 
1630155391656: [Tag] Update Work End for Tag 
1630155391685: [Persistence] Save to DB 
1630155391685: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-08-28 14:07
Duplicate of #398

**Comment by johannesjo** [comment] 2021-08-28 14:07
But thanks for reporting :)

**Closed by johannesjo** 2021-08-28 14:07 UTC
