### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is undefined.

### ISSUE THREAD

**Issue by gloarte** [johannesjo/super-productivity#1702] opened 2021-11-30 03:29 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is undefined.
    at b._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:2107790)
    at b.__tryOrUnsub (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956876)
    at b.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956105)
    at T._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955288)
    at T.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955062)
    at v._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:975388)
    at v.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:955062)
    at O.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:952809)
    at b._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:1716081)
    at b.__tryOrUnsub (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.f4427a919009fab6.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – es-419 – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638234268320: [Idle] Set idle time 
1638234326457: [Idle] Trigger Idle (12) 
1638234328326: [Idle] Set idle time 
1638234386528: [Idle] Trigger Idle (12) 
1638234388296: [Idle] Set idle time 
1638234446596: [Idle] Trigger Idle (12) 
1638234448283: [Idle] Set idle time 
1638234506660: [Idle] Trigger Idle (12) 
1638234508274: [Idle] Set idle time 
1638234566733: [Idle] Trigger Idle (12) 
1638234568241: [Idle] Set idle time 
1638234626799: [Idle] Trigger Idle (12) 
1638234628261: [Idle] Set idle time 
1638234686898: [Idle] Trigger Idle (12) 
1638234688250: [Idle] Set idle time 
1638234746965: [Idle] Trigger Idle (12) 
1638234748245: [Idle] Set idle time 
1638234807024: [Idle] Trigger Idle (12) 
1638234808251: [Idle] Set idle time 
1638234867106: [Idle] Trigger Idle (12) 
1638234868230: [Idle] Set idle time 
1638234927183: [Idle] Trigger Idle (12) 
1638234928230: [Idle] Set idle time 
1638235049955: [Idle] Trigger Idle (12) 
1638235050980: [Idle] Set idle time 
1638235526086: [Idle] Trigger Idle (5) 
1638242919116: [Idle] Set idle time (7375) 
1638242919637: [Task] Update Task 
1638242919647: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment] 2021-11-30 21:54
Duplicate of #1684

**Closed by johannesjo** 2021-11-30 21:54 UTC
