### ISSUE TITLE
One feature I'd love to see

### ISSUE THREAD

**Issue by jmastrolia** [johannesjo/super-productivity#3086] opened 2024-03-18 12:07 UTC
I am LOVING the app - so far, it's the best to-do list app I've found for my needs and preferences. The one thing I'd love to see is due dates (separate from schedule dates). I have a lot of tasks with an end date - some within a few days but some months out, so being able to see if something is coming up would be amazing, without having to schedule it yet.

Other things - subtasks, and two-way sync with GCal - even if it just drops the tasks as an all-day event (I can click and drag from there.) 

But those things are secondary, and I can live without them.

Love Super-Productivity!

**Comment by Jagdfalke** [comment] 2024-03-21 20:23
Regarding the due date, there is already a feature request: https://github.com/johannesjo/super-productivity/issues/405

Feel free to upvote it.

**Comment by johannesjo** [comment] 2024-03-22 14:45
Closing this as duplicate of #405

**Closed by johannesjo** 2024-03-22 14:45 UTC
Labels: enhancement
