### ISSUE TITLE
Changing the Project on top 

### ISSUE THREAD

**Issue by matcabgomes** [johannesjo/super-productivity#132] opened 2019-01-30 17:56 UTC
## Your Environment

* Version used: v2.0.1
* Operating System and version: Linux Mint 18.3
* Desktop Environment: Cinnamon 64bit

## Current Behavior
BUG: When I change the project on the top left, all the funcionalities on the top stop working, and I cannot change to other project.

## Steps to Reproduce (for bugs)
1. Open the App
2. Click on the list of the project
3. (I currentlty have 2 projects and the default 'Super Productivity' Project) Change to the second project
4. All the buttons on the right stop working, and I cannot change the project, the list is showed, but when I click on another project nothing happens.

P.S: The 'Tasks', 'Worklog', 'Projects', 'Settings' work, but I cannot add a task, because the button on the right has frozen.

**Comment by johannesjo** [comment] 2019-01-30 18:03
Thanks for reporting. Is this directly after the import of the v1 data? Also could you maybe check the console for errors (Ctrl+Shift+ should open it).

**Comment by matcabgomes** [comment] 2019-01-30 18:08
Yes, I Imported  v1 dataon the first time I opened. But now I'm just opening without importing anything, and the problem is also happening. The console isn't showing anything. :)

**Comment by johannesjo** [comment] 2019-01-30 18:19
Hm that's weird. This behavior should only occur if there is some sort of error. Also: There should be at least some output in the console, even if there is no error. Is there anything useful inside the network tab?

**Comment by johannesjo** [comment] 2019-02-10 17:27
@matcabgomes were you able to solve this issue?

**Comment by danielestevez** [comment] 2019-02-15 15:07
I have exactly the same issue: only the main bar buttons work (tasks/worklog/project/settings). I also imported V1 Settings but wouldn't mind start from scratch if it fixes it

I can't see anything in console, just some not related (i think) 
`polyfills.65ed77762c2223b33daf.js:1 Uncaught Error: Insufficient Settings for Jira
    at e._sendRequest (main.f636a92db7cdcad98921.js:1)
 `
But right after this message the app still works, it becomes unresponsive at any other latter point, but i can't find where, no error messages :confused:

**Comment by danielestevez** [comment] 2019-02-15 16:06
Just to add more info: I think it's related to that imported settings to JIRA and/or github. I disabled all synchronizations from my projects and i can not reproduce the issue. 

Maybe it works for @matcabgomes too?

I'll keep trying this since i really use the JIRA sync and will try to reproduce the JIRA related error later next week

**Comment by johannesjo** [comment] 2019-02-16 22:25
@danielestevez which version are you using?

**Comment by danielestevez** [comment] 2019-02-17 17:38
v.2.2.2 on Ubuntu 18.04

**Comment by johannesjo** [comment] 2019-02-17 17:49
@danielestevez Could you maybe check if the issue persists with 2.2.3?

**Comment by danielestevez** [comment] 2019-02-17 17:53
I will try but since I removed the JIRA integration I cannot reproduce it anymore.
I'll try next week adding the integration back, I guess it could be a problem with importing the v1 settings

**Comment by danielestevez** [comment] 2019-02-19 21:53
Hi @johannesjo, i removed the integration and added the settings again and i cannot reproduce the issue, so the problem seems to be with the initial import from v1?
I don't think i can reproduce it again

**Comment by johannesjo** [comment] 2019-02-24 21:55
@danielestevez thanks for checking. I am assuming that most people should be through migration process by now, so I am closing this. If you encounter another issue, please let me know.

**Closed by johannesjo** 2019-02-24 21:55 UTC
