### ISSUE TITLE
Error: Uncaught (in promise): Error: No correct localLastSync given nullError: No correct localLastSync given null    at e. (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3529073)    at Generator.next ()    at https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522395    at new C (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)    at fE (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)    at e._setLocalRevAndLastSync (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)    at e. (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528122)    at Generator.next ()    at a (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)    at l.invoke (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)

### ISSUE THREAD

**Issue by zig-i2p** [johannesjo/super-productivity#868] opened 2021-02-06 18:02 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): Error: No correct localLastSync given null
Error: No correct localLastSync given null
    at e.<anonymous> (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3529073)
    at Generator.next (<anonymous>)
    at https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522395
    at new C (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at fE (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)
    at e._setLocalRevAndLastSync (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)
    at e.<anonymous> (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528122)
    at Generator.next (<anonymous>)
    at a (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)
    at l.invoke (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Z (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at fE (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)
    at e._setLocalRevAndLastSync (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)
    at e.<anonymous> (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528122)
    at Generator.next (<anonymous>)
    at a (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)
    at l.invoke (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:1555412)
    at l.invoke (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
```

### Meta Info
META: SP6.3.3 Browser – ru-RU – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36

### Actions Before Error
```
1612634302702: [SP_ALL] Load(import) all data 
1612634302706: [SP_ALL] All Data was loaded 
1612634302718: [WorkContext] Set Active Work Context 
1612634302766: [Task] SetSelectedTask 
1612634321938: [Layout] Hide SideBar 
1612634328195: [Layout] Toggle SideBar 
1612634344945: [Global Config] Update Global Config Section 
1612634344958: [Persistence] Save to DB 
1612634389218: [Global Config] Update Global Config Section 
1612634389265: [Persistence] Save to DB 
1612634448200: [Global Config] Update Global Config Section 
1612634448222: [Persistence] Save to DB 
1612634451960: [Global Config] Update Global Config Section 
1612634451969: [Persistence] Save to DB 
1612634469605: [Global Config] Update Global Config Section 
1612634469623: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-02-06 19:22
Thanks for reporting. This is a duplicate of #720

**Closed by johannesjo** 2021-02-06 19:22 UTC
