### ISSUE TITLE
[Arch] SNAP package - Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by presianbg** [johannesjo/super-productivity#27] opened 2017-11-22 11:11 UTC
## Your Environment

* Version used: Latest from SNAP
* Operating System and version: Arch with all packages up-to-date
* Desktop Environment: Cinnamon

## Expected Behavior
The application is starting with this error:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
```
And looks like this:

![image](https://user-images.githubusercontent.com/2163486/33124647-652b120a-cf86-11e7-82c7-bb9eeaa826fc.png)

Any advice?

Btw the web app is awesome!

Best Regards,
Presian

**Comment by johannesjo** [comment] 2017-11-22 11:16
Hello! Thanks for reporting! Here are some suggestions Does `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` fix your issue (source: https://askubuntu.com/questions/208431/failed-to-load-module-canberra-gtk-module)?

**Comment by presianbg** [comment] 2017-11-22 12:33
@johannesjo 
Thanks for fast response. Arch Linux has different package names for those libraries:

````
extra/libcanberra 0.30+2+gc0620e4-1 [installed]
    A small and lightweight implementation of the XDG Sound Theme Specification
extra/libcanberra-gstreamer 0.30+2+gc0620e4-1
    GStreamer plugin for libcanberra
extra/libcanberra-pulse 0.30+2+gc0620e4-1 [installed]
    PulseAudio plugin for libcanberra
multilib/lib32-libcanberra 0.30-4 [installed]
    A small and lightweight implementation of the XDG Sound Theme Specification (32-bit)
multilib/lib32-libcanberra-pulse 0.30-4
    PulseAudio plugin for libcanberra (32-bit)
```
Perhaps it's wrong / missing path? Unfortunately I have poor experience with SNAP , actually it's my fist snap package :), so I'm not able to provide any detailed info without further guidance.

**Comment by johannesjo** [comment] 2017-11-22 13:09
Thank you! That's already pretty helpful. I did a little research. Currently I believe that this an error with snap building itself that it doesn't properly map it's olugins.

This is what the electron generated snapcraft.yml looks like:
```
name: superproductivity
version: 1.3.6
summary: superProductivity
description: Personal Task Management App to help you with your daily struggle with JIRA etc.
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  superproductivity:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/superproductivity
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: /home/user/www/super-productivity/dist/linux-unpacked
    after:
      - desktop-glib-only
```

**Comment by Morganamilo** [comment] 2017-11-28 06:39
I uploaded a version to the AUR. See if that works for you.

**Comment by johannesjo** [comment] 2017-11-28 09:47
@Morganamilo Did you do any adjustments to the snapfile? If so I'm curious to hear what they are!

**Comment by presianbg** [comment] 2017-11-28 11:40
@Morganamilo It works! Many thanks :+1:

**Comment by Morganamilo** [comment] 2017-11-28 16:21
I am not a fan of snap so I never bothered to try it. First I tried compiling from source where I got 'cannot find module ..dialog' so instead I used the deb which works fine.

The AUR is the Arch User Repository, basically a repo where any one is allowed to upload packages.

You can find the package here https://aur.archlinux.org/packages/superproductivity/

**Comment by johannesjo** [comment] 2017-11-28 17:14
@Morganamilo interesting! Thanks! Didn't know about it.

Also interesting that you got the 'cannot find module ..dialog' error when compiling. So far I have't been able to reproduce the issue myself unfortunately although I tried different linux distros and configs via a VM.

**Comment by Morganamilo** [comment] 2017-11-28 17:50
Having looked back over it, the error I actually got was 'cannot find module ..tray'. I realised this was from trying to open Super Productivity while there was an instance running in the background. I would call this its own issue but its unrelated to this.

So with no instance already running in the background, the latest deb, .tar.gz and clone of master all build and run fine on my machine.

**Comment by johannesjo** [comment] 2017-11-29 22:55
Not really sure if this is still an issue with the latest release to be honest. I'm closing this for now.

**Closed by johannesjo** 2017-11-29 22:55 UTC
Labels: bug, help wanted

**Comment by andres-jurado** [comment] 2018-04-30 23:06
Regarding this issue. The regular version of Firefox runs without issues, but the snap version (/snap/bin/firefox) produces the following error:

Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by johannesjo** [comment] 2018-04-30 23:52
@andres-jurado. Could you maybe open up a new issue and provide a little bit more info? That would be really helpful!

**Comment by hasand** [comment] 2018-05-05 15:04
Open Synaptic package manager (it's available in Linux Software resource) and search for canberra-gtk-module then mark for installation and apply. That worked for me.

**Comment by andres-jurado** [comment] 2018-05-05 20:31
Sadly that package doesn't seem to be present in Ubuntu 18.04 amd64 (the
closest is libcanberra-gtk-module which I already have installed)


*José Andrés Jurado*
Economics Student

**Comment by hasand** [comment] 2018-05-05 21:08
Andres, I did that just a few minutes before I posted the first message up there. 
I have Ubuntu 18.04 on amd64 laptop

**Comment by johannesjo** [comment] 2018-05-06 18:30
I'm updating electron and electron builder for the next release. I'm unable to reproduce this issue properly, but hopefully this will fix the issue and automatically install the libcanberra-gtk-module if not already there.

**Comment by makeworld-the-better-one** [comment] 2018-09-13 00:13
I am having the same issue with a completely separate snap.

**Comment by BananaLoaf** [comment] 2019-04-28 15:34
Fixed this bug for me on Manjaro, but I was launching google-play-music-desktop-player, not super-productivity
`sudo snap install core`

**Comment by makeworld-the-better-one** [comment] 2019-04-28 17:22
I've had this bug with other programs. If you run `echo $GTK_MODULES` you can see the libcanberra is there. By running `unset GTK_MODULES` you can remove it, and all applications that reported the error work fine. You can add this command to your `~/.bash_profile` or the Zsh equivalent, whatever you use. It worked for me with other stuff, but I have never used this program before.
