### ISSUE TITLE
Unknown sync error

### ISSUE THREAD

**Issue by j316radoslawredzik** [johannesjo/super-productivity#3283] opened 2024-07-22 14:41 UTC
### Steps to Reproduce
1. Launch SuperProductivity
2. Click 
![image](https://github.com/user-attachments/assets/71fd453c-e5d4-44aa-97a6-a20ab5f7570c)
3. Notice error
![image](https://github.com/user-attachments/assets/54923f5b-a4e1-4a78-bfc4-34480f22787d)

### Error Log (Desktop only)
[2024-07-22 16:20:44.613] [info]  close, isQuiting: undefined
[2024-07-22 16:20:44.615] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2024-07-22 16:20:59.557] [info]  close, isQuiting: undefined
[2024-07-22 16:21:01.286] [info]  close, isQuiting: undefined
[2024-07-22 16:22:51.392] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-07-22 16:22:51.407] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-07-22 16:22:51.408] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-07-22 16:22:51.409] [warn]  getSettingsCb no callbacks left
[2024-07-22 16:22:51.409] [warn]  getSettingsCb no callbacks left
[2024-07-22 16:22:51.943] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-07-22 16:22:51.963] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2024-07-22 16:22:51.964] [info]  close, isQuiting: undefined
[2024-07-22 16:22:52.352] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2024-07-22 16:22:52.352] [info]  close, isQuiting: undefined
[2024-07-22 16:22:52.364] [info]  close, isQuiting: true
[2024-07-22 16:22:52.365] [info]  close, isQuiting: true
[2024-07-22 16:22:52.370] [info]  Quit after all windows being closed
[2024-07-22 16:22:54.407] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-07-22 16:22:54.501] [info]  Saving backups to /home/rr/.config/superProductivity/backups
[2024-07-22 16:22:55.097] [info]  No custom styles detected at /home/rr/.config/superProductivity/styles.css
[2024-07-22 16:23:04.670] [info]  close, isQuiting: undefined
[2024-07-22 16:23:04.672] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2024-07-22 16:23:05.792] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2024-07-22 16:23:05.832] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2024-07-22 16:23:05.833] [info]  close, isQuiting: undefined
[2024-07-22 16:23:05.833] [info]  close, isQuiting: true
[2024-07-22 16:23:05.837] [info]  Quit after all windows being closed
[2024-07-22 16:23:07.479] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-07-22 16:23:07.576] [info]  Saving backups to /home/rr/.config/superProductivity/backups
[2024-07-22 16:23:08.153] [info]  No custom styles detected at /home/rr/.config/superProductivity/styles.css
[2024-07-22 16:23:27.621] [info]  Quit after all windows being closed
[2024-07-22 16:24:08.088] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-07-22 16:24:08.653] [info]  Saving backups to /home/rr/.config/superProductivity/backups
[2024-07-22 16:24:10.130] [info]  No custom styles detected at /home/rr/.config/superProductivity/styles.css

### Console Output

I'm using linux gui

### Meta Info
META: SP9.0.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

**Comment by johannesjo** [comment] 2024-07-22 15:10
Duplicate of #3269

**Closed by johannesjo** 2024-07-22 15:10 UTC
