### ISSUE TITLE
Error: UnknownError: Internal error opening backing store for indexedDB.open

### ISSUE THREAD

**Issue by jfeid** [johannesjo/super-productivity#988] opened 2021-03-21 01:41 UTC
### Steps to Reproduce

1. Just tracking time on a task
2.
3.
4.

### Error Log (Desktop only)

No such file found.

### Console Output

main.c2e649cce333ff00c62f.js:1 @ngrx/store/update-reducers Object Object
main.c2e649cce333ff00c62f.js:1 @ngrx/effects/init Object Object
main.c2e649cce333ff00c62f.js:1 @ngrx/store/update-reducers Object Object
main.c2e649cce333ff00c62f.js:1 Persistence already allowed
main.c2e649cce333ff00c62f.js:1 3 out of 136236 MiB used (0%)
main.c2e649cce333ff00c62f.js:1 Database initialization failed
(anonymous) @ main.c2e649cce333ff00c62f.js:1
o @ main.c2e649cce333ff00c62f.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.c2e649cce333ff00c62f.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.c2e649cce333ff00c62f.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
_ @ polyfills.bbc1c0564b6a5d42ba73.js:1
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
main.c2e649cce333ff00c62f.js:1 _lastParams Object
(anonymous) @ main.c2e649cce333ff00c62f.js:1
o @ main.c2e649cce333ff00c62f.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvoke @ main.c2e649cce333ff00c62f.js:1
invoke @ polyfills.bbc1c0564b6a5d42ba73.js:1
run @ polyfills.bbc1c0564b6a5d42ba73.js:1
(anonymous) @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
onInvokeTask @ main.c2e649cce333ff00c62f.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
runTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
m @ polyfills.bbc1c0564b6a5d42ba73.js:1
invokeTask @ polyfills.bbc1c0564b6a5d42ba73.js:1
_ @ polyfills.bbc1c0564b6a5d42ba73.js:1
k @ polyfills.bbc1c0564b6a5d42ba73.js:1
main.c2e649cce333ff00c62f.js:1 Database initialization failed
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 _lastParams Object
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 Database initialization failed
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 _lastParams Object
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 Database initialization failed
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 _lastParams Object
(anonymous) @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.
Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at t.<anonymous> (main.c2e649cce333ff00c62f.js:1)
    at Generator.throw (<anonymous>)
    at o (main.c2e649cce333ff00c62f.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvoke (main.c2e649cce333ff00c62f.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.run (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvokeTask (main.c2e649cce333ff00c62f.js:1)
    at Z (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Z (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvokeTask (main.c2e649cce333ff00c62f.js:1)
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.runTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at m (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at u.invokeTask [as invoke] (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at _ (polyfills.bbc1c0564b6a5d42ba73.js:1)
handleError @ main.c2e649cce333ff00c62f.js:1
main.c2e649cce333ff00c62f.js:1 Last actions before error: Array(30)
polyfills.bbc1c0564b6a5d42ba73.js:1 Uncaught Error: Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.
Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at t.<anonymous> (main.c2e649cce333ff00c62f.js:1)
    at Generator.throw (<anonymous>)
    at o (main.c2e649cce333ff00c62f.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvoke (main.c2e649cce333ff00c62f.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.run (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvokeTask (main.c2e649cce333ff00c62f.js:1)
    at t.handleError (main.c2e649cce333ff00c62f.js:1)
    at Object.next (main.c2e649cce333ff00c62f.js:1)
    at d.i [as _next] (main.c2e649cce333ff00c62f.js:1)
    at d.__tryOrUnsub (main.c2e649cce333ff00c62f.js:1)
    at d.next (main.c2e649cce333ff00c62f.js:1)
    at l._next (main.c2e649cce333ff00c62f.js:1)
    at l.next (main.c2e649cce333ff00c62f.js:1)
    at Yh.next (main.c2e649cce333ff00c62f.js:1)
    at Yh.emit (main.c2e649cce333ff00c62f.js:1)
    at main.c2e649cce333ff00c62f.js:1

### Stacktrace
```
alert (webpack:///src/app/core/persistence/database.service.ts:89:12)
Ur (file:///snap/superproductivity/1044/resources/app.asar/dist/main.c2e649cce333ff00c62f.js:1:2684388)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1163:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1275:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:578:34)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:487:20)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
```

### Meta Info
META: SP6.5.0 Electron – el – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1616290325695: [Task] Add time spent 
1616290325699: [Project] Update Work End 
1616290325700: [Tag] Update Work End for Tag 
1616290325704: [Persistence] Save to DB 
1616290325705: [Persistence] Save to DB 
1616290325705: [Persistence] Save to DB 
1616290326695: [Task] Add time spent 
1616290326699: [Project] Update Work End 
1616290326701: [Tag] Update Work End for Tag 
1616290326707: [Persistence] Save to DB 
1616290326707: [Persistence] Save to DB 
1616290326708: [Persistence] Save to DB 
1616290327695: [Task] Add time spent 
1616290327698: [Project] Update Work End 
1616290327700: [Tag] Update Work End for Tag 
1616290327718: [Persistence] Save to DB 
1616290327719: [Persistence] Save to DB 
1616290327720: [Persistence] Save to DB 
1616290328695: [Task] Add time spent 
1616290328699: [Project] Update Work End 
1616290328701: [Tag] Update Work End for Tag 
1616290328715: [Persistence] Save to DB 
1616290328717: [Persistence] Save to DB 
1616290328717: [Persistence] Save to DB 
1616290336019: [Task] Add time spent 
1616290336020: [Project] Update Work End 
1616290336022: [Tag] Update Work End for Tag 
1616290336030: [Persistence] Save to DB 
1616290336031: [Persistence] Save to DB 
1616290336032: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-03-21 15:32
Thank you very much for reporting this. I suppose that this is a duplicate of: #955

**Closed by johannesjo** 2021-03-21 15:32 UTC
