### ISSUE TITLE
error 400 when I want get authorization code from google

### ISSUE THREAD

**Issue by amirdarvishi00** [johannesjo/super-productivity#2393] opened 2023-01-01 09:13 UTC
hello , when I want get authorization code from google response me error 400
and I get this error in linux
![Screenshot from 2023-01-01 04-07-56](https://user-images.githubusercontent.com/44260172/210165954-5ab5891d-5919-46af-9d55-110d46730113.png)
I attached this error picture

**Comment by Ziumper** [comment] 2023-01-03 20:47
hello there, 

I am using windows version and it's really painfull to do it by hand :+1 , so far I am on it looking for modules where the bug is. I will try to build it up from scratch and test it out.

**Comment by mostafa20220** [comment] 2023-01-04 01:48
@AmirmoahammadDarvishi  
Have you found a solution ? 
I have the same issue, although the sync functionality worked fine on my android. 
I use The AUR Version on Arch

**Comment by AmirmoahammadDarvishi** [comment] 2023-01-04 09:36
> @AmirmoahammadDarvishi Have you found a solution ? I have the same issue, although the sync functionality worked fine on my android. I use The AUR Version on Arch

Hello, I use Dropbox for syncing

**Comment by jmiodownik** [comment] 2023-01-04 11:39
confirmed on my end as well: windows environment on google drive looking at the provided link reports:

`Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob `

**Comment by Elkellympia** [comment] 2023-01-05 15:30
> Error 400: invalid_request The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method. Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob

Exact same error here, happened on linux, seems like it could be solved only by the devs.

> ![Screenshot from 2023-01-01 04-07-56](https://user-images.githubusercontent.com/44260172/210165954-5ab5891d-5919-46af-9d55-110d46730113.png)

Here you did not post the resources in the multiple anchors that could help a bunch the devs to solve it, so i will

The More information about this error anchor leads to [this page](https://support.google.com/accounts/answer/12379384)

And below the error details @jmiodownik posted there is also a really important anchor for this porpouse

[Related developer documents](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)

Hope it gives some clarity to the solvers

**Comment by ffcruz85** [comment] 2023-01-09 20:44
Is this not related to issue #2306?

**Comment by johannesjo** [comment] 2023-01-10 17:13
I am closing this as a duplicate of #2306

**Closed by johannesjo** 2023-01-10 17:13 UTC
Labels: bug
