### ISSUE TITLE
Auto-complete/auto-fill tags for tasks

### ISSUE THREAD

**Issue by cokxivawo** [johannesjo/super-productivity#1214] opened 2021-05-16 09:59 UTC
As the title much says, it would be beneficial if tags  for tasks could be auto-completed/auto-filled which was input before once.

**Comment by johannesjo** [comment] 2021-05-16 11:42
Hello there! Thank you very much for opening this up. Could you maybe provide a a little bit more detailed example of what you mean?

**Comment by cokxivawo** [comment] 2021-05-16 12:13
> Hello there! Thank you very much for opening this up. Could you maybe provide a a little bit more detailed example of what you mean?

My request is as follows: 
1. Create a task with the tag named “# tag A”.
2. Afterward when creating another task, just typing “# t” automatically displays “# tag A” as suggestion.

Hope this makes sense.

**Comment by johannesjo** [comment] 2021-05-16 12:23
Ah, now I understood. Thanks!  Looks like a duplicate of #903

**Closed by johannesjo** 2021-05-16 12:23 UTC
Labels: enhancement
