### ISSUE TITLE
Auto-Conversion of Hashtag-Prefixed Tags to Avoid Duplicates

### ISSUE THREAD

**Issue by tempookian** [johannesjo/super-productivity#3035] opened 2024-02-14 09:55 UTC
## Problem Statement
Currently, when adding tags in the Superproductivity app, if a user prefixes a tag with a hashtag (e.g., "#urgent"), the app creates a new tag (e.g., "#urgent") instead of recognizing it as an existing tag without a hashtag (e.g., "urgent"). This leads to the creation of duplicate, unwanted tags.

![image](https://github.com/johannesjo/super-productivity/assets/124298725/4b7dc0cb-89a2-4c3e-9e4c-64cb0b1d6a24)

## :grey_question: Possible Solution
Implement a feature that automatically strips the hashtag from a tag name when entered (e.g., "#urgent" becomes "urgent"), and then matches it to an existing tag if one exists, to prevent the creation of duplicate tags.

## :arrow_heading_up: Describe alternatives you've considered
An alternative could be a warning or prompt that informs users when they are about to create a tag with a hashtag that matches an existing tag, giving the option to merge with the existing tag or create a new one.

## :heavy_plus_sign: Additional context
I appreciate the functionality and user-friendliness of the Superproductivity app. This tag management improvement could enhance user experience and efficiency. Thank you for considering this feature request.

**Comment by Jagdfalke** [comment] 2024-02-14 13:53
I am confused. What version do you use and what OS are you on? I cannot reproduce your described behaviour with 8.0.0 (neither on Windows nor on Android). If I use the syntax #hashtag a task is always assigned to the existing hastag.

**Comment by johannesjo** [comment] 2024-02-16 09:55
I am also unable to reproduce this. Thanks for checking @Jagdfalke !!

**Comment by tempookian** [comment] 2024-02-19 08:31
Thank you @johannesjo and @Jagdfalke for checking and my apologies for not being clear enough. I'm using Version 8.0.0 on Linux and here are the steps to reproduce the behavior:

1. Launch the app.
2. Navigate to the 'Today' tab.
3. Right-click on a task.
4. Select 'Edit Tags'.
5. Enter a hashtag-prefixed tag, such as `#urgent`, rather than 'urgent'.

**Observed Behavior:**
The system creates a new tag `#urgent`.

**Suggested Behavior:**
Prevent the prefix `#` from being added to the beginning of the tag. Instead:
- Create a new tag if it does not already exist.
- If the tag exists, utilize the existing one.

**Comment by Jagdfalke** [comment] 2024-02-19 16:54
Thanks for your clarification. With your detailed description I could reproduce your observed behavior. To be honest, I've never run into this situation, but I second your opinion that it would be better if the hashtag would be ignored in this case.

**Closed** 2024-03-28 18:05 UTC
Labels: enhancement
