### ISSUE TITLE
[BUG: Pop OS Linux 20.10] Can't sync with google drive

### ISSUE THREAD

**Issue by dodalovic** [johannesjo/super-productivity#893] opened 2021-02-10 20:28 UTC
Pop OS Linux, freshly installed the latest `.deb` package today

### Stacktrace
```
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:292:12)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581546)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581291)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3588121)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///opt/superProductivity/resources/app.asar/dist/main.328417deb207573139f4.js:1:3581348)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

### Meta Info
META: SP6.4.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1612988569829: [SP_ALL] Load(import) all data 
1612988569831: [SP_ALL] All Data was loaded 
1612988569836: [WorkContext] Set Active Work Context 
1612988569855: [Task] SetSelectedTask 
1612988584512: [Global Config] Update Global Config Section 
1612988584520: [Persistence] Save to DB 
1612988588517: [Global Config] Update Global Config Section 
1612988588521: [Persistence] Save to DB 
1612988596192: [Global Config] Update Global Config Section 
1612988596200: [Persistence] Save to DB 
1612988735597: [Global Config] Update Global Config Section 
1612988735619: [Persistence] Save to DB 
1612988807953: [Global Config] Update Global Config Section 
1612988807959: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-02-10 21:17
Thanks for opening this up. Could you maybe provide a little bit more context?

**Comment by dodalovic** [comment] 2021-02-10 21:36
Just installed the `.deb` and wanted to enable google sync. I pasted the token and the got upper error.

**Comment by johannesjo** [comment] 2021-02-11 08:55
Ok thanks!

**Comment by johannesjo** [comment] 2021-02-11 08:58
Hm, are you sure that was the error message? Because there is no place in the app that could throw this exact message...

**Comment by dodalovic** [comment] 2021-02-11 10:26
If I recall correctly, I just used the OOB report bug option 🤷

**Comment by johannesjo** [comment] 2021-02-11 19:06
Looks like a duplicate of  #720  at least that's the error referenced in the logs above.

**Closed by johannesjo** 2021-02-11 19:06 UTC
