### ISSUE TITLE
Add an option to Repeat every 2 weeks, every month, two months, or every year on Repeatable tasks

### ISSUE THREAD

**Issue by JLuisGT** [johannesjo/super-productivity#1342] opened 2021-07-04 21:49 UTC
## Problem Statement
Add an option to Repeat every 2 weeks, every month, two months, or every year on Repeatable tasks

**Comment by johannesjo** [comment] 2021-07-05 11:39
Thanks for opening this up. Looks like a duplicate of #948

**Closed by johannesjo** 2021-07-05 11:39 UTC
Labels: enhancement
