### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by konami12** [johannesjo/super-productivity#3278] opened 2024-07-20 21:54 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Browser – es-419 – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

### Stacktrace
```
show (https://app.super-productivity.com/src/app/features/shepherd/shepherd-steps.const.ts:540:38)
focus (https://app.super-productivity.com/src/app/features/shepherd/shepherd.service.ts:115:10)
isUndefined (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:189:16)
isUndefined (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:182:27)
this._styleTargetElementForStep (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:3872:9)
isFunction (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:3711:32)
isFunction (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:4448:13)
this.steps.indexOf (https://app.super-productivity.com/node_modules/shepherd.js/dist/js/shepherd.esm.js:4398:11)
next (https://app.super-productivity.com/src/app/features/shepherd/shepherd.service.ts:80:15)
```

### Actions Before Error
```
1721512356057: [Persistence] Save to DB (3) 
1721512357050: [Task] Add time spent 
1721512357052: [Project] Update Work End 
1721512357054: [Tag] Update Work End for Tag 
1721512357056: [Persistence] Save to DB (3) 
1721512358050: [Task] Add time spent 
1721512358053: [Project] Update Work End 
1721512358055: [Tag] Update Work End for Tag 
1721512358058: [Persistence] Save to DB (3) 
1721512358135: [Task] Toggle start 
1721512358138: [Persistence] Save to DB 
1721512358138: [Task] UnsetCurrentTask 
1721512362803: [Task] SetSelectedTask 
1721512362805: [Layout] Hide Notes 
1721512372823: [Task] Update Task 
1721512372827: [Persistence] Save to DB 
1721512375336: [Task] SetSelectedTask 
1721512380805: [Task] Update Task 
1721512380814: [Persistence] Save to DB 
1721512385599: [Task] Update Task 
1721512385701: [Persistence] Save to DB 
1721512390435: [Task] Update Task 
1721512390437: [Persistence] Save to DB 
1721512404364: [Task] Update Task 
1721512404370: [Persistence] Save to DB 
1721512407027: [Task] Update Task 
1721512407029: [Persistence] Save to DB 
1721512439135: [Task] Delete Task 
1721512439148: [Persistence] Save to DB (3) 
1721512439148: [Task] UnsetCurrentTask
```

**Comment by johannesjo** [comment] 2024-07-22 06:42
Seems to be a duplicate of #3270

**Closed by johannesjo** 2024-07-22 06:42 UTC
