### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by mr-ravi** [johannesjo/super-productivity#1316] opened 2021-06-23 05:13 UTC
### Steps to Reproduce

1. Add new task in a project. Edit description while timer is not started for any task.
2. When pop-up comes to add the 5 min. time span, select the currently added new task.
3. App crashes in sometime!

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1255/resources/app.asar/dist/main.8a98c7fb049add531aaa.js:1:2336736)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
```

### Meta Info
META: SP7.0.3 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.3 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

### Actions Before Error
```
1624424581744: [Persistence] Save to DB 
1624424581745: [Persistence] Save to DB 
1624424581746: [Persistence] Save to DB 
1624424581746: [Persistence] Save to DB 
1624424582711: [Task] Add time spent 
1624424582715: [Project] Update Work End 
1624424582721: [Tag] Update Work End for Tag 
1624424582725: [Tag] Update Work End for Tag 
1624424582731: [Persistence] Save to DB 
1624424582731: [Persistence] Save to DB 
1624424582732: [Persistence] Save to DB 
1624424582732: [Persistence] Save to DB 
1624424583710: [Task] Add time spent 
1624424583713: [Project] Update Work End 
1624424583720: [Tag] Update Work End for Tag 
1624424583724: [Tag] Update Work End for Tag 
1624424583729: [Persistence] Save to DB 
1624424583729: [Persistence] Save to DB 
1624424583730: [Persistence] Save to DB 
1624424583730: [Persistence] Save to DB 
1624424585279: [Task] Update Task 
1624424585281: [Persistence] Save to DB 
1624424585316: [Task] Add time spent 
1624424585318: [Project] Update Work End 
1624424585325: [Tag] Update Work End for Tag 
1624424585332: [Tag] Update Work End for Tag 
1624424585337: [Persistence] Save to DB 
1624424585338: [Persistence] Save to DB 
1624424585338: [Persistence] Save to DB 
1624424585339: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-23 07:56
Thanks for reporting. Looks like a duplicate of #816

**Closed** 2021-06-23 11:50 UTC
