### ISSUE TITLE
Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by MichaelTunnell** [johannesjo/super-productivity#553] opened 2020-09-30 07:20 UTC
### Steps to Reproduce
1. I was just using the app as normal with adding and updating tasks on my today list

### Error Log (Desktop only)
no log file in my snap folder for the app

Extra info: Linux -> Manjaro KDE -> installed via Snap

### Console Output
main.85c5718eafb26d401081.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (main.85c5718eafb26d401081.js:1)
    at Proxy.o (main.85c5718eafb26d401081.js:1)
    at t.<anonymous> (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1
    at Object.next (main.85c5718eafb26d401081.js:1)
    at a (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at S (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at s (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.85c5718eafb26d401081.js:1)
t.handleError @ main.85c5718eafb26d401081.js:1

Uncaught Error: Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (main.85c5718eafb26d401081.js:1)
    at Proxy.o (main.85c5718eafb26d401081.js:1)
    at t.<anonymous> (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1
    at Object.next (main.85c5718eafb26d401081.js:1)
    at a (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at t.handleError (main.85c5718eafb26d401081.js:1)
    at Object.next (main.85c5718eafb26d401081.js:1)
    at e.o [as _next] (main.85c5718eafb26d401081.js:1)
    at e.__tryOrUnsub (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e._next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.emit (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1

### Stacktrace
```
function (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:150:25)
function (webpack:///node_modules/idb/build/esm/index.js:65:24)
constructor (webpack:///src/app/core/persistence/database.service.ts:44:49)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2570402)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2570507)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2569245)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
```

### Meta Info
META: SP5.6.5 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1601449618762: [Layout] Hide AddTaskBar 
1601449660060: [Layout] Toggle AddTaskBar 
1601449665256: [Task][Issue] Add Task 
1601449672116: [Task][Issue] Add Task 
1601449678583: [Task][Issue] Add Task 
1601449683651: [Task][Issue] Add Task 
1601449687850: [Task][Issue] Add Task 
1601449693167: [Task][Issue] Add Task 
1601449697550: [Layout] Hide AddTaskBar 
1601449700015: [Task] Update Task 
1601449701741: [Task] Update Task 
1601449702249: [Task] Update Task 
1601449702982: [Task] Update Task 
1601449703489: [Task] Update Task 
1601449704049: [Task] Update Task 
1601449704521: [Task] Update Task 
1601449715153: [Layout] Toggle AddTaskBar 
1601449722025: [Task][Issue] Add Task 
1601449730909: [Task][Issue] Add Task 
1601449742124: [Task][Issue] Add Task 
1601449752027: [Task][Issue] Add Task 
1601449753367: [Layout] Hide AddTaskBar 
1601449768056: [Task] Update Task 
1601449775480: [Task] Update Task 
1601449783648: [Task] Update Task
```

**Comment by MichaelTunnell** [comment] 2020-09-30 07:24
## Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.Error: UnknownError: Internal error opening backing store for indexedDB.open.    at t.

### Steps to Reproduce
1. I tried the Reload App button and the it errored on this as well.

### Console Output
Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.

GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.
Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at t.<anonymous> (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1
    at Object.throw (main.85c5718eafb26d401081.js:1)
    at s (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at S (polyfills.aebe8ecc43d658291381.js:1)
    at S (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.85c5718eafb26d401081.js:1)
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at e.runTask (polyfills.aebe8ecc43d658291381.js:1)
    at b (polyfills.aebe8ecc43d658291381.js:1)
    at e.invokeTask [as invoke] (polyfills.aebe8ecc43d658291381.js:1)
    at p (polyfills.aebe8ecc43d658291381.js:1)

Uncaught Error: Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.
Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at t.<anonymous> (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1
    at Object.throw (main.85c5718eafb26d401081.js:1)
    at s (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at t.handleError (main.85c5718eafb26d401081.js:1)
    at Object.next (main.85c5718eafb26d401081.js:1)
    at e.o [as _next] (main.85c5718eafb26d401081.js:1)
    at e.__tryOrUnsub (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e._next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.emit (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1

### Stacktrace
```
alert (webpack:///src/app/core/persistence/database.service.ts:80:12)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2570402)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2570507)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:2569296)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:20)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:20)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:38)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:507:24)
callback (webpack:///node_modules/zone.js/dist/zone.js:1671:17)
```

### Meta Info
META: SP5.6.5 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1601449618762: [Layout] Hide AddTaskBar 
1601449660060: [Layout] Toggle AddTaskBar 
1601449665256: [Task][Issue] Add Task 
1601449672116: [Task][Issue] Add Task 
1601449678583: [Task][Issue] Add Task 
1601449683651: [Task][Issue] Add Task 
1601449687850: [Task][Issue] Add Task 
1601449693167: [Task][Issue] Add Task 
1601449697550: [Layout] Hide AddTaskBar 
1601449700015: [Task] Update Task 
1601449701741: [Task] Update Task 
1601449702249: [Task] Update Task 
1601449702982: [Task] Update Task 
1601449703489: [Task] Update Task 
1601449704049: [Task] Update Task 
1601449704521: [Task] Update Task 
1601449715153: [Layout] Toggle AddTaskBar 
1601449722025: [Task][Issue] Add Task 
1601449730909: [Task][Issue] Add Task 
1601449742124: [Task][Issue] Add Task 
1601449752027: [Task][Issue] Add Task 
1601449753367: [Layout] Hide AddTaskBar 
1601449768056: [Task] Update Task 
1601449775480: [Task] Update Task 
1601449783648: [Task] Update Task
```

**Comment by MichaelTunnell** [comment] 2020-09-30 07:26
I closed the app and then restarted it. The app is now working again but I did lose a few hours of task logs. Not a deal breaker but certainly unfortunate.

**Comment by johannesjo** [comment] 2020-09-30 09:00
Hey Michael! Thanks for reporting this! Unfortunately, these IndexedDB errors keep popping up for some people from time to time. I am very sorry that you lost some data. I'm working on a solution, but it's tricky because I am unable to reproduce this. It's likely happening because some external process is blocking write access for the database.

When such an error pops up I recommend checking your backup folder immediately. Usually the file there shouldn't be older than a couple of minutes and should be able to import it without a problem.

**Comment by johannesjo** [comment] 2020-10-02 20:15
May I ask how you did lose a couple of hours of data? Did you import a backup? Was the backup from the current day or the day before?


I thought about and experimented with this quite a bit in the past and I've come to the following conclusions:

1. IndexedDB does this from time to time and has been for a long time and probably will be for some time to come
2. The errors appear for some people more often than others but overall happen rarely
3. Replacing IndexedDB with another custom solution will probably introduce new problems
4. For the browser version IndexedDB will always (for a long time) be the only viable option

Because of these conclusions, I think the best overall path to go would be to stick with IndexedDB but to provide a better solution for restoring data more easily when restarting the app.

**Comment by johannesjo** [comment] 2020-10-18 20:41
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!

**Closed by johannesjo** 2020-10-18 20:41 UTC
Labels: bug, db
