### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by arinnn3** [johannesjo/super-productivity#1743] opened 2021-12-07 16:14 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638888732774: [Tag] Update Work End for Tag (2) 
1638888732805: [Persistence] Save to DB (3) 
1638888738262: [Task] Add time spent 
1638888738276: [Tag] Update Work End for Tag (2) 
1638888738289: [Persistence] Save to DB (3) 
1638888745840: [Task] Add time spent 
1638888745856: [Tag] Update Work End for Tag (2) 
1638888745868: [Persistence] Save to DB (3) 
1638888753403: [Task] Add time spent 
1638888753419: [Tag] Update Work End for Tag (2) 
1638888753433: [Persistence] Save to DB (3) 
1638888761858: [Task] Add time spent 
1638888761872: [Tag] Update Work End for Tag (2) 
1638888761887: [Persistence] Save to DB (3) 
1638888773516: [Task] Add time spent 
1638888773532: [Tag] Update Work End for Tag (2) 
1638888773545: [Persistence] Save to DB (3) 
1638888781322: [Task] Add time spent 
1638888781338: [Tag] Update Work End for Tag (2) 
1638888781359: [Persistence] Save to DB (3) 
1638888789974: [Task] Add time spent 
1638888789989: [Tag] Update Work End for Tag (2) 
1638888790004: [Persistence] Save to DB (3) 
1638893610740: [Pomodoro] Finish Pomodoro Session 
1638893610753: [Task] UnsetCurrentTask 
1638893620966: [Idle] Trigger Idle 
1638893620967: [Idle] Set idle time 
1638893621734: [Idle] Trigger Idle (2) 
1638893627352: [Idle] Set idle time (6)
```

**Comment by johannesjo** [comment] 2021-12-09 09:55
Thank you for opening this up! Looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-09 09:55 UTC
