### ISSUE TITLE
Error: No tag TODAY

### ISSUE THREAD

**Issue by asimove** [johannesjo/super-productivity#615] opened 2020-10-27 07:48 UTC
### Steps to Reproduce

1. Version 6;01
2.No Today Tag  at Startup with Desktop Version
3. and Microsoft Edge
4.

### Stacktrace
```
webpack:///src/app/features/tag/store/tag.reducer.ts:46:12
function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1096:29)
memoized (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1011:38)
args (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1059:38)
function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1105:35)
memoized (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1011:38)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:868:24)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
```

### Meta Info
META: SP6.0.1 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.0.1 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36

### Actions Before Error
```
1603728265690: [Task][Issue] Add Task 
1603728265710: [Persistence] Save to DB 
1603728265711: [Persistence] Save to DB 
1603728265712: [Persistence] Save to DB 
1603728265713: [TaskRepeatCfg] Update TaskRepeatCfg 
1603728265715: [Persistence] Save to DB 
1603728265719: [Task][Issue] Add Task 
1603728265747: [Persistence] Save to DB 
1603728265749: [Persistence] Save to DB 
1603728265750: [Persistence] Save to DB 
1603728265752: [TaskRepeatCfg] Update TaskRepeatCfg 
1603728265753: [Persistence] Save to DB 
1603728265760: [Task][Issue] Add Task 
1603728265767: [Persistence] Save to DB 
1603728265767: [Persistence] Save to DB 
1603728265768: [Persistence] Save to DB 
1603728265769: [TaskRepeatCfg] Update TaskRepeatCfg 
1603728265771: [Persistence] Save to DB 
1603728265775: [Task][Issue] Add Task 
1603728265788: [Persistence] Save to DB 
1603728265790: [Persistence] Save to DB 
1603728265791: [Persistence] Save to DB 
1603728265793: [TaskRepeatCfg] Update TaskRepeatCfg 
1603728265794: [Persistence] Save to DB 
1603728265799: [Task][Issue] Add Task 
1603728265802: [Persistence] Save to DB 
1603728265802: [Persistence] Save to DB 
1603728265803: [Persistence] Save to DB 
1603728265804: [TaskRepeatCfg] Update TaskRepeatCfg 
1603728265805: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2020-10-27 12:17
Thank you very much for reporting. I am closing this as duplicate of #600 .

**Comment by johannesjo** [comment] 2020-10-28 10:45
I am reopening this in favor of #600, because that seems to be resolved... Thank you very much for sending me your data! Does this happen consistently or did it only happen once? When I import your data into the windows store version, everything works fine. If applicable, does this happen after the initial sync is done, or right away?

**Comment by asimove** [comment] 2020-10-28 12:06
Hello,

This happens after the initial synchronization. Just before I see a little
bit Today, after loading, the error happens.

Careful, I don't load the Windows Store but the site:
https://www.softpedia.com/.../Super-Productivity.shtml

Pascal Bras
Avenue Notre Dame de Lourdes, 66
1090 Bruxelles
Phone: +3224286009
Mobile: +32492135309



Le mer. 28 oct. 2020 à 11:45, Johannes Millan <notifications@github.com> a
écrit :

**Comment by johannesjo** [comment] 2020-10-28 12:21
What you might try for now (I think I found a possible fix, but the release will take some time) is to delete all user data for the app (probably located under `C:\Users\YOUR_USER_NAME\AppData\Roaming\superProductivity`). And to re-import the backups you send to me. Probably makes sense to make a backup of `C:\Users\YOUR_USER_NAME\AppData\Roaming\superProductivity` before that.

**Comment by asimove** [comment] 2020-10-28 13:37
Hello,

OK, it works. Thank you very much.

Pascal Bras
Avenue Notre Dame de Lourdes, 66
1090 Bruxelles
Phone: +3224286009
Mobile: +32492135309



Le mer. 28 oct. 2020 à 13:21, Johannes Millan <notifications@github.com> a
écrit :

**Comment by johannesjo** [comment] 2020-10-28 14:05
Thanks for reporting back! Btw. your email signature shows up here, just in case you want to remove it form here.

**Closed by johannesjo** 2020-10-28 14:05 UTC
