### ISSUE TITLE
Error - stop while timing task (New user)

### ISSUE THREAD

**Issue by etschmidt60** [johannesjo/super-productivity#399] opened 2020-06-11 21:38 UTC
Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open.Error: UnknownError: Internal error opening backing store for indexedDB.open.    at t. (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:76:13)    at file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007330    at Object.throw (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007435)    at apply (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2006224)    at t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)    at Object.onInvoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)    at t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)    at e.run (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)    at apply (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)    at t.invokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
META: SP5.3.4 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.4 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
t.<anonymous> (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:76:13)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007330)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007435)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2006224)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
resolvePromise (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
resolvePromise (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:784:21)
apply (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:894:21)
t.invokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
t.invokeTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
drainMicroTaskQueue (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:601:39)
e.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:507:25)
p (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
```

**Comment by johannesjo** [comment] 2020-06-11 21:46
Thank you very much for reporting! Could you provide a little bit more info on what happened exactly before the error occurred?

Probably a duplicate of #375.

**Closed by johannesjo** 2020-06-11 21:46 UTC
Labels: bug

**Comment by etschmidt60** [comment] 2020-06-12 01:14
I had started the timing of a task (I had identified two projects). I was working on a LibreOffice document and I noticed that the app had the error message. I do not think I was doing anything unusual.

**Comment by johannesjo** [comment] 2020-06-12 09:25
@etschmidt60 Thank you. This seems to be happening to some users sometimes. I am really not sure why, as I never was able to reproduce this. Common reasons for database issues might be:

1. Running multiple instances of the app
2. Not enough disk space

But if it is not that I am still in the dark.
