### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by Jironymo** [johannesjo/super-productivity#1261] opened 2021-06-01 19:31 UTC
### Steps to Reproduce

1. Do nothing actively (presumably wait for a sync).
2. Sync?
3. Enjoy a bug.

### Error Log (Desktop only)

Couldn't find the log file.

### Console Output

[Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
page_view:1 
Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:2684500)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
```

### Meta Info
META: SP6.5.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1622575474761: [Persistence] Save to DB 
1622575474763: [Persistence] Save to DB 
1622575490741: [Task] Add time spent 
1622575490749: [Project] Update Work End 
1622575490784: [Persistence] Save to DB 
1622575490786: [Persistence] Save to DB 
1622575501740: [Task] Add time spent 
1622575501748: [Project] Update Work End 
1622575501777: [Persistence] Save to DB 
1622575501780: [Persistence] Save to DB 
1622575530740: [Task] Add time spent 
1622575530749: [Project] Update Work End 
1622575530778: [Persistence] Save to DB 
1622575530782: [Persistence] Save to DB 
1622575545743: [Task] Add time spent 
1622575545750: [Project] Update Work End 
1622575545777: [Persistence] Save to DB 
1622575545779: [Persistence] Save to DB 
1622575560743: [Task] Add time spent 
1622575560745: [Project] Update Work End 
1622575560764: [Persistence] Save to DB 
1622575560766: [Persistence] Save to DB 
1622575570747: [Task] Add time spent 
1622575570754: [Project] Update Work End 
1622575570780: [Persistence] Save to DB 
1622575570781: [Persistence] Save to DB 
1622575582410: [Task] Add time spent 
1622575582414: [Project] Update Work End 
1622575582439: [Persistence] Save to DB 
1622575582441: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-06-02 08:16
Duplicate of #398

**Closed by johannesjo** 2021-06-02 08:16 UTC
