### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of nullTypeError

### ISSUE THREAD

**Issue by BlueBayliss** [johannesjo/super-productivity#1445] opened 2021-08-10 17:57 UTC
### Steps to Reproduce
1. I run Super Productivity as a progressive web app from Chrome
2. I have several Super Productivity Projects set up pointing to the same Jira Project
2. I was adding stories from Jira to their respective projects in Super Productivity
3. One of the projects was not retrieving any stories when I searched so I had Super Productivity validate my Jira credentials and I verified the search filters I'd put for the product in Super Productivity compared to a working product to make sure they were set up the same. I am not sure of the specific order of events here and I did go back and forth between projects for a bit. No settings were actually changed because everything at this point looked like it was still set up correctly.
4. Went back to the broken project and got this or a similar error when clicking Settings from the 3 dot menu on the project name and got this or a similar error
5. Now I can't go to any project's settings without getting an error. Reloading the app from the error window immediately pops up the error again. Closing and restarting the app lets me work normally, but I can't access the project specific settings anymore.

### Error Log (Desktop only)
Not available

### Console Output
```
task.reducer.ts:91 @ngrx/store/update-reducers Object
task.reducer.ts:91 @ngrx/effects/init Object
task.reducer.ts:91 @ngrx/store/update-reducers Object
main.ts:23 Registering Service worker
app.component.ts:287 Persistence already allowed
app.component.ts:316 17 out of 585116 MiB used (0%)
frontendInterface.bundle.js:97 SPEX injected
chrome-extension-interface.service.ts:23 SUCCESS Super Productivity Extension found and loaded.
frontendInterface.bundle.js:77 SP-EXT: Content Script Injection blocked. Reinitializing...
17 @ frontendInterface.bundle.js:77
frontendInterface.bundle.js:97 SPEX injected
model-version.ts:34 Migrating model "GlobalConfig" to version from 2.2003 to 2.2005 Object
migrate-global-config.util.ts:112 EXTEND globalConfig sync localFileSync Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 Object
model-version.ts:34 Migrating model "GlobalConfig" to version from 2.2003 to 2.2005 Object
migrate-global-config.util.ts:112 EXTEND globalConfig sync localFileSync Object
model-version.ts:34 Migrating model "Improvement" to version from undefined to 1 Object
model-version.ts:34 Migrating model "Obstruction" to version from undefined to 1 Object
task.reducer.ts:91 [SP_ALL] Load(import) all data Object
task.reducer.ts:91 [SP_ALL] All Data was loaded Object
migrate-metric.service.ts:37 Migrating Legacy Metric State to new model
migrate-metric.service.ts:38 metricMigration: 1 Object
task.reducer.ts:91 [WorkContext] Set Active Work Context Object
task.reducer.ts:91 [Task] SetSelectedTask Object
global-error-handler.class.ts:36 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (jira-cfg.component.ts:190)
    at t._setTriggerValue (autocomplete.js:708)
    at autocomplete.js:566
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
    at b (zone.js:1213)
    at zone.js:1283
    at l.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
    at l.invokeTask (zone.js:405)
    at t.runTask (zone.js:178)
    at m (zone.js:582)
(anonymous) @ global-error-handler.class.ts:36
action-logger.ts:30 Last actions before error: Array(30)
global-error-handler.class.ts:80 t
global-error-handler.util.ts:115 Object
zone.js:1063 Unhandled Promise rejection: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3128589)
    at t._setTriggerValue (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:2124720)
    at https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:2122653
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6540)
    at Object.onInvoke (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:142498)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6480)
    at t.run (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:1939)
    at https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:16715
    at l.invokeTask (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:7158)
    at Object.onInvokeTask (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:142314) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (jira-cfg.component.ts:190)
    at t._setTriggerValue (autocomplete.js:708)
    at autocomplete.js:566
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
    at t.<anonymous> (global-error-handler.class.ts:63)
    at Generator.next (<anonymous>)
    at o (global-error-handler.util.ts:215)
    at l.invoke (zone.js:372)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at t.runTask (zone.js:178)
    at m (zone.js:582) Error: Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3128589)
    at t._setTriggerValue (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:2124720)
    at https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:2122653
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6540)
    at Object.onInvoke (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:142498)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6480)
    at t.run (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:1939)
    at https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:16715
    at l.invokeTask (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:7158)
    at Object.onInvokeTask (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:142314)
    at t.<anonymous> (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3532609)
    at Generator.next (<anonymous>)
    at o (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3529938)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6540)
    at t.run (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:1939)
    at https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:16715
    at l.invokeTask (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:7158)
    at t.runTask (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:2554)
    at m (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:9152)
n.onUnhandledError @ zone.js:1063
frontendInterface.bundle.js:77 SP-EXT: Content Script Injection blocked. Reinitializing...
17 @ frontendInterface.bundle.js:77
frontendInterface.bundle.js:97 SPEX injected
2jira-api.service.ts:601 Jira: Response Request ID not existing myself__GET__mO-KhVTan
_handleResponse @ jira-api.service.ts:601
task.reducer.ts:91 [Note] Load Note State Object
task.reducer.ts:91 [Bookmark] Load Bookmark State Object
task.reducer.ts:91 [Project] Load Project related Data Success Object
task.reducer.ts:91 [Improvement] Clear Hidden Improvements bk
task.reducer.ts:91 [Improvement] Delete multiple Improvements Object
```

### Stacktrace
```
submit (webpack:///src/app/features/issue/providers/jira/jira-view-components/jira-cfg/jira-cfg.component.ts:190:17)
_setTriggerValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:708:30)
writeValue (webpack:///node_modules/@angular/material/fesm2015/autocomplete.js:566:46)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
resolvePromise (webpack:///node_modules/zone.js/fesm2015/zone.js:1283:16)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:582:34)
task.zone.runTask (webpack:///node_modules/zone.js/fesm2015/zone.js:491:20)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1600:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1626:16)
```

### Meta Info
META: SP7.5.0 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

### Actions Before Error
```
1628616463403: [Task] Add time spent 
1628616463404: [Tag] Update Work End for Tag 
1628616463407: [Persistence] Save to DB 
1628616463407: [Persistence] Save to DB 
1628616464405: [Task] Add time spent 
1628616464407: [Tag] Update Work End for Tag 
1628616464412: [Persistence] Save to DB 
1628616464412: [Persistence] Save to DB 
1628616471586: [SP_ALL] Load(import) all data 
1628616471587: [SP_ALL] All Data was loaded 
1628616480055: [Task] SetCurrentTask 
1628616480404: [Task] Add time spent 
1628616480406: [Tag] Update Work End for Tag 
1628616480411: [Persistence] Save to DB 
1628616480412: [Persistence] Save to DB 
1628616481149: [WorkContext] Set Active Work Context 
1628616481197: [Task] SetSelectedTask 
1628616481379: [Note] Load Note State 
1628616481380: [Bookmark] Load Bookmark State 
1628616481381: [Project] Load Project related Data Success 
1628616481381: [Improvement] Clear Hidden Improvements 
1628616481382: [Improvement] Delete multiple Improvements 
1628616481402: [Task] Add time spent 
1628616481404: [Tag] Update Work End for Tag 
1628616481409: [Persistence] Save to DB 
1628616481409: [Persistence] Save to DB 
1628616482403: [Task] Add time spent 
1628616482405: [Tag] Update Work End for Tag 
1628616482419: [Persistence] Save to DB 
1628616482420: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-08-16 18:02
I am closing this as a duplicate of #1441

**Closed** 2021-08-16 18:02 UTC
Labels: bug
