### ISSUE TITLE
Error: DOMException: AbortError: The transaction was aborted, so the request cannot be fulfilled.

### ISSUE THREAD

**Issue by Nootaku** [johannesjo/super-productivity#452] opened 2020-07-24 12:33 UTC
### Steps to Reproduce
Don't know, sorry. It was in the background and suddenly ... poof.
I am on Ubuntu 18.04 with a Budgie DE.

### Error Log (Desktop only)

```
resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
reject (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21)
IDBTransaction.apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/idb/build/esm/wrap-idb-value.js:77:13)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
e.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38)
invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
IDBTransaction.h (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1697:21)
```

### Console Output

```
main.59aec93a65eb7bb777cb.js:1 GLOBAL_ERROR_HANDLER DOMException: The transaction was aborted, so the request cannot be fulfilled.
t.handleError @ main.59aec93a65eb7bb777cb.js:1
main.59aec93a65eb7bb777cb.js:1 META: SP5.4.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.2 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36
main.59aec93a65eb7bb777cb.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): UnknownError: Connection is closing.
    at resolvePromise (webpack:/node_modules/zone.js/dist/zone.js:832)
    at reject (webpack:/node_modules/zone.js/dist/zone.js:739)
    at IDBTransaction.apply (webpack:/node_modules/idb/build/esm/wrap-idb-value.js:77)
    at t.invokeTask (webpack:/node_modules/zone.js/dist/zone.js:421)
    at Object.onInvokeTask (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122)
    at t.invokeTask (webpack:/node_modules/zone.js/dist/zone.js:420)
    at e.runTask (webpack:/node_modules/zone.js/dist/zone.js:188)
    at e.invoke (webpack:/node_modules/zone.js/dist/zone.js:503)
    at invokeTask (webpack:/node_modules/zone.js/dist/zone.js:1671)
    at IDBTransaction.h (webpack:/node_modules/zone.js/dist/zone.js:1697)
t.handleError @ main.59aec93a65eb7bb777cb.js:1
main.59aec93a65eb7bb777cb.js:1 META: SP5.4.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.2 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36
polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: Uncaught (in promise): UnknownError: Connection is closing.
    at t.handleError (webpack:/src/app/core/error-handler/global-error-handler.class.ts:55)
    at Object.next (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28692)
    at e.call [as _next] (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:25506)
    at e.__tryOrUnsub (webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192)
    at e.next (webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:130)
    at e._next (webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:76)
    at e.next (webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53)
    at e.call (webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47)
    at emit (webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:25488)
    at webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28157
e.runTask @ polyfills.aebe8ecc43d658291381.js:1
e.invokeTask @ polyfills.aebe8ecc43d658291381.js:1
invoke @ polyfills.aebe8ecc43d658291381.js:1
n.args.<computed> @ polyfills.aebe8ecc43d658291381.js:1
webpack:/node_modules/zone.js/dist/zone.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
webpack:/node_modules/idb/build/esm/wrap-idb-value.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.59aec93a65eb7bb777cb.js:1 resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
reject (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21)
IDBTransaction.apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/idb/build/esm/wrap-idb-value.js:77:13)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
e.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38)
invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
IDBTransaction.h (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1697:21)
main.59aec93a65eb7bb777cb.js:1 <a href=​"https:​/​/​github.com/​johannesjo/​super-productivity/​issues/​new?body=%23…ror%3A+Uncaught+%28in+promise%29%3A+UnknownError%3A+Connection+is+closing." id=​"github-issue-url" target=​"_blank">​! Please copy & report !​</a>​
webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/lz.e07ab30fff20ee5a3b30.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/reminder.d61ebebcd6923ff4a0b4.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/styles.27a7e300d4e11fa96b14.css.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/runtime.c51bd5b1c616d9ffddc1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/686/resources/app.asar/dist/main.59aec93a65eb7bb777cb.js.map: 
```

### Stacktrace
```
resolvePromise (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
reject (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:739:21)
IDBTransaction.apply (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/idb/build/esm/wrap-idb-value.js:77:13)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28122:33)
t.invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
e.invoke (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38)
invokeTask (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)
IDBTransaction.h (file:///snap/superproductivity/686/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1697:21)
```

### Meta Info
META: SP5.4.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.4.2 Chrome/83.0.4103.104 Electron/9.0.4 Safari/537.36

**Comment by johannesjo** [comment] 2020-07-24 12:36
Thanks for reporting. Seems to me that this being caused by IndexedDB. I will work on replacing it with another persistence solution for the Elctron version when I have the time.

**Comment by johannesjo** [comment] 2020-08-06 20:35
I am closing this as duplicate of #401.

**Closed** 2020-08-06 20:36 UTC
Labels: bug, db
