### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by fillswim** [johannesjo/super-productivity#1733] opened 2021-12-05 04:14 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – ru – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638640607129: [Idle] Set idle time 
1638641550183: [Idle] Trigger Idle 
1638641550196: [Idle] Set idle time 
1638641573036: [Idle] Trigger Idle 
1638641575850: [Idle] Set idle time 
1638642520768: [Idle] Trigger Idle 
1638642520773: [Idle] Set idle time 
1638642529110: [Idle] Trigger Idle 
1638642585136: [Idle] Set idle time (2) 
1638643487477: [Idle] Trigger Idle 
1638643487618: [Idle] Set idle time 
1638643506260: [Idle] Trigger Idle 
1638643546063: [Idle] Set idle time 
1638644449289: [Idle] Trigger Idle 
1638644449302: [Idle] Set idle time 
1638644457031: [Idle] Trigger Idle 
1638644505110: [Idle] Set idle time 
1638673130236: [Idle] Trigger Idle (3) 
1638673130242: [Idle] Set idle time 
1638673130249: [Idle] Trigger Idle 
1638674066152: [Idle] Set idle time 
1638674094477: [Idle] Trigger Idle (2) 
1638674094484: [Idle] Set idle time 
1638675049422: [Idle] Trigger Idle 
1638675049430: [Idle] Set idle time 
1638675057540: [Idle] Trigger Idle 
1638676034107: [Idle] Set idle time (2) 
1638677630284: [Idle] Trigger Idle (6) 
1638677643990: [Idle] Set idle time (7)
```

**Comment by johannesjo** [comment] 2021-12-05 09:09
Thank you for open this up. It's a duplicate of #1684

Help debugging this would be very welcome!

**Closed by johannesjo** 2021-12-05 09:09 UTC
