### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by nomare** [johannesjo/super-productivity#1704] opened 2021-12-01 07:34 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
task (webpack:///src/app/features/idle/idle.service.ts:137:22)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
```

### Meta Info
META: SP7.8.0 Electron – ru – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638343984356: [Idle] Set idle time (5) 
1638343985260: [Idle] Trigger Idle 
1638343989422: [Idle] Set idle time (5) 
1638343990263: [Idle] Trigger Idle 
1638343994477: [Idle] Set idle time (5) 
1638343995273: [Idle] Trigger Idle 
1638343999524: [Idle] Set idle time (5) 
1638344000284: [Idle] Trigger Idle 
1638344004582: [Idle] Set idle time (5) 
1638344005300: [Idle] Trigger Idle 
1638344009624: [Idle] Set idle time (5) 
1638344010310: [Idle] Trigger Idle 
1638344014691: [Idle] Set idle time (5) 
1638344015316: [Idle] Trigger Idle 
1638344019741: [Idle] Set idle time (5) 
1638344020331: [Idle] Trigger Idle 
1638344024748: [Idle] Set idle time (5) 
1638344025335: [Idle] Trigger Idle 
1638344029750: [Idle] Set idle time (5) 
1638344030352: [Idle] Trigger Idle 
1638344034753: [Idle] Set idle time (5) 
1638344035361: [Idle] Trigger Idle 
1638344039759: [Idle] Set idle time (5) 
1638344040361: [Idle] Trigger Idle 
1638344048765: [Idle] Set idle time (9) 
1638344049282: [Pomodoro] Skip Break 
1638344049282: [Task] Toggle start 
1638344049282: [Persistence] Save to DB 
1638344049283: [Task] SetCurrentTask 
1638344049283: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment] 2021-12-01 08:48
Thank you very much for reporting looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-01 08:48 UTC
