### ISSUE TITLE
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'    at statSync (node:fs:1615:3)    at t.statSync (node:electron/js2c/asar_bundle:2:4557)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40    at Array.map ()    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71    at new Promise ()

### ISSUE THREAD

**Issue by NAICOLAS** [johannesjo/super-productivity#2903] opened 2023-12-07 09:55 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
```

### Meta Info
META: SP7.16.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1701942796647: [FocusMode] Set focus session elapsed time 
1701942796736: [SP_ALL] Load(import) all data 
1701942796737: [SP_ALL] All Data was loaded 
1701942808636: [FocusMode] Set focus session elapsed time 
1701942808690: [SP_ALL] Load(import) all data 
1701942808690: [SP_ALL] All Data was loaded 
1701942823254: [Layout] Toggle SideBar 
1701942832621: [FocusMode] Set focus session elapsed time 
1701942832664: [SP_ALL] Load(import) all data 
1701942832665: [SP_ALL] All Data was loaded
```

**Comment by codeling** [comment] 2023-12-15 09:55
Duplicate of https://github.com/johannesjo/super-productivity/issues/2901

**Closed** 2023-12-15 10:42 UTC
Labels: bug, help wanted
