### ISSUE TITLE
allow using self-hosted gitlab instances

### ISSUE THREAD

**Issue by javierfolcini** [johannesjo/super-productivity#740] opened 2020-12-23 11:08 UTC
## Problem Statement
GitLab integration is nice but it doesn't work with self-hosted instances.

## :grey_question: Possible Solution
Allow using self-hosted instances of Gitlab.

**Comment by johannesjo** [comment] 2020-12-23 13:21
Thanks for opening this up. This is a duplicate of #337

**Closed by johannesjo** 2020-12-23 13:21 UTC
Labels: enhancement

**Comment by javierfolcini** [comment] 2020-12-23 13:55
you re right, thanks!
