### ISSUE TITLE
TypeError: Cannot set property 'boundary' of undefined

### ISSUE THREAD

**Issue by emmie** [johannesjo/super-productivity#479] opened 2020-08-05 19:33 UTC
### Steps to Reproduce

1. Activate Google Drive Syncronization
2. dialog box appears:
    > Google Drive: No file named "SUPER_PRODUCTIVITY_SYNC.json" was found. Create as sync file on Google Drive?
3. Click on "OK"

### Stacktrace
```
MultiPartBuilder (webpack:///src/app/features/google/util/multi-part-builder.ts:7:18)
encodeURIComponent (webpack:///src/app/features/google/google-api.service.ts:249:32)
saveFile$ (webpack:///src/app/features/google/store/google-drive-sync.effects.ts:180:29)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/mergeMap.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/mergeMap.js:51:17)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
this.project.call (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:41:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
this.destination.error (webpack:///node_modules/rxjs/_esm5/internal/operators/filter.js:38:29)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
```

### Meta Info
META: SP5.5.4 Electron – es – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.4 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1596655036097: [GoogleDriveSync] Save To Flow 
1596655036100: [GoogleDriveSync] Save To Cancel 
1596655036102: [GoogleDriveSync] Change Sync File Name 
1596655540784: [GoogleDriveSync] Save For Sync 
1596655540785: [GoogleDriveSync] Save To Flow 
1596655540785: [GoogleDriveSync] Save To Cancel 
1596655540786: [GoogleDriveSync] Change Sync File Name 
1596655551913: [GoogleDriveSync] Create Sync File 
1596655560305: [SP_ALL] Load(import) all data 
1596655560314: [SP_ALL] All Data was loaded 
1596655560323: [WorkContext] Set Active Work Context 
1596655560347: [Task] SetSelectedTask 
1596655560811: [Note] Load Note State 
1596655560834: [Bookmark] Load Bookmark State 
1596655560841: [Metric] Load Metric State 
1596655560844: [Improvement] Load Improvement State 
1596655560846: [Obstruction] Load Obstruction State 
1596655560847: [Project] Load Project related Data Success 
1596655560848: [Improvement] Clear Hidden Improvements 
1596655560848: [Improvement] Delete multiple Improvements 
1596655575096: [GoogleDriveSync] Save For Sync 
1596655575097: [GoogleDriveSync] Save To Flow 
1596655575098: [GoogleDriveSync] Save To Cancel 
1596655575099: [GoogleDriveSync] Change Sync File Name 
1596655586477: [GoogleDriveSync] Create Sync File
```

**Comment by johannesjo** [comment] 2020-08-05 21:24
Likely a duplicate of #474

**Closed by johannesjo** 2020-08-05 21:24 UTC

**Comment by johannesjo** [comment] 2020-08-07 15:37
Should be fixed with the next release.
