### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'color')

### ISSUE THREAD

**Issue by riyaan** [johannesjo/super-productivity#3214] opened 2024-06-12 10:39 UTC
### Steps to Reproduce

1. Update the windows app to version 8.0.7
2. In the left pane, select the ellipses next to Today -> Worklog
3. Click on any of the Dates
4. The popup appears.

### Meta Info
META: SP8.0.7 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0

### Stacktrace
```
i0 (webpack:///src/app/features/worklog/worklog.component.html:134:34)
setSelectedIndex (webpack:///node_modules/@angular/core/fesm2015/core.mjs:12112:8)
setBindingIndex (webpack:///node_modules/@angular/core/fesm2015/core.mjs:11975:12)
viewAttachedToChangeDetector (webpack:///node_modules/@angular/core/fesm2015/core.mjs:13025:16)
executeCheckHooks (webpack:///node_modules/@angular/core/fesm2015/core.mjs:11999:29)
viewAttachedToChangeDetector (webpack:///node_modules/@angular/core/fesm2015/core.mjs:13025:16)
executeCheckHooks (webpack:///node_modules/@angular/core/fesm2015/core.mjs:11999:29)
viewAttachedToChangeDetector (webpack:///node_modules/@angular/core/fesm2015/core.mjs:13025:16)
executeCheckHooks (webpack:///node_modules/@angular/core/fesm2015/core.mjs:11999:29)
viewAttachedToChangeDetector (webpack:///node_modules/@angular/core/fesm2015/core.mjs:13025:16)
```

### Actions Before Error
```
1718188298709: [Task] Add time spent 
1718188298712: [Tag] Update Work End for Tag 
1718188298714: [Persistence] Save to DB (2) 
1718188358710: [Task] Add time spent 
1718188358714: [Tag] Update Work End for Tag 
1718188358716: [Persistence] Save to DB (2) 
1718188418705: [Task] Add time spent 
1718188418709: [Tag] Update Work End for Tag 
1718188418711: [Persistence] Save to DB (2) 
1718188458169: [Task] Add time spent 
1718188458172: [Tag] Update Work End for Tag 
1718188458174: [Persistence] Save to DB (2) 
1718188458415: [Task] Add time spent 
1718188458418: [Tag] Update Work End for Tag 
1718188458419: [Persistence] Save to DB (2) 
1718188459425: [Task] Add time spent 
1718188459428: [Tag] Update Work End for Tag 
1718188459429: [Persistence] Save to DB (2) 
1718188460413: [Task] Add time spent 
1718188460415: [Tag] Update Work End for Tag 
1718188460416: [Persistence] Save to DB (2) 
1718188461422: [Task] Add time spent 
1718188461424: [Tag] Update Work End for Tag 
1718188461425: [Persistence] Save to DB (2) 
1718188462425: [Task] Add time spent 
1718188462427: [Tag] Update Work End for Tag 
1718188462428: [Persistence] Save to DB (2) 
1718188463559: [FocusMode] Set focus session elapsed time 
1718188463705: [SP_ALL] Load(import) all data 
1718188463708: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment] 2024-06-13 07:15
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by kvieto** [comment] 2024-06-13 11:19
duplicate https://github.com/johannesjo/super-productivity/issues/3208

**Comment by kvieto** [comment] 2024-06-13 11:23
> Hey there! Thank you very much for reporting this!
> 
> It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to [contact@super-productivity.com](mailto:contact@super-productivity.com), so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

duplicate https://github.com/johannesjo/super-productivity/issues/3208

at least one task of the day must not be assigned to a project.

**Comment by riyaan** [comment] 2024-06-13 11:25
Hi. Thanks for responding to my email.

I have sent an email (*Subject: Issue #3214 - Data export*) with the copy
of my data.

Regards,
Riyaan


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Jagdfalke** [comment] 2024-06-14 05:49
Duplicate of #3208

**Closed by Jagdfalke** 2024-06-14 05:49 UTC
