### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by PabloHdzVizcarra** [johannesjo/super-productivity#1727] opened 2021-12-02 16:00 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
task (webpack:///src/app/features/idle/idle.service.ts:137:22)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638460747847: [Pomodoro] Pause Pomodoro 
1638460751185: [Idle] Set idle time (4) 
1638460752115: [Idle] Trigger Idle 
1638460756219: [Idle] Set idle time (5) 
1638460757116: [Idle] Trigger Idle 
1638460761253: [Idle] Set idle time (5) 
1638460762126: [Idle] Trigger Idle 
1638460766280: [Idle] Set idle time (5) 
1638460767127: [Idle] Trigger Idle 
1638460771314: [Idle] Set idle time (5) 
1638460772132: [Idle] Trigger Idle 
1638460776327: [Idle] Set idle time (5) 
1638460777147: [Idle] Trigger Idle 
1638460781372: [Idle] Set idle time (5) 
1638460782160: [Idle] Trigger Idle 
1638460786425: [Idle] Set idle time (5) 
1638460787166: [Idle] Trigger Idle 
1638460791439: [Idle] Set idle time (5) 
1638460792166: [Idle] Trigger Idle 
1638460795454: [Idle] Set idle time (4) 
1638460795836: [Pomodoro] Finish Pomodoro Session 
1638460795837: [Task] Toggle start 
1638460795837: [Persistence] Save to DB 
1638460795837: [Task] SetCurrentTask 
1638460795838: [Pomodoro] Start Pomodoro 
1638460795853: [Task] Add time spent 
1638460795854: [Project] Update Work End 
1638460795859: [Tag] Update Work End for Tag 
1638460795868: [Persistence] Save to DB (3)
```

**Comment by johannesjo** [comment] 2021-12-02 16:05
Thanks for reporting! Looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-02 16:05 UTC
