### ISSUE TITLE
Resize Left Menu

### ISSUE THREAD

**Issue by unonewcreative** [johannesjo/super-productivity#841] opened 2021-01-28 21:24 UTC
First of all I would like to start with that the the program is awesome. Therefore I would like help. I noticed that the left menu is not scalable therefore not showing the full text in the menu. A fix on this matter would make it more awesome. 

Cheers!

**Comment by johannesjo** [comment] 2021-01-29 14:50
Hi there! Thanks for opening this up! Looks like a duplicate of https://github.com/johannesjo/super-productivity/issues/297 though.

**Closed by johannesjo** 2021-01-29 14:50 UTC
Labels: enhancement

**Comment by unonewcreative** [comment] 2021-01-29 15:20
Ok sorry thanks guess I missed that one. Cheers
