### ISSUE TITLE
Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open. Error: UnknownError: Inte

### ISSUE THREAD

**Issue by felipevaldes** [johannesjo/super-productivity#386] opened 2020-06-04 16:47 UTC
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by ntlghb** [comment] 2020-06-05 08:17
Your Environment
META: SP5.2.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.2.1 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

Expected Behavior: pressed play button to log a todo

Error Log (Desktop only)

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open. Error: UnknownError: Internal error opening backing store for indexedDB.open. at t. (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:76:13) at file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1693335 at Object.throw (file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1693440) at apply (file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1692229) at t.invoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30) at Object.onInvoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28285:33) at t.invoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36) at e.run (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47) at apply (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38) at t.invokeTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
t.<anonymous> (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:76:13)
Ur (file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1693335)
Ur (file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1693440)
Ur (file:///snap/superproductivity/629/resources/app.asar/dist/main.b7cb82b0013ae989fd89.js:1:1692229)
t.invoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28285:33)
t.invoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
apply (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:891:38)
t.invokeTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
resolvePromise (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:832:39)
resolvePromise (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:784:21)
apply (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:894:21)
t.invokeTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28273:33)
t.invokeTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
drainMicroTaskQueue (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:601:39)
e.invoke (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:507:25)
p (file:///snap/superproductivity/629/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1671:18)

**Comment by johannesjo** [comment] 2020-06-05 11:35
Thank you for letting me know. Did you by any chance run 2 instances of the app when this error occurred?

**Comment by johannesjo** [comment] 2020-06-05 12:26
Closing as duplicate of #375

**Closed by johannesjo** 2020-06-05 12:26 UTC
Labels: bug

**Comment by ntlghb** [comment] 2020-06-15 07:18
> Thank you for letting me know. Did you by any chance run 2 instances of the app when this error occurred?

I wasn't aware that this was possible. If I did, gnome did not reflect it.
