### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by nomare** [johannesjo/super-productivity#1726] opened 2021-12-02 08:10 UTC
### Steps to Reproduce

1. On PC I did not press any key for 30 minutes, then I pressed "Go back to work" and got this error. 
2.
3.
4.

### Stacktrace
```
task (webpack:///src/app/features/idle/idle.service.ts:137:22)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)
_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)
```

### Meta Info
META: SP7.8.0 Electron – ru – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638431741087: [Idle] Set idle time 
1638431800410: [Idle] Trigger Idle (12) 
1638431801085: [Idle] Set idle time 
1638431860534: [Idle] Trigger Idle (12) 
1638431861089: [Idle] Set idle time 
1638431920649: [Idle] Trigger Idle (12) 
1638431921081: [Idle] Set idle time 
1638431980738: [Idle] Trigger Idle (12) 
1638431981081: [Idle] Set idle time 
1638432040820: [Idle] Trigger Idle (12) 
1638432041067: [Idle] Set idle time 
1638432100916: [Idle] Trigger Idle (12) 
1638432101066: [Idle] Set idle time 
1638432161039: [Idle] Trigger Idle (12) 
1638432161066: [Idle] Set idle time 
1638432216226: [Idle] Trigger Idle (11) 
1638432221074: [Idle] Set idle time 
1638432276306: [Idle] Trigger Idle (12) 
1638432281078: [Idle] Set idle time 
1638432336417: [Idle] Trigger Idle (12) 
1638432341062: [Idle] Set idle time 
1638432396534: [Idle] Trigger Idle (12) 
1638432401066: [Idle] Set idle time 
1638432416568: [Idle] Trigger Idle (4) 
1638432438381: [Idle] Set idle time (6) 
1638432438921: [Pomodoro] Finish Pomodoro Session 
1638432438922: [Task] Toggle start 
1638432438922: [Persistence] Save to DB 
1638432438923: [Task] SetCurrentTask 
1638432438924: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment] 2021-12-02 08:19
Hey there! Thanks for reporting. This looks like a duplicate of #1684 to me. Unfortunately I am unable to reproduce this myself. Would you maybe be willing to help me with debugging this?

**Closed** 2021-12-02 19:38 UTC
