### ISSUE TITLE
Error: Uncaught (in promise): Error: No correct localLastSync given nullError: No correct localLastSync given null    at e. (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3529073)    at Generator.next ()    at https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522395    at new C (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)    at fE (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)    at e._setLocalRevAndLastSync (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)    at e. (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528122)    at Generator.next ()    at a (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)    at l.invoke (https://app.super-productivity.com/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)

### ISSUE THREAD

**Issue by extropista** [johannesjo/super-productivity#796] opened 2021-01-14 19:59 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:289:12)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522395)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522140)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3528955)
cp.uploadAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:243:11)
Ur (https://app.super-productivity.com/main.333d3b4f46c620a0fa3e.js:1:3522197)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28281:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

### Meta Info
META: SP6.3.3 Browser – es-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4385.0 Safari/537.36

### Actions Before Error
```
1610653618226: [SP_ALL] Load(import) all data 
1610653618247: [SP_ALL] All Data was loaded 
1610653618353: [WorkContext] Set Active Work Context 
1610653618899: [Task] SetSelectedTask 
1610653653181: [Global Config] Update Global Config Section 
1610653653208: [Persistence] Save to DB 
1610654204435: [Global Config] Update Global Config Section 
1610654204637: [Persistence] Save to DB 
1610654205877: [Global Config] Update Global Config Section 
1610654205922: [Persistence] Save to DB 
1610654220140: [Global Config] Update Global Config Section 
1610654220158: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2021-01-14 20:16
Thanks for opening this up. Could you provide a little bit more context? Did this happen just once, or multiple times?

**Comment by johannesjo** [comment] 2021-02-06 19:22
Thanks for reporting. This is a duplicate of #720

**Closed by johannesjo** 2021-02-06 19:22 UTC
Labels: bug
