### ISSUE TITLE
Can't delete a tag 

### ISSUE THREAD

**Issue by MKarat** [johannesjo/super-productivity#1264] opened 2021-06-02 13:22 UTC
### Your Environment

- Version used: 7.0.0 (upgraded from 6.5.2 via Microsoft Store)
- Operating System and version: Windows 10 Pro (20H2)

### Expected Behavior

Tag is deleted

### Current Behavior

Tag isn't deleted

### Steps to Reproduce (for bugs)

1. Right-click on a tag
2. Click on "Delete Tag"
3. Click on "OK" on the warning message

### Console Output
console is clear
### Error Log (Desktop only)
[main.log](https://github.com/johannesjo/super-productivity/files/6584818/main.log)

**Comment by johannesjo** [comment] 2021-06-02 14:25
Hey there! Thank you very much for reporting this!

It looks like that for some reason a bit of your data might have gotten into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by emmansh** [comment] 2021-06-03 15:12
Same here. I can't delete a tag...

**Comment by johannesjo** [comment] 2021-06-04 12:54
This should be fixed with the next release (available on the edge channel shortly and as a real release tomorrow). Thank you very much for your help!

**Closed by johannesjo** 2021-06-04 12:54 UTC
Labels: bug

**Comment by MKarat** [comment] 2021-06-07 09:12
Great! Thanks for the quick fix!
