### ISSUE TITLE
Lost all data after updating from 5.4.2 to 5.5.2 (snap)

### ISSUE THREAD

**Issue by mjgwood** [johannesjo/super-productivity#468] opened 2020-07-31 06:30 UTC
### Your Environment
* Version used: 5.5.2 (snap)
* Operating System and version: Ubuntu 18.04.4
* Desktop Environment: GNOME

### Expected Behavior
Able to continue working with existing data after updating the app.

### Current Behavior
All data appears to have been lost during the update process. Only the default 'Super Productivity' project exists and all settings appear to have been reset.

### Steps to Reproduce (for bugs)
1. Use 5.4.2 (snap)
2. Update to 5.5.2 (N.B. I did not launch app for versions between 5.4.2 and 5.5.2)
3. Launch 5.5.2 - presented with blank app (data has not been migrated)

### Console Output
electron/js2c/renderer_init.js:82 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ electron/js2c/renderer_init.js:82
main.537ceab2d6dcf7127421.js:1 Persistent store granted
main.537ceab2d6dcf7127421.js:1 0 out of 61144 MiB used (0%)
main.537ceab2d6dcf7127421.js:1 Migrating model "?" to version from undefined to 2 Object
main.537ceab2d6dcf7127421.js:1 Migrating model "?" to version from undefined to 1 Object
main.537ceab2d6dcf7127421.js:1 Migrating model "task" to version from undefined to 3.3333 Object
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/runtime.c51bd5b1c616d9ffddc1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/main.537ceab2d6dcf7127421.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/reminder.fc53a8950e2e9cd6c010.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/lz.758d42083f84b546d14c.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/720/resources/app.asar/dist/styles.7019285b763bf4d29f54.css.map: 

### Error Log (Desktop only)
Current log file is empty.

The only log file with any contents is `~/snap/superproductivity/673/.config/superProductivity/log.log`:

[2020-06-21 20:20:38.398] [error] Frontend Error: TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33) TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-21 20:20:39.736] [error] Frontend Error Stack: filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
_filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-21 20:21:06.574] [error] Frontend Error: TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33) TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-21 20:21:08.795] [error] Frontend Error Stack: filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
_filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-22 21:55:31.991] [error] Frontend Error: TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33) TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-22 21:55:33.235] [error] Frontend Error Stack: filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
_filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-23 17:58:53.637] [error] Frontend Error: TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33) TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
    at file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379
    at Object.next (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
    at apply (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
    at t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-23 17:58:54.702] [error] Frontend Error Stack: filter (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
_filterIdsForProject (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
getCompleteStateForWorkContext (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
t.<anonymous> (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:150:58)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829379)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2829484)
Ur (file:///snap/superproductivity/656/resources/app.asar/dist/main.ea037dc63c283f59730f.js:1:2832404)
t.invoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/656/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-25 21:40:23.376] [error] Frontend Error: TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:151:58)
    at file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263343
    at Object.next (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263448)
    at apply (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3266366)
    at t.invoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33) TypeError: Cannot read property 'projectId' of undefined
    at filter (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
    at Array.filter (<anonymous>)
    at _filterIdsForProject (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
    at getCompleteStateForWorkContext (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
    at t.<anonymous> (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:151:58)
    at file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263343
    at Object.next (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263448)
    at apply (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3266366)
    at t.invoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
    at Object.onInvoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
[2020-06-25 21:40:24.422] [error] Frontend Error Stack: filter (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:36:51)
_filterIdsForProject (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:34:117)
getCompleteStateForWorkContext (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/util/get-complete-state-for-work-context.util.ts:17:7)
t.<anonymous> (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/src/app/features/worklog/worklog.service.ts:151:58)
Ur (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263343)
Ur (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3263448)
Ur (file:///snap/superproductivity/673/resources/app.asar/dist/main.dfed7263d15fcd0c7469.js:1:3266366)
t.invoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/673/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)

**Comment by johannesjo** [comment] 2020-07-31 06:58
Thanks for reporting and I'm very sorry to hear this happened. Usually automatic backups should be created so I hope that you're able to restore the data.

I'll look into the data you provided as soon as I can

**Comment by mjgwood** [comment] 2020-07-31 07:10
It looks like the data is still in the old version's folder so I don't think it's lost fortunately. I'm not sure how I'd go about trying to restore it though. Thanks very much for the awesome app and such a quick response.

**Comment by johannesjo** [comment] 2020-07-31 10:49
I added a section to the readme: https://github.com/johannesjo/super-productivity#automatic-backups

**Comment by mjgwood** [comment] 2020-08-01 03:02
Too easy, thank you very much Johannes!

**Comment by mjgwood** [comment] 2020-08-06 11:59
Experienced the same issue when updating to 5.5.4 today. All my data was missing when initially launching the app but I was able to import the backup again and everything seems to be there. I toggled off and on and saved Automatic Backups in Settings - not sure if that will make a difference but hoping I won't have this issue with each new release.

**Comment by johannesjo** [comment] 2020-08-06 21:24
Thank you for letting me know and I have to say that I am sorry to hear that. This should normally not be the case (and I never encountered this behavior myself). I am not sure why you did encounter this, to be honest, but I suspect IndexedDb to responsible for this. I can't pinpoint it exactly. Are you running (relatively) low on disk space by any chance?

**Comment by mjgwood** [comment] 2020-08-07 00:34
It is strange that it suddenly started happening. I don't know if the failed auto-import could be related to the [other issue](https://github.com/johannesjo/super-productivity/issues/481#issue-674256127) I'm seeing but I'm wondering if maybe I should just wipe the app from my machine and start over with a fresh install?

I'm sure I was low on disk space at some point fairly recently, but I currently have about 60GB free. If there's any other information that could be helpful just let me know.

**Comment by mjgwood** [comment] 2020-08-10 01:13
Same issue with the most recent updates. Hopefully it won't happen again now that I've received the fixed data from you for the other issue I referenced.

**Comment by mjgwood** [comment] 2020-08-31 04:52
Same issue when updating to v5.6.5 snap sadly. Seems like it has also messed up the Dropbox sync.

**Comment by johannesjo** [comment] 2020-08-31 08:10
@mjgwood could you please open up a new issue with some more info?

**Comment by mjgwood** [comment] 2020-08-31 12:07
Sure thing. If the previous information was not useful, what info should I provide that would help find the issue?

The issue isn't any different than what I described in the first comment - the data backup is just not being imported automatically when updating the app to a new version.

**Comment by johannesjo** [comment] 2020-08-31 12:18
@mjgwood sorry, Monday morning confusion. I didn't realize that you were the original poster of this issue too... 
Did the automatic backups work at least?

To recap/clarify:
1. You updated the app via snapcraft (or the update manager or whatever)
2. After the next start all data is lost without any error?
3. After trying to get the data from Dropbox, you accidentally overwrote the Dropbox data as well?

**Comment by mjgwood** [comment] 2020-09-02 04:43
Haha no problem! That description is accurate - my data was backed up automatically, but it was not imported automatically after updating to a new version. I can manually import the backed up data and everything seems to work fine after that.

1. Correct
2. Correct - I am presented with essentially a fresh install. All data and settings are reset to default.
3. I don't think there is an issue here actually. When I manually imported my data I got a message saying that the dates of my local and Dropbox data did not match up and that something must have gone wrong. But after ignoring that message everything still seems to be syncing correctly and updates on my PC are reflected on my phone.

**Comment by johannesjo** [comment] 2020-09-02 19:42
I think this might be related to IndexedDB not being reliable. Chrome/Electron does seem to treat as a cache rather than serious storage at times and data is deleted when the disk is full for some reason. It's definitely on my list to change that and very high on it too. In fact, I already started working on it but it's not a small task, so we might need to rely on the automatic backups a little longer. :-(

**Comment by mjgwood** [comment] 2020-09-03 07:12
Ah yes we discussed the disk space when I initially raised this issue but I still have around 15% available. Maybe that could be considered relatively low but I'd be surprised if that's the cause, and I would have expected to see others experiencing the same issue if it was.

Anyway, I'm just glad to hear you have a starting point for fixing it. Obviously it only happens occassionally so it's not a major inconvenience that will prevent me from using this otherwise fantastic piece of software. Best of luck finding a solution!

**Comment by johannesjo** [comment] 2020-09-03 09:34
I am not a 100% sure, but that could very well be the cause. Depending on what I do the tmp folder can get quite big on Ubuntu without me even noticing it.

**Comment by mjgwood** [comment] 2020-09-03 10:59
Well you'd have a better idea than I do haha. Let me know if I can help at all when you get around to looking deeper into the issue.

**Comment by johannesjo** [comment] 2020-09-03 11:11
Thank you! :)

**Comment by johannesjo** [comment] 2020-09-22 13:49
I am closing this, as there isn't much we can do about this atm.

**Closed by johannesjo** 2020-09-22 13:49 UTC
Labels: bug, db
