### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by irsyadtiket** [johannesjo/super-productivity#2798] opened 2023-09-29 02:02 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:1014179
    at _.project (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:1014201)
    at _next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3478842)
    at _.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3466971)
    at _next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3467197)
    at _.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3466971)
    at _next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3478940)
    at _.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3466971)
    at _next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3478353)
    at _.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3466971)
```

### Meta Info
META: SP7.11.5 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.11.5 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36

### Actions Before Error
```
1695952696595: [Bookmark] Load Bookmark State 
1695952696595: [Project] Load Project related Data Success 
1695952696596: [Improvement] Clear Hidden Improvements 
1695952696596: [Improvement] Delete multiple Improvements 
1695952925700: [Project] Add Project 
1695952925705: [Persistence] Save to DB 
1695952929856: [WorkContext] Set Active Work Context 
1695952929883: [Task] SetSelectedTask 
1695952929916: [Bookmark] Load Bookmark State 
1695952929919: [Project] Load Project related Data Success 
1695952929922: [Improvement] Clear Hidden Improvements 
1695952929922: [Improvement] Delete multiple Improvements 
1695952964010: [SP_ALL] Load(import) all data 
1695952964016: [SP_ALL] All Data was loaded 
1695952964071: [WorkContext] Set Active Work Context 
1695952964085: [Task] SetSelectedTask 
1695952964932: [Bookmark] Load Bookmark State 
1695952964933: [Project] Load Project related Data Success 
1695952964934: [Improvement] Clear Hidden Improvements 
1695952964935: [Improvement] Delete multiple Improvements 
1695952981455: [SP_ALL] Load(import) all data 
1695952981459: [SP_ALL] All Data was loaded 
1695952981494: [WorkContext] Set Active Work Context 
1695952981510: [Task] SetSelectedTask 
1695952982192: [Bookmark] Load Bookmark State 
1695952982192: [Project] Load Project related Data Success 
1695952982193: [Improvement] Clear Hidden Improvements 
1695952982194: [Improvement] Delete multiple Improvements 
1695952985374: [Project] Update Project Issue Provider Cfg 
1695952985543: [Persistence] Save to DB
```

**Comment by codeling** [comment] 2023-12-15 12:03
Duplicate of https://github.com/johannesjo/super-productivity/issues/2793 .

**Closed** 2023-12-18 15:38 UTC
