### ISSUE TITLE
suError: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': 

### ISSUE THREAD

**Issue by bigmpc** [johannesjo/super-productivity#613] opened 2020-10-26 17:10 UTC
suError: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    at Proxy.n (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:2356764)    at Proxy.s (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:2357846)    at t. (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:2358892)    at Generator.next ()    at a (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:2358230)    at l.invoke (file:///snap/superproductivity/912/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)    at Object.onInvoke (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:1544051)    at l.invoke (file:///snap/superproductivity/912/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)    at i.run (file:///snap/superproductivity/912/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)    at file:///snap/superproductivity/912/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
function (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:150:25)
function (webpack:///node_modules/idb/build/esm/index.js:65:24)
constructor (webpack:///src/app/core/persistence/database.service.ts:44:49)
Ur (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:2358230)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///snap/superproductivity/912/resources/app.asar/dist/main.099adb7ad2df75974a4b.js:1:1390011)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27488:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27476:32)
```

### Meta Info
META: SP6.0.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.0.1 Chrome/85.0.4183.121 Electron/10.1.5 Safari/537.36

### Actions Before Error
```
1603724898289: [Task] Add time spent 
1603724898291: [Project] Update Work End 
1603724898293: [Tag] Update Work End for Tag 
1603724898302: [Persistence] Save to DB 
1603724898302: [Persistence] Save to DB 
1603724898303: [Persistence] Save to DB 
1603724899289: [Task] Add time spent 
1603724899291: [Project] Update Work End 
1603724899292: [Tag] Update Work End for Tag 
1603724899302: [Persistence] Save to DB 
1603724899302: [Persistence] Save to DB 
1603724899303: [Persistence] Save to DB 
1603724900289: [Task] Add time spent 
1603724900292: [Project] Update Work End 
1603724900293: [Tag] Update Work End for Tag 
1603724900302: [Persistence] Save to DB 
1603724900302: [Persistence] Save to DB 
1603724900303: [Persistence] Save to DB 
1603724901289: [Task] Add time spent 
1603724901291: [Project] Update Work End 
1603724901293: [Tag] Update Work End for Tag 
1603724901296: [Persistence] Save to DB 
1603724901296: [Persistence] Save to DB 
1603724901296: [Persistence] Save to DB 
1603732152008: [Task] Add time spent 
1603732152008: [Project] Update Work End 
1603732152008: [Tag] Update Work End for Tag 
1603732152011: [Persistence] Save to DB 
1603732152011: [Persistence] Save to DB 
1603732152011: [Persistence] Save to DB
```

**Comment by johannesjo** [comment] 2020-10-26 18:27
Thank you very much for reporting! Unfortunately, there is not much I could do atm. I hope that the chrome people will fix this at some point.

**Comment by johannesjo** [comment] 2021-01-13 21:28
I am closing this as duplicate of #737 (although this was first, but on 737 there is more info.

**Closed by johannesjo** 2021-01-13 21:28 UTC
Labels: bug, db, external issue
