### ISSUE TITLE
F-Droid app has not been updated since  Apr 17, 2023

### ISSUE THREAD

**Issue by ghost** [johannesjo/super-productivity#3745] opened 2024-12-09 19:37 UTC
## Problem Statement

The F-Droid app has not been updated since the 17th of april 2023.
Without any notice on the F-Droid page.

## :grey_question: Possible Solution

- Update the app on F-Droid.
- Remove the app from F-Droid.
- Display a notice on F-Droid page about how the app is outdated.

## :arrow_heading_up: Describe alternatives you've considered

I have made an [issue](https://github.com/johannesjo/super-productivity/issues/3733) for adding the app to Accrescent. 
Regarding security it is  in many ways is better than F-Droid and possibly an alternative to replace F-Droid.
But the application has not been added yet.

## :heavy_plus_sign: Additional context

It would be nice to have the Android application up-to-date on F-Droid, accrescent or both!

**Comment by johannesjo** [comment] 2024-12-15 10:48
Not sure why this is the case. Haven't fully understood when their build chain triggers and when not. Help with this would be welcome!

**Comment by Chrisimx** [comment] 2024-12-22 08:35
I've now created a merge request on the f-droid metadata gitlab: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/17788

But the problem is that with the v11.0.3 tag the versionCode is invalid as it's over the maximum integer value bounds. This was fixed with b8016de2c3d03aa925c9af7a666f891c0d781419 . But f-droid works like this for determining the current version / version updates: It goes through all tags and takes the one with the highest versionCode as the newest version. In our case, however, this tag is not buildable for f-droid as the versionCode is invalid. You can build b8016de2c3d03aa925c9af7a666f891c0d781419 which I've done now. But the f-droid update check is effectively broken because the v11.0.3 has a versionCode larger than any versionCode that will ever be used in the future. As there is no other option, would it be possible to move the v11.0.3 tag by one commit to b8016de2c3d03aa925c9af7a666f891c0d781419 ?

**Comment by Chrisimx** [comment] 2024-12-22 11:59
I've come to the idea that maybe it would be easier (no force-pushing and no influence on other packages like the AUR package) to just create a new tag like "v11.0.3-android-fixed". In the f-droid metadata a RegEx can be included to filter the tags. Using this I can exclude the specific broken tag and include the  "v11.0.3-android-fixed" one. In the future, the tag naming scheme can continue like normal with "v${VERSION}"

**Comment by Chrisimx** [comment] 2024-12-31 13:50
> Slightly unrelated, but I noticed there is a google play icon but not an F-Droid one in the release notes.

The icon would have to be added as `fastlane/metadata/android/en-US/images/icon.png`, then it should show on f-droid

**Comment by Chrisimx** [comment] 2024-12-31 14:52
As my MR on the f-droid data repo has been merged, the current version should appear on f-droid when the f-droid build cycle is completed in about 2 days, which will resolve this issue. The broken tag is now just excluded, so no further action is necessary

**Closed as completed** 2024-12-31 16:00 UTC
Labels: enhancement, help wanted

**Comment by johannesjo** [comment] 2025-01-02 18:09
Wow! Thank you so much @Chrisimx !!! This is great!
