### ISSUE TITLE
can it create new Issues in Jira if we add a Task to a Project which is linked to Jira?  thank you.

### ISSUE THREAD

**Issue by tustinn** [johannesjo/super-productivity#550] opened 2020-09-30 05:28 UTC
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment] 2020-10-05 19:49
If I understand you correctly that this is a duplicate of #381

**Closed by johannesjo** 2020-10-05 19:49 UTC
