### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by JustusCF** [johannesjo/super-productivity#1747] opened 2021-12-08 07:44 UTC
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956876)
    at b.next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956105)
    at T._next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955288)
    at T.next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955062)
    at v._next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:975388)
    at v.next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955062)
    at O.next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:952809)
    at b._next (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Users/cf_ju/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638938476589: [Idle] Set idle time (5) 
1638938477034: [Idle] Trigger Idle 
1638938481604: [Idle] Set idle time (5) 
1638938482046: [Idle] Trigger Idle 
1638938486613: [Idle] Set idle time (5) 
1638938487049: [Idle] Trigger Idle 
1638938491617: [Idle] Set idle time (5) 
1638938492052: [Idle] Trigger Idle 
1638938496628: [Idle] Set idle time (5) 
1638938497059: [Idle] Trigger Idle 
1638938501636: [Idle] Set idle time (5) 
1638938502062: [Idle] Trigger Idle 
1638938506645: [Idle] Set idle time (5) 
1638938507077: [Idle] Trigger Idle 
1638938511660: [Idle] Set idle time (5) 
1638938512078: [Idle] Trigger Idle 
1638938516691: [Idle] Set idle time (5) 
1638938517088: [Idle] Trigger Idle 
1638938521705: [Idle] Set idle time (5) 
1638938522091: [Idle] Trigger Idle 
1638938526744: [Idle] Set idle time (5) 
1638938527103: [Idle] Trigger Idle 
1638938531802: [Idle] Set idle time (5) 
1638938532116: [Idle] Trigger Idle 
1638938538852: [Idle] Set idle time (7) 
1638938539444: [Pomodoro] Skip Break 
1638938539445: [Task] Toggle start 
1638938539445: [Persistence] Save to DB 
1638938539445: [Task] SetCurrentTask 
1638938539446: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment] 2021-12-09 10:00
Thank you for opening this up! Looks like a duplicate of #1684

**Closed by johannesjo** 2021-12-09 10:00 UTC
