### ISSUE TITLE
Cannot reopen the application

### ISSUE THREAD

**Issue by Gontran08** [johannesjo/super-productivity#18] opened 2017-11-20 18:05 UTC
If I hide the application using the window button, I cannot reopen it using the application launcher, I have to use the keyboard shortcut. I have to kill the application to be able to use the launcher again. I also cannot see that the application is still active in the taskbar. Closing the application has the same effect that hiding it.

**Comment by johannesjo** [comment] 2017-11-20 19:19
Thanks for reporting! May I ask which OS you're on and which desktop environment you're using?

**Comment by HarmtH** [comment] 2017-11-20 20:22
I don't know if this is the same issue, but if I try to start the application, while it is still running (window is closed, but icon still in the notification area), it won't show the main window. This is with the Ubuntu snap package under Ubuntu 17.10.

```
blackbox ~% superproductivity 
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/snap/superproductivity/5/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/snap/superproductivity/5/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/snap/superproductivity/5/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)
```
I would expect that the main window of the currently running instance is shown when I try to run ```superproductivity``` again.

**Comment by johannesjo** [comment] 2017-11-20 20:26
Thank you. I'll look into it tomorrow. Haven't had any issue like this myself, but maybe I overlooked something.

**Comment by Gontran08** [comment] 2017-11-20 20:31
I'm using Ubuntu 17.10 with Gnome Shell.

**Comment by Atem18** [comment] 2017-11-21 08:48
Same problem on Debian Sid with Appimage and DEB package with Gnome 3.26.

**Comment by johannesjo** [comment] 2017-11-21 11:46
Ok I dug into it. Problem seems to be that the app is supposed to minimize to tray so it keeps tracking your time until closed via the tray icon (or after you finished your daily work inside the app). This does not work well for gnome, as tray icons are deprecated and weirdly hidden or not shown at all and not everybody has the shell extension installed. 

I would recommend trying to install the extension for now (https://github.com/johannesjo/gnome-shell-extension-super-productivity) at least until the next release is out.  

As a behavior where neither tray icon nor extension are available the app will "now" (when I push the next release) simply close.

**Comment by johannesjo** [comment] 2017-11-21 14:22
I published a new release. Could you please check, if it works out for you as expected now?
https://github.com/johannesjo/super-productivity/releases/tag/v1.4.0

**Comment by Atem18** [comment] 2017-11-21 14:48
@johannesjo It's worse, application relaunch again and again with that error:
![screenshot from 2017-11-21 15-45-39](https://user-images.githubusercontent.com/2875254/33078486-1dda4046-ced3-11e7-8998-683bd7488fc4.png)

Using the DEB package on Debian Sid with Gnome Shell

**Comment by GhisF** [comment] 2017-11-21 14:51
Using the DEB package on Ubuntu 17.10, the problem is solved for me.

**Comment by Gontran08** [comment] 2017-11-21 15:03
Works fine for me on Ubuntu 17.10. Thanks!

**Comment by johannesjo** [comment] 2017-11-21 15:03
@Atem18 you mean the `Error: Cannot find module '../dialog'` error?

**Comment by Atem18** [comment] 2017-11-21 15:04
@johannesjo Yes, it does not append on my screenshot but yeah

**Comment by johannesjo** [comment] 2017-11-21 15:06
@Atem18 Ok thanks! and it only appears when trying to reopen the application, after closing it once before?

**Comment by Atem18** [comment] 2017-11-21 15:06
@johannesjo Yes !

**Comment by johannesjo** [comment] 2017-11-21 19:01
Ok I suppose we're dealing with different issues here. 

@HarmtH does your error persist with the newest version? 

@Atem18 could you please also check again if the error still persists in this scenario, when you kill the apps process first (e.g. `killall superproductivity` and then starting and restarting ). If not, it could be related to this: https://github.com/electron/electron/issues/4279

**Comment by HarmtH** [comment] 2017-11-22 12:07
> @HarmtH does your error persist with the newest version?

I still get the same error-message (about the cannot find module '../dialog') when I try to start the application while it's already running, BUT it now raises the main window while doing so. I still think it shouldn't error, but my main issue is solved.

**Comment by johannesjo** [comment] 2017-11-22 13:17
@HarmtH @Atem18 I created two different issues for the problems you described.

**Comment by Atem18** [comment] 2017-11-23 09:15
@johannesjo Sure, I will fill the issue

**Closed** 2017-11-23 21:01 UTC
Labels: bug
