### ISSUE TITLE
Error: Uncaught (in promise): Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutation

### ISSUE THREAD

**Issue by ProfP30** [johannesjo/super-productivity#620] opened 2020-10-28 09:10 UTC
Error: Uncaught (in promise): Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations._init/<@https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2332636o@https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:2330942invoke@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6639onInvoke@https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344939invoke@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:6579run@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:2051P/<@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:16770invokeTask@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:7257onInvokeTask@https://app.super-productivity.com/main.2e71b6240367db6e355c.js:1:344828invokeTask@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:7178runTask@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:2666m@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:9251invokeTask@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:8336_@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:20152k@https://app.super-productivity.com/polyfills.250ebd3af63450554a58.js:1:20398

### Steps to Reproduce
1. Simply go to https://app.super-productivity.com/
2. I am using Firefox/82.0, 64bit, Windows10 2004 build 19041.572
3.
4.

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
value.hasOwnProperty (webpack:///node_modules/zone.js/fesm2015/zone.js:1165:20)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1277:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27476:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:179:50)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:583:38)
task.zone.runTask (webpack:///node_modules/zone.js/fesm2015/zone.js:492:24)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1598:17)
globalZoneAwareCallback (webpack:///node_modules/zone.js/fesm2015/zone.js:1624:31)
```

### Meta Info
META: SP6.0.1 Browser – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

### Actions Before Error
None
![temp1](https://user-images.githubusercontent.com/41631425/97415560-b230b700-1905-11eb-89e1-d108ceb7ad50.png)
![temp2](https://user-images.githubusercontent.com/41631425/97415585-bb218880-1905-11eb-9010-c955811df786.png)

**Comment by johannesjo** [comment] 2020-10-28 10:22
Thank you for reporting. I am unable to reproduce this. Might be related to some extension you are using? Generally, I'd recommend using a chromium-based browser such as chrome, brave, or edge or the desktop version of the app. The experience should be a bit more polished there.

**Comment by johannesjo** [comment] 2021-01-13 21:28
I am closing this as duplicate of #737 (although this was first, but on 737 there is more info.

**Closed by johannesjo** 2021-01-13 21:28 UTC
Labels: needs clarification
