### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by bpnolan** [johannesjo/super-productivity#398] opened 2020-06-11 17:25 UTC
META: SP5.3.4 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.3.4 Chrome/80.0.3987.165 Electron/8.3.0 Safari/537.36

### Stacktrace
```
Proxy.transaction (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/idb/build/esm/wrap-idb-value.js:150:26)
Proxy.put (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/idb/build/esm/index.js:65:25)
t.<anonymous> (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/src/app/core/persistence/database.service.ts:43:26)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007330)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2007435)
Ur (file:///snap/superproductivity/651/resources/app.asar/dist/main.05eca3ac60f95ea85f95.js:1:2006173)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:386:30)
Object.onInvoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:28134:33)
t.invoke (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:385:36)
e.run (file:///snap/superproductivity/651/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:143:47)
```

**Comment by johannesjo** [comment] 2020-06-11 18:20
Thank you. This can happen if there are two instances of the app running (or some other app accessing it's files). I definitely should improve the error message on though.

**Comment by johannesjo** [comment] 2020-06-11 21:35
Sorry, I misread the error message. This might be something else:
https://github.com/jensarps/IDBWrapper/issues/80

**Comment by johannesjo** [comment] 2020-09-26 21:10
May I ask if you encountered this or a similar issue again? I am asking because I had the feeling that this might have gotten better with the most recent electron version (introduced with Super Productivity 5.6.5) as nobody has reported a similar issue after that.

**Comment by bpnolan** [comment] 2020-09-28 14:46
Hmm I will leave a comment if I get the issue again. If memory serves I got it a couple weeks ago, nothing since then. Thanks.

**Comment by johannesjo** [comment] 2020-09-28 15:06
Thank you!

**Comment by johannesjo** [comment] 2020-10-18 20:41
I added some advanced data repair/restore functionality, as a compromise as there is no way to fix this completely without replacing the database adapter, which is not trivial and likely to cause new issues on other fronts. I think this is acceptable, as the issue only occurs rarely. I am closing this, but please open up new issues, if you encounter this again. Thank you!

**Comment by johannesjo** [comment] 2021-06-23 07:57
#816

**Comment by johannesjo** [comment] 2021-09-01 20:13
So after all this time, I've been finally able to reproduce the issue. Seems like that this only occurs for the snap version. Haven't found a way to fix it yet. Meanwhile using the deb or the AppImage can be used to avoid the issue.

**Comment by johannesjo** [comment] 2021-09-04 11:44
After digging into this I found out that error appeared whenever snapcraft made one of their automatic backups to the app (which can happen up to 4 times a day if there are updates for the app). Hopefully this is now handled in a more graceful manner. 

There is a [longer discussion here](https://forum.snapcraft.io/t/disabling-automatic-refresh-for-snap-from-store/707)  that revolves around how to best adjust the snap update cycle in case your interested.

**Closed** 2021-09-04 11:46 UTC
Labels: bug, db, external issue
