### ISSUE TITLE
'Repeat' for sub-tasks

### ISSUE THREAD

**Issue by Tushar-Mahapatra-Git** [johannesjo/super-productivity#1142] opened 2021-04-29 13:58 UTC
I created a task named 'Sprint xx.x', and added two sub-tasks named 'Meeting: XXX Daily Scrum' and 'Meeting: Daily Tag Up xxx xxxx' (as a sub-contractor, we have our own scrum and have to attend our prime contractor's scrum too). I wanted to 'repeat' the two sub-tasks but couldn't find the 'Repeat' option at the sub-task level. Would it be possible to add 'Repeat' at the sub-task level?

**Comment by Tushar-Mahapatra-Git** [comment] 2021-04-29 14:03
Also, can we have sub-tasks have tags and 'Add to My Day' independent of parent task?

**Comment by johannesjo** [comment] 2021-04-29 18:54
Hi there! Thanks for opening this up. This looks like a duplicate of this #427

**Comment by johannesjo** [comment] 2021-04-29 18:56
> Also, can we have sub-tasks have tags and 'Add to My Day' independent of parent task?

I've been thinking about this. Not sure. I think that this might be confusing for some people. Also it's not trivial to implement and we somehow would need to visually distinguish them. Best if you open up a new issue for this.

**Closed by johannesjo** 2021-04-29 18:56 UTC
Labels: enhancement
